{
 "title": "Github Domain Layer Only",
 "time": { "from": "2021-01-30T18:24:57.517Z", "to": "2022-02-02T18:24:57.519Z" },
 "panels": [
  {
   "title": "Added LOC",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(additions)\nFROM commits\nWHERE\n  $__timeFilter(created_at)\n  AND message not like '%Merge branch%'"
    }
   ]
  },
  {
   "title": "Deleted Loc",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(deletions)\nFROM commits\nWHERE\n  $__timeFilter(created_at) \n  AND message not like '%Merge branch%'\n"
    }
   ]
  },
  {
   "title": "Added and Deleted LOC Over Time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "with loc as(\n  SELECT\n    DATE_ADD(date(authored_date), INTERVAL 1 DAY) as time,\n    sum(additions) as added_LOC,\n    sum(deletions) as deleted_LOC\n  FROM commits\n  WHERE\n    message not like '%Merge branch%'\n    and $__timeFilter(authored_date)\n  group by 1\n)\n\nSELECT \n  timestamp(time) as time,\n  added_LOC as \"Added LOC\",\n  deleted_LOC as \"Deleted LOC\"\nFROM loc\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total Developers By Email",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct author_email) as developer_count\nFROM commits"
    }
   ]
  },
  {
   "title": "Open Pull Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() AS \"time\",\n  count(*) as value\nFROM \n  prs\nWHERE\n $__timeFilter(created_at) AND state = 'open'\ngroup by 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total Pull Request Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() AS \"time\",\n  count(*) as value\nFROM \n  prs\nWHERE\n $__timeFilter(created_at)\ngroup by 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total Commits",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(sha)\n  \nFROM commits\nWHERE\n  $__timeFilter(created_at)\n"
    }
   ]
  }
 ]
}