{
 "title": "Jenkins",
 "tags": [
  "Jenkins",
  "Data Source Specific Dashboard"
 ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Time Interval", "query": "Week : DAYOFWEEK, Month : DAY" }
  ]
 },
 "panels": [
  {
   "title": "Build Count",
   "type": "stat",
   "description": "1. Number of builds executed.\n2. The builds being calculated are filtered by \"build starting time\" (time filter at the upper-right corner) and \"Jira board\" (\"Choose Board\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() AS time,\n  count(*)\nFROM jenkins_builds\nWHERE\n  $__timeFilter(start_time)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Build Result Distribution",
   "type": "piechart",
   "description": "The percentage of successful, failed, and aborted builds.",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() AS time,\n  result as metric,\n  count(*) as value\nFROM jenkins_builds\nWHERE\n  $__timeFilter(start_time)\nGROUP BY 1,2\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Build Success Rate",
   "type": "stat",
   "description": "Number of successful builds / Number of total builds",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() AS time,\n  1.0 * count(case when result = 'SUCCESS' then 1 else null end)/count(*)\nFROM jenkins_builds\nWHERE\n  $__timeFilter(start_time)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Build Success Rate over Time",
   "type": "graph",
   "description": "1. Build success rate over time.\n2. The builds being calculated are filtered by \"build starting time\" (time filter at the upper-right corner) and \"Jira board\" (\"Choose Board\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "with _build_success_rate as(\r\n  SELECT\r\n    DATE_ADD(date(start_time), INTERVAL -$interval(date(start_time))+1 DAY) as time,\r\n    result\r\n  FROM\r\n    jenkins_builds\r\n  WHERE\r\n    $__timeFilter(start_time)\r\n)\r\n\r\nSELECT \r\n  timestamp(time) as time,\r\n  1.0 * sum(case when result = 'SUCCESS' then 1 else 0 end)/ count(*) as \"Build Success Rate\"\r\nFROM _build_success_rate\r\ngroup by 1\r\norder by 1"
    }
   ]
  }
 ]
}