# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: devlake-mysql

services:
  mysql:
    image: mysql:8
    volumes:
      - mysql-storage:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: lake
      MYSQL_USER: merico
      MYSQL_PASSWORD: merico
      TZ: UTC
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
      --skip-log-bin

  grafana:
    image: devlake.docker.scarf.sh/apache/devlake-dashboard:latest
    build:
      context: grafana/
    ports:
      - 3001:3000
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/dashboards/mysql:/etc/grafana/dashboards:ro
    environment:
      GF_SERVER_ROOT_URL: "http://localhost:4001/grafana"
      GF_USERS_DEFAULT_THEME: "light"
      DATABASE_TYPE: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: lake
      DATABASE_USER: merico
      DATABASE_PASSWORD: merico
      TZ: UTC
    restart: always
    depends_on:
      - mysql

  devlake:
    image: devlake-local:latest
    build:
      context: backend
      dockerfile: Dockerfile.local
      args:
        HTTPS_PROXY: "${HTTPS_PROXY}"
        GOPROXY: "${GOPROXY}"
    ports:
      - 8083:8080
    restart: always
    volumes:
      - devlake-log:/app/logs
    env_file:
      - ./.env
    environment:
      DB_URL: mysql://merico:merico@mysql:3306/lake?charset=utf8mb4&parseTime=True&loc=UTC
      E2E_DB_URL: mysql://merico:merico@mysql:3306/lake_test?charset=utf8mb4&parseTime=True&loc=UTC
      REMOTE_PLUGIN_DIR: ""
      FORCE_MIGRATION: "true"
      LOGGING_DIR: /app/logs
      TZ: UTC
    depends_on:
      - mysql

  config-ui:
    image: devlake.docker.scarf.sh/apache/devlake-config-ui:latest
    build:
      context: "config-ui"
    ports:
      - 4001:4000
    env_file:
      - ./.env
    environment:
      DEVLAKE_ENDPOINT: devlake:8080
      GRAFANA_ENDPOINT: grafana:3000
      TZ: UTC
    depends_on:
      - devlake

  authproxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.15.3-amd64
    network_mode: "host"
    ports:
      - 4181:4180
    env_file:
      - ./.env

volumes:
  mysql-storage:
  grafana-storage:
  devlake-log:
