import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react'
import styles from '../styles/Home.module.css'
import path from 'path'
const dotenv = require('dotenv')

export default function Home(props) {
  const { fileData } = props;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <p>change env NEW_VALUE</p>
        <input type="text" />
        <button>save</button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getStaticProps(context) {
  const fs = require('fs').promises

  const filePath = path.join(process.cwd(), 'data', '../../frontend/.env')
  const fileData = await fs.readFile(filePath)

  //TODO: take read value and overwrite env

  console.log(dotenv.parse(fileData))

  return {
    props: {
      fileData: JSON.stringify(fileData)
    },
  };
}
