{
 "title": "Average Requirement Lead Time By Process",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "board_id",
    "label": "Choose Board",
    "query": "select distinct concat(name, ': ', id) from jira_boards"
   }
  ]
 },
 "panels": [
  {
   "title": "Open",
   "type": "barchart",
   "description": "1. Compare the average time spent in each state of a requirement in the last 2 months.\n2. The requirements being calculated are the requirements delivered in the last 2 months.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with status_change_history as(\n\tSELECT\n\t\tjc.issue_id,\n\t\tjc.created as operation_time,\n\t\tjci.changelog_id,\n\t\tjci.from,\n\t\tjci.from_string,\n\t\tjci.to,\n\t\tjci.to_string,\n\t\tji.created as issue_creation_time,\n\t\tlag(jc.created) over(PARTITION BY jc.issue_id ORDER BY jc.created ASC) as last_operation_time,\n\t\tcase \n\t\t\twhen lag(jc.created) over(PARTITION BY jc.issue_id ORDER BY jc.created ASC) is not null then\n\t\t\tTIMESTAMPDIFF(MINUTE, lag(jc.created) over(PARTITION BY jc.issue_id ORDER BY jc.created ASC), jc.created)\n\t\t\telse TIMESTAMPDIFF(MINUTE, ji.created, jc.created) end as time_in_status\n\tFROM\n\t\tjira_changelogs jc\n\t\tJOIN jira_changelog_items jci ON jc.id = jci.changelog_id\n\t\tJOIN jira_issues ji ON jc.issue_id = ji.id\n\t\tjoin jira_board_issues jbi on ji.id = jbi.issue_id\n\tWHERE\n\t\tjci.field = 'status'\n\t\tand ji.std_type = 'Requirement'\n\t\tand ji.std_status = 'Resolved'\n\t\tand $__timeFilter(ji.resolution_date)\n    and jbi.board_id = $board_id\n),\n\ntime_in_status as(\n\tSELECT \n\t\tDATE_ADD(date(issue_creation_time), INTERVAL -DAY(date(issue_creation_time))+1 DAY) as time,\n\t\tfrom_string,\n\t\tround(avg(time_in_status)/1440,1) as time_in_status\n\tFROM status_change_history\n\tGROUP BY 1,2\n),\n\nthis_month as(\n\tselect \n\t\tDATE_ADD(date(CURDATE()), INTERVAL -DAY(date(CURDATE()))+1 DAY) as this_month\n),\n\nlast_month as(\n\tSELECT \n\t\tDATE_ADD(DATE_ADD(date(CURDATE()), INTERVAL -DAY(date(CURDATE()))+1 DAY), INTERVAL -1 MONTH) as last_month\n),\n\nthe_month_before_last as(\n\tSELECT \n\t\tDATE_ADD(DATE_ADD(date(CURDATE()), INTERVAL -DAY(date(CURDATE()))+1 DAY), INTERVAL -2 MONTH) as the_month_before_last\n),\n\nthis_month_record as(\n\tSELECT\n\t\tfrom_string as issue_status,\n\t\tcase when time in (SELECT this_month from this_month) then time_in_status else null end as this_month\n\tfrom time_in_status\n\tWHERE \n\t\ttime in (SELECT this_month from this_month)\n),\n\nlast_month_record as(\n\tSELECT\n\t\tfrom_string as issue_status,\n\t\tcase when time in (SELECT last_month from last_month) then time_in_status else null end as last_month\n\tfrom time_in_status\n\tWHERE \n\t\ttime in (SELECT last_month from last_month)\n),\n\nthe_month_before_last_record as(\n\tSELECT\n\t\tfrom_string as issue_status,\n\t\tcase when time in (SELECT the_month_before_last from the_month_before_last) then time_in_status else null end as the_month_before_last\n\tfrom time_in_status\n\tWHERE \n\t\ttime in (SELECT the_month_before_last from the_month_before_last)\n),\n\nfull_data as (\n  SELECT\n  \tcase \n  \t  when lmr.issue_status in ('打开','重新打开','待开发','Open','open','todo','to-do') then 'Open'\n  \t  when lmr.issue_status in ('处理中','设计中','in-progress','InProgress') then 'In-progress'\n  \t  when lmr.issue_status in ('开发自测','代码评审','open') then 'Code Review'\n  \t  when lmr.issue_status in ('测试中','testing','open') then 'Testing'\n  \t  when lmr.issue_status in ('发布中') then 'Build and Deploy' \n  \t  else 'Other' end as issue_status,\n  \tlmr.last_month,\n\t\t-- tmr.this_month,\n\t\ttmblr.the_month_before_last\n  FROM the_month_before_last_record tmblr\n  right join last_month_record lmr on lmr.issue_status = tmblr.issue_status \n)\n\nSELECT \n  '' as '',\n  the_month_before_last AS 'The Month Before Last',\n  last_month AS \"Last Month\"\n-- \tthis_month AS \"This Month\"\nFROM full_data\nWHERE issue_status = 'Open'"
    }
   ]
  },
  {
   "title": "In-progress",
   "type": "barchart",
   "description": "1. Compare the average time spent in each state of a requirement in the last 2 months.\n2. The requirements being calculated are the requirements delivered in the last 2 months.",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with status_change_history as(\n\tSELECT\n\t\tjc.issue_id,\n\t\tjc.created as operation_time,\n\t\tjci.changelog_id,\n\t\tjci.from,\n\t\tjci.from_string,\n\t\tjci.to,\n\t\tjci.to_string,\n\t\tji.created as issue_creation_time,\n\t\tlag(jc.created) over(PARTITION BY jc.issue_id ORDER BY jc.created ASC) as last_operation_time,\n\t\tcase \n\t\t\twhen lag(jc.created) over(PARTITION BY jc.issue_id ORDER BY jc.created ASC) is not null then\n\t\t\tTIMESTAMPDIFF(MINUTE, lag(jc.created) over(PARTITION BY jc.issue_id ORDER BY jc.created ASC), jc.created)\n\t\t\telse TIMESTAMPDIFF(MINUTE, ji.created, jc.created) end as time_in_status\n\tFROM\n\t\tjira_changelogs jc\n\t\tJOIN jira_changelog_items jci ON jc.id = jci.changelog_id\n\t\tJOIN jira_issues ji ON jc.issue_id = ji.id\n\t\tjoin jira_board_issues jbi on ji.id = jbi.issue_id\n\tWHERE\n\t\tjci.field = 'status'\n\t\tand ji.std_type = 'Requirement'\n\t\tand ji.std_status = 'Resolved'\n\t\tand $__timeFilter(ji.resolution_date)\n    and jbi.board_id = $board_id\n),\n\ntime_in_status as(\n\tSELECT \n\t\tDATE_ADD(date(issue_creation_time), INTERVAL -DAY(date(issue_creation_time))+1 DAY) as time,\n\t\tfrom_string,\n\t\tround(avg(time_in_status)/1440,1) as time_in_status\n\tFROM status_change_history\n\tGROUP BY 1,2\n),\n\nthis_month as(\n\tselect \n\t\tDATE_ADD(date(CURDATE()), INTERVAL -DAY(date(CURDATE()))+1 DAY) as this_month\n),\n\nlast_month as(\n\tSELECT \n\t\tDATE_ADD(DATE_ADD(date(CURDATE()), INTERVAL -DAY(date(CURDATE()))+1 DAY), INTERVAL -1 MONTH) as last_month\n),\n\nthe_month_before_last as(\n\tSELECT \n\t\tDATE_ADD(DATE_ADD(date(CURDATE()), INTERVAL -DAY(date(CURDATE()))+1 DAY), INTERVAL -2 MONTH) as the_month_before_last\n),\n\nthis_month_record as(\n\tSELECT\n\t\tfrom_string as issue_status,\n\t\tcase when time in (SELECT this_month from this_month) then time_in_status else null end as this_month\n\tfrom time_in_status\n\tWHERE \n\t\ttime in (SELECT this_month from this_month)\n),\n\nlast_month_record as(\n\tSELECT\n\t\tfrom_string as issue_status,\n\t\tcase when time in (SELECT last_month from last_month) then time_in_status else null end as last_month\n\tfrom time_in_status\n\tWHERE \n\t\ttime in (SELECT last_month from last_month)\n),\n\nthe_month_before_last_record as(\n\tSELECT\n\t\tfrom_string as issue_status,\n\t\tcase when time in (SELECT the_month_before_last from the_month_before_last) then time_in_status else null end as the_month_before_last\n\tfrom time_in_status\n\tWHERE \n\t\ttime in (SELECT the_month_before_last from the_month_before_last)\n),\n\nfull_data as (\n  SELECT\n  \tcase \n  \t  when lmr.issue_status in ('打开','重新打开','待开发','Open','open','todo','to-do') then 'Open'\n  \t  when lmr.issue_status in ('处理中','设计中','in-progress','InProgress') then 'In-progress'\n  \t  when lmr.issue_status in ('开发自测','代码评审','open') then 'Code Review'\n  \t  when lmr.issue_status in ('测试中','testing','open') then 'Testing'\n  \t  when lmr.issue_status in ('发布中') then 'Build and Deploy' \n  \t  else 'Other' end as issue_status,\n  \tlmr.last_month,\n\t\t-- tmr.this_month,\n\t\ttmblr.the_month_before_last\n  FROM the_month_before_last_record tmblr\n  right join last_month_record lmr on lmr.issue_status = tmblr.issue_status \n)\n\nSELECT \n  '' as '',\n  the_month_before_last AS 'The Month Before Last',\n  last_month AS \"Last Month\"\n-- \tthis_month AS \"This Month\"\nFROM full_data\nWHERE issue_status = 'In-progress'"
    }
   ]
  },
  {
   "title": "Code Review",
   "type": "barchart",
   "description": "1. Compare the average time spent in each state of a requirement in the last 2 months.\n2. The requirements being calculated are the requirements delivered in the last 2 months.",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with status_change_history as(\n\tSELECT\n\t\tjc.issue_id,\n\t\tjc.created as operation_time,\n\t\tjci.changelog_id,\n\t\tjci.from,\n\t\tjci.from_string,\n\t\tjci.to,\n\t\tjci.to_string,\n\t\tji.created as issue_creation_time,\n\t\tlag(jc.created) over(PARTITION BY jc.issue_id ORDER BY jc.created ASC) as last_operation_time,\n\t\tcase \n\t\t\twhen lag(jc.created) over(PARTITION BY jc.issue_id ORDER BY jc.created ASC) is not null then\n\t\t\tTIMESTAMPDIFF(MINUTE, lag(jc.created) over(PARTITION BY jc.issue_id ORDER BY jc.created ASC), jc.created)\n\t\t\telse TIMESTAMPDIFF(MINUTE, ji.created, jc.created) end as time_in_status\n\tFROM\n\t\tjira_changelogs jc\n\t\tJOIN jira_changelog_items jci ON jc.id = jci.changelog_id\n\t\tJOIN jira_issues ji ON jc.issue_id = ji.id\n\t\tjoin jira_board_issues jbi on ji.id = jbi.issue_id\n\tWHERE\n\t\tjci.field = 'status'\n\t\tand ji.std_type = 'Requirement'\n\t\tand ji.std_status = 'Resolved'\n\t\tand $__timeFilter(ji.resolution_date)\n    and jbi.board_id = $board_id\n),\n\ntime_in_status as(\n\tSELECT \n\t\tDATE_ADD(date(issue_creation_time), INTERVAL -DAY(date(issue_creation_time))+1 DAY) as time,\n\t\tfrom_string,\n\t\tround(avg(time_in_status)/1440,1) as time_in_status\n\tFROM status_change_history\n\tGROUP BY 1,2\n),\n\nthis_month as(\n\tselect \n\t\tDATE_ADD(date(CURDATE()), INTERVAL -DAY(date(CURDATE()))+1 DAY) as this_month\n),\n\nlast_month as(\n\tSELECT \n\t\tDATE_ADD(DATE_ADD(date(CURDATE()), INTERVAL -DAY(date(CURDATE()))+1 DAY), INTERVAL -1 MONTH) as last_month\n),\n\nthe_month_before_last as(\n\tSELECT \n\t\tDATE_ADD(DATE_ADD(date(CURDATE()), INTERVAL -DAY(date(CURDATE()))+1 DAY), INTERVAL -2 MONTH) as the_month_before_last\n),\n\nthis_month_record as(\n\tSELECT\n\t\tfrom_string as issue_status,\n\t\tcase when time in (SELECT this_month from this_month) then time_in_status else null end as this_month\n\tfrom time_in_status\n\tWHERE \n\t\ttime in (SELECT this_month from this_month)\n),\n\nlast_month_record as(\n\tSELECT\n\t\tfrom_string as issue_status,\n\t\tcase when time in (SELECT last_month from last_month) then time_in_status else null end as last_month\n\tfrom time_in_status\n\tWHERE \n\t\ttime in (SELECT last_month from last_month)\n),\n\nthe_month_before_last_record as(\n\tSELECT\n\t\tfrom_string as issue_status,\n\t\tcase when time in (SELECT the_month_before_last from the_month_before_last) then time_in_status else null end as the_month_before_last\n\tfrom time_in_status\n\tWHERE \n\t\ttime in (SELECT the_month_before_last from the_month_before_last)\n),\n\nfull_data as (\n  SELECT\n  \tcase \n  \t  when lmr.issue_status in ('打开','重新打开','待开发','Open','open','todo','to-do') then 'Open'\n  \t  when lmr.issue_status in ('处理中','设计中','in-progress','InProgress') then 'In-progress'\n  \t  when lmr.issue_status in ('开发自测','代码评审','open') then 'Code Review'\n  \t  when lmr.issue_status in ('测试中','testing','open') then 'Testing'\n  \t  when lmr.issue_status in ('发布中') then 'Build and Deploy' \n  \t  else 'Other' end as issue_status,\n  \tlmr.last_month,\n\t\t-- tmr.this_month,\n\t\ttmblr.the_month_before_last\n  FROM the_month_before_last_record tmblr\n  right join last_month_record lmr on lmr.issue_status = tmblr.issue_status \n)\n\nSELECT \n  '' as '',\n  the_month_before_last AS 'The Month Before Last',\n  last_month AS \"Last Month\"\n-- \tthis_month AS \"This Month\"\nFROM full_data\nWHERE issue_status = 'Code Review'"
    }
   ]
  },
  {
   "title": "Testing",
   "type": "barchart",
   "description": "1. Compare the average time spent in each state of a requirement in the last 2 months.\n2. The requirements being calculated are the requirements delivered in the last 2 months.",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with status_change_history as(\n\tSELECT\n\t\tjc.issue_id,\n\t\tjc.created as operation_time,\n\t\tjci.changelog_id,\n\t\tjci.from,\n\t\tjci.from_string,\n\t\tjci.to,\n\t\tjci.to_string,\n\t\tji.created as issue_creation_time,\n\t\tlag(jc.created) over(PARTITION BY jc.issue_id ORDER BY jc.created ASC) as last_operation_time,\n\t\tcase \n\t\t\twhen lag(jc.created) over(PARTITION BY jc.issue_id ORDER BY jc.created ASC) is not null then\n\t\t\tTIMESTAMPDIFF(MINUTE, lag(jc.created) over(PARTITION BY jc.issue_id ORDER BY jc.created ASC), jc.created)\n\t\t\telse TIMESTAMPDIFF(MINUTE, ji.created, jc.created) end as time_in_status\n\tFROM\n\t\tjira_changelogs jc\n\t\tJOIN jira_changelog_items jci ON jc.id = jci.changelog_id\n\t\tJOIN jira_issues ji ON jc.issue_id = ji.id\n\t\tjoin jira_board_issues jbi on ji.id = jbi.issue_id\n\tWHERE\n\t\tjci.field = 'status'\n\t\tand ji.std_type = 'Requirement'\n\t\tand ji.std_status = 'Resolved'\n\t\tand $__timeFilter(ji.resolution_date)\n    and jbi.board_id = $board_id\n),\n\ntime_in_status as(\n\tSELECT \n\t\tDATE_ADD(date(issue_creation_time), INTERVAL -DAY(date(issue_creation_time))+1 DAY) as time,\n\t\tfrom_string,\n\t\tround(avg(time_in_status)/1440,1) as time_in_status\n\tFROM status_change_history\n\tGROUP BY 1,2\n),\n\nthis_month as(\n\tselect \n\t\tDATE_ADD(date(CURDATE()), INTERVAL -DAY(date(CURDATE()))+1 DAY) as this_month\n),\n\nlast_month as(\n\tSELECT \n\t\tDATE_ADD(DATE_ADD(date(CURDATE()), INTERVAL -DAY(date(CURDATE()))+1 DAY), INTERVAL -1 MONTH) as last_month\n),\n\nthe_month_before_last as(\n\tSELECT \n\t\tDATE_ADD(DATE_ADD(date(CURDATE()), INTERVAL -DAY(date(CURDATE()))+1 DAY), INTERVAL -2 MONTH) as the_month_before_last\n),\n\nthis_month_record as(\n\tSELECT\n\t\tfrom_string as issue_status,\n\t\tcase when time in (SELECT this_month from this_month) then time_in_status else null end as this_month\n\tfrom time_in_status\n\tWHERE \n\t\ttime in (SELECT this_month from this_month)\n),\n\nlast_month_record as(\n\tSELECT\n\t\tfrom_string as issue_status,\n\t\tcase when time in (SELECT last_month from last_month) then time_in_status else null end as last_month\n\tfrom time_in_status\n\tWHERE \n\t\ttime in (SELECT last_month from last_month)\n),\n\nthe_month_before_last_record as(\n\tSELECT\n\t\tfrom_string as issue_status,\n\t\tcase when time in (SELECT the_month_before_last from the_month_before_last) then time_in_status else null end as the_month_before_last\n\tfrom time_in_status\n\tWHERE \n\t\ttime in (SELECT the_month_before_last from the_month_before_last)\n),\n\nfull_data as (\n  SELECT\n  \tcase \n  \t  when lmr.issue_status in ('打开','重新打开','待开发','Open','open','todo','to-do') then 'Open'\n  \t  when lmr.issue_status in ('处理中','设计中','in-progress','InProgress') then 'In-progress'\n  \t  when lmr.issue_status in ('开发自测','代码评审','open') then 'Code Review'\n  \t  when lmr.issue_status in ('测试中','testing','open') then 'Testing'\n  \t  when lmr.issue_status in ('发布中') then 'Build and Deploy' \n  \t  else 'Other' end as issue_status,\n  \tlmr.last_month,\n\t\t-- tmr.this_month,\n\t\ttmblr.the_month_before_last\n  FROM the_month_before_last_record tmblr\n  right join last_month_record lmr on lmr.issue_status = tmblr.issue_status \n)\n\nSELECT \n  '' as '',\n  the_month_before_last AS 'The Month Before Last',\n  last_month AS \"Last Month\"\n-- \tthis_month AS \"This Month\"\nFROM full_data\nWHERE issue_status = 'Testing'"
    }
   ]
  },
  {
   "title": "Build and Deploy",
   "type": "barchart",
   "description": "1. Compare the average time spent in each state of a requirement in the last 2 months.\n2. The requirements being calculated are the requirements delivered in the last 2 months.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with status_change_history as(\n\tSELECT\n\t\tjc.issue_id,\n\t\tjc.created as operation_time,\n\t\tjci.changelog_id,\n\t\tjci.from,\n\t\tjci.from_string,\n\t\tjci.to,\n\t\tjci.to_string,\n\t\tji.created as issue_creation_time,\n\t\tlag(jc.created) over(PARTITION BY jc.issue_id ORDER BY jc.created ASC) as last_operation_time,\n\t\tcase \n\t\t\twhen lag(jc.created) over(PARTITION BY jc.issue_id ORDER BY jc.created ASC) is not null then\n\t\t\tTIMESTAMPDIFF(MINUTE, lag(jc.created) over(PARTITION BY jc.issue_id ORDER BY jc.created ASC), jc.created)\n\t\t\telse TIMESTAMPDIFF(MINUTE, ji.created, jc.created) end as time_in_status\n\tFROM\n\t\tjira_changelogs jc\n\t\tJOIN jira_changelog_items jci ON jc.id = jci.changelog_id\n\t\tJOIN jira_issues ji ON jc.issue_id = ji.id\n\t\tjoin jira_board_issues jbi on ji.id = jbi.issue_id\n\tWHERE\n\t\tjci.field = 'status'\n\t\tand ji.std_type = 'Requirement'\n\t\tand ji.std_status = 'Resolved'\n\t\tand $__timeFilter(ji.resolution_date)\n    and jbi.board_id = $board_id\n),\n\ntime_in_status as(\n\tSELECT \n\t\tDATE_ADD(date(issue_creation_time), INTERVAL -DAY(date(issue_creation_time))+1 DAY) as time,\n\t\tfrom_string,\n\t\tround(avg(time_in_status)/1440,1) as time_in_status\n\tFROM status_change_history\n\tGROUP BY 1,2\n),\n\nthis_month as(\n\tselect \n\t\tDATE_ADD(date(CURDATE()), INTERVAL -DAY(date(CURDATE()))+1 DAY) as this_month\n),\n\nlast_month as(\n\tSELECT \n\t\tDATE_ADD(DATE_ADD(date(CURDATE()), INTERVAL -DAY(date(CURDATE()))+1 DAY), INTERVAL -1 MONTH) as last_month\n),\n\nthe_month_before_last as(\n\tSELECT \n\t\tDATE_ADD(DATE_ADD(date(CURDATE()), INTERVAL -DAY(date(CURDATE()))+1 DAY), INTERVAL -2 MONTH) as the_month_before_last\n),\n\nthis_month_record as(\n\tSELECT\n\t\tfrom_string as issue_status,\n\t\tcase when time in (SELECT this_month from this_month) then time_in_status else null end as this_month\n\tfrom time_in_status\n\tWHERE \n\t\ttime in (SELECT this_month from this_month)\n),\n\nlast_month_record as(\n\tSELECT\n\t\tfrom_string as issue_status,\n\t\tcase when time in (SELECT last_month from last_month) then time_in_status else null end as last_month\n\tfrom time_in_status\n\tWHERE \n\t\ttime in (SELECT last_month from last_month)\n),\n\nthe_month_before_last_record as(\n\tSELECT\n\t\tfrom_string as issue_status,\n\t\tcase when time in (SELECT the_month_before_last from the_month_before_last) then time_in_status else null end as the_month_before_last\n\tfrom time_in_status\n\tWHERE \n\t\ttime in (SELECT the_month_before_last from the_month_before_last)\n),\n\nfull_data as (\n  SELECT\n  \tcase \n  \t  when lmr.issue_status in ('打开','重新打开','待开发','Open','open','todo','to-do') then 'Open'\n  \t  when lmr.issue_status in ('处理中','设计中','in-progress','InProgress') then 'In-progress'\n  \t  when lmr.issue_status in ('开发自测','代码评审','open') then 'Code Review'\n  \t  when lmr.issue_status in ('测试中','testing','open') then 'Testing'\n  \t  when lmr.issue_status in ('发布中') then 'Build and Deploy' \n  \t  else 'Other' end as issue_status,\n  \tlmr.last_month,\n\t\t-- tmr.this_month,\n\t\ttmblr.the_month_before_last\n  FROM the_month_before_last_record tmblr\n  right join last_month_record lmr on lmr.issue_status = tmblr.issue_status \n)\n\nSELECT \n  '' as '',\n  the_month_before_last AS 'The Month Before Last',\n  last_month AS \"Last Month\"\n-- \tthis_month AS \"This Month\"\nFROM full_data\nWHERE issue_status = 'Build and Deploy'"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with status_change_history as(\n\tSELECT\n\t\tjc.issue_id,\n\t\tjc.created as operation_time,\n\t\tjci.changelog_id,\n\t\tjci.from,\n\t\tjci.from_string,\n\t\tjci.to,\n\t\tjci.to_string,\n\t\tji.created as issue_creation_time,\n\t\tlag(jc.created) over(PARTITION BY jc.issue_id ORDER BY jc.created ASC) as last_operation_time,\n\t\tcase \n\t\t\twhen lag(jc.created) over(PARTITION BY jc.issue_id ORDER BY jc.created ASC) is not null then\n\t\t\tTIMESTAMPDIFF(MINUTE, lag(jc.created) over(PARTITION BY jc.issue_id ORDER BY jc.created ASC), jc.created)\n\t\t\telse TIMESTAMPDIFF(MINUTE, ji.created, jc.created) end as time_in_status\n\tFROM\n\t\tjira_changelogs jc\n\t\tJOIN jira_changelog_items jci ON jc.id = jci.changelog_id\n\t\tJOIN jira_issues ji ON jc.issue_id = ji.id\n\t\tjoin jira_board_issues jbi on ji.id = jbi.issue_id\n\tWHERE\n\t\tjci.field = 'status'\n\t\tand ji.std_type = 'Requirement'\n\t\tand ji.std_status = 'Resolved'\n\t\tand $__timeFilter(ji.resolution_date)\n    and jbi.board_id = $board_id\n),\n\ntime_in_status as(\n\tSELECT \n\t\tDATE_ADD(date(issue_creation_time), INTERVAL -DAY(date(issue_creation_time))+1 DAY) as time,\n\t\tfrom_string,\n\t\tround(avg(time_in_status)/1440,1) as time_in_status\n\tFROM status_change_history\n\tGROUP BY 1,2\n),\n\nthis_month as(\n\tselect \n\t\tDATE_ADD(date(CURDATE()), INTERVAL -DAY(date(CURDATE()))+1 DAY) as this_month\n),\n\nlast_month as(\n\tSELECT \n\t\tDATE_ADD(DATE_ADD(date(CURDATE()), INTERVAL -DAY(date(CURDATE()))+1 DAY), INTERVAL -1 MONTH) as last_month\n),\n\nthe_month_before_last as(\n\tSELECT \n\t\tDATE_ADD(DATE_ADD(date(CURDATE()), INTERVAL -DAY(date(CURDATE()))+1 DAY), INTERVAL -2 MONTH) as the_month_before_last\n),\n\nthis_month_record as(\n\tSELECT\n\t\tfrom_string as issue_status,\n\t\tcase when time in (SELECT this_month from this_month) then time_in_status else null end as this_month\n\tfrom time_in_status\n\tWHERE \n\t\ttime in (SELECT this_month from this_month)\n),\n\nlast_month_record as(\n\tSELECT\n\t\tfrom_string as issue_status,\n\t\tcase when time in (SELECT last_month from last_month) then time_in_status else null end as last_month\n\tfrom time_in_status\n\tWHERE \n\t\ttime in (SELECT last_month from last_month)\n),\n\nthe_month_before_last_record as(\n\tSELECT\n\t\tfrom_string as issue_status,\n\t\tcase when time in (SELECT the_month_before_last from the_month_before_last) then time_in_status else null end as the_month_before_last\n\tfrom time_in_status\n\tWHERE \n\t\ttime in (SELECT the_month_before_last from the_month_before_last)\n),\n\nfull_data as (\n  SELECT\n  \tcase \n  \t  when tmblr.issue_status like 'Open%' or tmblr.issue_status in ('打开','重新打开','待开发','Open','open','todo','to-do') then 'Open'\n  \t  when tmblr.issue_status in ('处理中','设计中','in-progress','InProgress') then 'In-progress'\n  \t  when tmblr.issue_status in ('开发自测','代码评审') then 'Code Review'\n  \t  when tmblr.issue_status in ('测试中','testing') then 'Testing'\n  \t  when tmblr.issue_status in ('发布中') then 'Build and Deploy' \n  \t  else 'Other' end as issue_status,\n  \tlmr.last_month,\n\t\ttmr.this_month,\n\t\ttmblr.the_month_before_last\n  FROM the_month_before_last_record tmblr\n  left join last_month_record lmr on tmblr.issue_status = lmr.issue_status\n  left join this_month_record tmr  on tmblr.issue_status = tmr.issue_status\n)\n\nSELECT \n  issue_status,\n  COALESCE(the_month_before_last, '-') AS \"The Month Before Last\",\n  COALESCE(last_month, '-') AS \"Last Month\"\n-- \tthis_month AS \"This Month\"\nFROM full_data"
    }
   ]
  }
 ]
}