{
 "title": "Azure DevOps",
 "tags": [
  "Data Source Dashboard",
  "Stable Data Sources"
 ],
 "time": { "from": "2023-10-31T03:37:59.571Z", "to": "2024-10-29T05:37:59.571Z" },
 "templating": {
  "list": [
   {
    "name": "repo_id",
    "label": "Repo",
    "query": "select concat(name, '--', id) as text from repos where id like 'azure%'"
   },
   {
    "name": "interval",
    "label": "Time Interval",
    "query": "Month : DAYOFMONTH, Week : WEEKDAY"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Introduction",
   "type": "text",
   "gridPos": { "h": 3, "w": 13, "x": 0, "y": 0 },
   "options": {
    "content": "- Use Cases: This dashboard shows the basic Git and Code Review metrics from Azure DevOps.\n- Data Source Required: Azure DevOps"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "1. User Requirements (Issues)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "1.1 Number of New Issues",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n\tcount(distinct i.id)\nfrom \n\tissues i\nwhere\n  $__timeFilter(i.created_date)\n"
    }
   ]
  },
  {
   "title": "1.2 Number of New Issues",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 4 },
   "targets": [
    {
     "rawSql": "with _issues as(\n  SELECT\n    DATE_ADD(date(i.created_date), INTERVAL -$interval(date(i.created_date))+1 DAY) as time,\n    count(distinct i.id) as issue_count\n  FROM issues i\n  WHERE\n    $__timeFilter(i.created_date)\n    -- Enable the following condition to remove the month with incomplete data\n    -- and i.created_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n  group by 1\n)\n\nSELECT \n  case when '$interval' = 'DAYOFMONTH' then date_format(time,'%M %Y') else concat('W', date_format(time,'%u %Y')) end as _time,\n  issue_count as \"Issue Count\"\nFROM _issues\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "2. How issues are handled?",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "2.1 Number of Closed Issues",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n\tcount(distinct i.id)\nfrom \n\tissues i\nwhere\n  $__timeFilter(i.created_date)\n  and (i.status = \"Resolved\" or i.status = \"Closed\")\n\n\n"
    }
   ]
  },
  {
   "title": "2.2 Number of open and closed issues by Issue creation time",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 11 },
   "targets": [
    {
     "rawSql": "with _issues as(\n  SELECT\n    DATE_ADD(date(i.created_date), INTERVAL -$interval(date(i.created_date))+1 DAY) as time,\n    count(distinct case when status != 'DONE' then i.id else null end) as open_issue_count,\n    count(distinct case when status = 'DONE' then i.id else null end) as closed_issue_count\n  FROM issues i\n  WHERE\n    $__timeFilter(i.created_date)\n    -- Enable the following condition to remove the month with incomplete data\n    -- and i.created_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n  group by 1\n)\n\nSELECT \n  case when '$interval' = 'DAYOFMONTH' then date_format(time,'%M %Y') else concat('W', date_format(time,'%u %Y')) end as _time,\n  open_issue_count,\n  closed_issue_count\nFROM _issues\nORDER BY time"
    }
   ]
  },
  {
   "title": "2.3 Mean Issue Lead Time by issue resolution time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n\tAVG(i.lead_time_minutes/1440) issue_lead_time_in_days\nfrom \n\tissues i\nwhere\n  $__timeFilter(i.resolution_date)\n  and i.resolution_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n  and (i.status = \"Resolved\" or i.status = \"Closed\")"
    }
   ]
  },
  {
   "title": "2.4 Mean issue lead time by issue resolution time",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "rawSql": "with _issues as(\n  SELECT\n    DATE_ADD(date(i.resolution_date), INTERVAL -$interval(date(i.resolution_date))+1 DAY) as time,\n    AVG(i.lead_time_minutes/1440) as issue_lead_time\n  FROM issues i\n  WHERE\n    (i.status = \"Resolved\" or i.status = \"Closed\")\n    and $__timeFilter(i.resolution_date)\n    and i.resolution_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n  group by 1\n)\n\nSELECT \n  case when '$interval' = 'DAYOFMONTH' then date_format(time,'%M %Y') else concat('W', date_format(time,'%u %Y')) end as _time,\n  issue_lead_time as \"Mean Issue Lead Time in Days\"\nFROM _issues\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "2.5 Top 20 Queue Time [All Open Issues]",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "rawSql": "-- Get the queue time of all outstanding bugs\nwith _outstanding_issues as(\n  select \n    DISTINCT\n    i.issue_key,\n    i.title,\n    i.created_date,\n    (TIMESTAMPDIFF(MINUTE, i.created_date,NOW()))/1440 as queue_time_in_days,\n    url\n  from \n    issues i\n  where\n    $__timeFilter(i.created_date)\n    and (i.status != \"Resolved\" or i.status != \"Closed\")\n)\n\nselect title, url, queue_time_in_days from _outstanding_issues\norder by 3 desc\nlimit 20"
    }
   ]
  },
  {
   "title": "2.6 List of Outstanding Issues Order By Queue Time [All Open Issues]",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "-- Get the queue time of all outstanding bugs\nselect \n  i.title,\n  i.created_date,\n  (TIMESTAMPDIFF(MINUTE, i.created_date,NOW()))/1440 as queue_time_in_days,\n  url\nfrom \n  issues i\nwhere\n  $__timeFilter(i.created_date)\n  and (i.status != \"Resolved\" or i.status != \"Closed\")\norder by queue_time_in_days desc"
    }
   ]
  },
  {
   "title": "3. Contribution (PRs)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "3.1 Number of New Pull Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n\tcount(distinct pr.id) as pull_request_count\nfrom \n\tpull_requests pr\nwhere\n  $__timeFilter(created_date)\n\tand base_repo_id in (${repo_id})\n\t\n\n"
    }
   ]
  },
  {
   "title": "3.2 Number of New Pull Requests",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 36 },
   "targets": [
    {
     "rawSql": "with _prs as(\n  SELECT\n    DATE_ADD(date(created_date), INTERVAL -$interval(date(created_date))+1 DAY) as time,\n    count(distinct id) as pr_count\n  FROM pull_requests\n  WHERE\n    base_repo_id in (${repo_id})\n    and $__timeFilter(created_date)\n    -- Enable the following condition to remove the month with incomplete data\n    -- and created_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n  group by 1\n)\n\nSELECT \n  case when '$interval' = 'DAYOFMONTH' then date_format(time,'%M %Y') else concat('W', date_format(time,'%u %Y')) end as _time,\n  pr_count as \"Pull Request Count\"\nFROM _prs\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "3.3 Top Contributors By Merged PRs",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "-- The PR/MR statuses are standardized to DevLake's statuses 'OPEN', 'MERGED' and 'CLOSED'. You can check out the original status from the field `original_status`\nselect\n  author_name,\n\tcount(distinct pr.id) as merged_pull_request_count\nfrom \n\tpull_requests pr\nwhere\n  $__timeFilter(created_date)\n\tand base_repo_id in (${repo_id})\n\tand pr.status = 'MERGED'\ngroup by 1\norder by 2 desc\nlimit 20\n"
    }
   ]
  },
  {
   "title": "4. How PRs are handled?",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "title": "4.1 Ratio of unmerged Pull Requests of All Closed or Merged PRs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "-- The PR/MR statuses are standardized to DevLake's statuses 'OPEN', 'MERGED' and 'CLOSED'. You can check out the original status from the field `original_status`\nselect\n  count(distinct case when status='CLOSED' then id else null end)/count(distinct case when status in ('MERGED','CLOSED') then id else null end) as ratio\nfrom \n\tpull_requests pr\nwhere\n  $__timeFilter(created_date)\n\tand base_repo_id in (${repo_id})"
    }
   ]
  },
  {
   "title": "4.2 Pull Request Status Distribution",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 49 },
   "targets": [
    {
     "rawSql": "-- The PR/MR statuses are standardized to DevLake's statuses 'OPEN', 'MERGED' and 'CLOSED'. You can check out the original status from the field `original_status`\nwith _prs as (\n  SELECT\n    DATE_ADD(date(created_date), INTERVAL -$interval(date(created_date))+1 DAY) as time,\n    count(distinct case when status = 'OPEN' then id else null end) as open,\n    count(distinct case when status = 'CLOSED' then id else null end) as closed,\n    count(distinct case when status = 'MERGED' then id else null end) as merged\n  FROM pull_requests\n  WHERE\n    $__timeFilter(created_date)\n    -- Enable the following condition to remove the month with incomplete data\n    -- and created_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n    and base_repo_id in (${repo_id})\n  group by 1\n)\n\nSELECT \n  case when '$interval' = 'DAYOFMONTH' then date_format(time,'%M %Y') else concat('W', date_format(time,'%u %Y')) end as _time,\n  open as \"PR: Open\",\n  closed as \"PR: Closed without merging\",\n  merged as \"PR: Closed and merged\"\nFROM _prs\nORDER BY time"
    }
   ]
  },
  {
   "title": "4.3 Number of Pull Requests Closed without Merging [Selected Time Range]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- The PR/MR statuses are standardized to DevLake's statuses 'OPEN', 'MERGED' and 'CLOSED'. You can check out the original status from the field `original_status`\nselect\n\tcount(distinct pr.id) as merged_pull_request_count\nfrom \n\tpull_requests pr\nwhere\n  $__timeFilter(created_date)\n\tand base_repo_id in (${repo_id})\n\tand pr.status = 'CLOSED'"
    }
   ]
  },
  {
   "title": "4.4 Ratio of unmerged PRs of All Closed or Merged PRs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "-- The PR/MR statuses are standardized to DevLake's statuses 'OPEN', 'MERGED' and 'CLOSED'. You can check out the original status from the field `original_status`\nSELECT\n  DATE_ADD(date(created_date), INTERVAL -$interval(date(created_date))+1 DAY) as time,\n  count(distinct case when status = 'CLOSED' then id else null end)/count(distinct case when status in ('MERGED', 'CLOSED') then id else null end) as ratio\nFROM pull_requests\nWHERE\n  $__timeFilter(created_date)\n  and base_repo_id in (${repo_id})\ngroup by 1\n"
    }
   ]
  },
  {
   "title": "4.5 Mean Time to Merge of Pull Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n\tavg(TIMESTAMPDIFF(Minute,created_date,merged_date)/1440)\nfrom \n\tpull_requests\nwhere \n  $__timeFilter(created_date)\n\tand base_repo_id in (${repo_id})\n\tand merged_date is not null\n\n\n"
    }
   ]
  },
  {
   "title": "4.6 Mean Time to Merge of Pull Requests",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "rawSql": "with _prs as(\n  SELECT\n    DATE_ADD(date(created_date), INTERVAL -DAY(date(created_date))+1 DAY) as time,\n    avg(TIMESTAMPDIFF(Minute,created_date,merged_date)/1440) as time_to_merge\n  FROM pull_requests\n  WHERE\n    $__timeFilter(created_date)\n    and base_repo_id in (${repo_id})\n    -- Enable the following condition to remove the month with incomplete data\n    -- and created_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n  group by 1\n)\n\nSELECT \n  case when '$interval' = 'DAYOFMONTH' then date_format(time,'%M %Y') else concat('W', date_format(time,'%u %Y')) end as _time,\n  time_to_merge as \"Time to Merge\"\nFROM _prs\nORDER BY time\n"
    }
   ]
  },
  { "title": "5. CI/CD Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "5.1 Number of Successful Pipeline runs",
   "type": "stat",
   "description": "Number of Pipeline runs executed in the selected time range",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct id)\nFROM \n  cicd_pipelines\nWHERE\n  $__timeFilter(finished_date)\n  and result = 'SUCCESS'\n  and cicd_scope_id in (${repo_id})\n  -- the following condition will remove the month with incomplete data\n  and finished_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)"
    }
   ]
  },
  {
   "title": "5.2 Mean Pipeline runs Success Rate %",
   "type": "stat",
   "description": "Number of successful Pipeline runs / Number of total Pipeline runs",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  1.0 * count(case when result = 'SUCCESS' then id else null end)/count(distinct id)\nFROM cicd_pipelines\nWHERE\n  $__timeFilter(finished_date)\n  and cicd_scope_id in (${repo_id})\n  -- the following condition will remove the month with incomplete data\n  and finished_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)"
    }
   ]
  },
  {
   "title": "5.3 Number of successful and failed pipeline runs",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "rawSql": "with _builds as (\n  SELECT\n    DATE_ADD(date(finished_date), INTERVAL -$interval(date(finished_date))+1 DAY) as time,\n    count(distinct case when result = 'SUCCESS' then id else null end) as successful_count,\n    count(distinct case when result != 'SUCCESS' then id else null end) as failed_count\n  FROM cicd_pipelines\n  WHERE\n    $__timeFilter(finished_date)\n    and cicd_scope_id in (${repo_id})\n    -- Enable the following condition to remove the month with incomplete data\n    -- and finished_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n  GROUP BY 1\n)\n\nSELECT \n  case when '$interval' = 'DAYOFMONTH' then date_format(time,'%M %Y') else concat('W', date_format(time,'%u %Y')) end as _time,\n  successful_count,\n  failed_count\nFROM _builds\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "5.4 Total Pipeline runs Result Distribution",
   "type": "piechart",
   "description": "Number of successful Pipeline runs / Number of total Pipeline runs",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  IF(result = '', 'Unknown', result) as result,\n  count(distinct id) as build_count\nFROM cicd_pipelines\nWHERE\n  $__timeFilter(finished_date)\n  and cicd_scope_id in (${repo_id})\n  -- the following condition will remove the month with incomplete data\n  and finished_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\nGROUP BY 1\nORDER BY 2 desc"
    }
   ]
  },
  {
   "title": "5.5 Pipeline run success rate %",
   "type": "barchart",
   "description": "1. Mean Pipeline Runs success rate over time.\n2. The Pipeline runs being calculated are filtered by \"workflow runs starting time\" (time filter at the upper-right corner) and \"Jira board\" (\"Choose Board\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "WITH _build_success_rate as(\r\n  SELECT\r\n    DATE_ADD(date(finished_date), INTERVAL -$interval(date(finished_date))+1 DAY) as time,\r\n    result,\r\n    id\r\n  FROM\r\n    cicd_pipelines\r\n  WHERE\r\n    $__timeFilter(finished_date)\r\n    -- and id like \"%azure%\"\r\n    and cicd_scope_id in (${repo_id})\r\n    -- Enable the following condition to remove the month with incomplete data\r\n    -- and finished_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\r\n  GROUP BY \r\n    time, result, id\r\n)\r\n\r\nSELECT \r\n  case when '$interval' = 'DAYOFMONTH' then date_format(time,'%m/%Y') else concat('W', date_format(time,'%u %Y')) end as _time,\r\n  1.0 * sum(case when result = 'SUCCESS' then 1 else 0 end)/ count(*) as \"Pipeline Runs Success Rate\"\r\nFROM _build_success_rate\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "5.6 Mean Pipeline runs Duration in Minutes",
   "type": "stat",
   "description": "1. Mean Pipeline runs success rate over time.\n2. The Pipeline runs being calculated are filtered by \"Pipeline runs starting time\" (time filter at the upper-right corner) and \"Jira board\" (\"Choose Board\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg(duration_sec/60) as duration_in_minutes\nFROM cicd_pipelines\nWHERE\n  $__timeFilter(finished_date)\n  and cicd_scope_id in (${repo_id})\n  -- the following condition will remove the month with incomplete data\n  and finished_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)"
    }
   ]
  },
  {
   "title": "5.7 Mean pipeline run duration",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "WITH _builds as(\n  SELECT\n    DATE_ADD(date(finished_date), INTERVAL -$interval(date(finished_date))+1 DAY) as time,\n    avg(duration_sec) as mean_duration_sec\n  FROM \n    cicd_pipelines\n  WHERE\n    $__timeFilter(finished_date)\n    -- and id like \"%azure%\"\n    and cicd_scope_id in (${repo_id})\n    -- Enable the following condition to remove the month with incomplete data\n    -- and finished_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n  GROUP BY 1\n)\n\nSELECT \n  case when '$interval' = 'DAYOFMONTH' then date_format(time,'%M %Y') else concat('W', date_format(time,'%u %Y')) end as _time,\n  mean_duration_sec\nFROM _builds\nORDER BY time\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 86 },
   "options": {
    "content": "<br/>\n\nThis dashboard is created based on this [data schema](https://devlake.apache.org/docs/DataModels/DevLakeDomainLayerSchema). Want to add more metrics? Please follow the [guide](https://devlake.apache.org/docs/Configuration/Dashboards/GrafanaUserGuide)."
   },
   "targets": [
    {}
   ]
  }
 ]
}