{
 "title": "Delivery Cost",
 "tags": [
  "metrics",
  "cost"
 ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "repo_id",
    "label": "Choose Repo",
    "query": "select distinct concat(name, ': ', gitlab_id) from gitlab_projects"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Developer Count",
   "type": "stat",
   "description": "1. Number of people who have created or reviewed a Pull/Merge Request.\n2. The PR/MR being calculated are filtered by \"PR/MR creation time\" (time filter at the upper-right corner).",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "with all_developers as(\n  select \n    gitlab_reviewers.name as user_name\n  from gitlab_merge_requests\n  join gitlab_reviewers on gitlab_reviewers.merge_request_id = gitlab_merge_requests.gitlab_id\n\n  WHERE\n    $__timeFilter(gitlab_merge_requests.gitlab_created_at)\n    and gitlab_merge_requests.project_id = $repo_id\n  union\n  select \n    distinct author_username as user_name \n  from gitlab_merge_requests\n  WHERE\n    $__timeFilter(gitlab_merge_requests.gitlab_created_at)\n    and gitlab_merge_requests.project_id = $repo_id\n  union\n  select \n    distinct author_name as user_name \n  from gitlab_commits\n  WHERE\n    $__timeFilter(authored_date)\n    and gitlab_commits.project_id = $repo_id\n)\n\n\nSELECT\n  now() AS \"time\",\n  count(distinct user_name) as developer_count\nFROM all_developers"
    }
   ]
  },
  {
   "title": "Commit Author Count",
   "type": "stat",
   "description": "1. Total number of Commit Authors.\n2. The commits being calculated are filtered by \"authored_date\" (time filter at the upper-right corner).",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() AS time,\n  count(distinct author_name) as value\nFROM gitlab_commits\nWHERE\n  $__timeFilter(authored_date)\n  and project_id = $repo_id\ngroup by 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Pull Request Reviewer Count",
   "type": "stat",
   "description": "1. Number of Pull/Merge Request Reviewers.\n2. The PR/MR being calculated are filtered by \"PR/MR creation time\" (time filter at the upper-right corner).",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select \n  now() as time,\n  count(name)\nfrom\n  gitlab_reviewers"
    }
   ]
  },
  {
   "title": "Pull Request Reviewer Rate (%)",
   "type": "stat",
   "description": "Pull Request Reviewer Count/Total Developer Count",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "with all_user_names as(\n  select \n    distinct gitlab_reviewers.name as user_name\n  from gitlab_reviewers\n  join gitlab_merge_requests on gitlab_reviewers.merge_request_id = gitlab_merge_requests.gitlab_id\n  WHERE\n    $__timeFilter(gitlab_merge_requests.gitlab_created_at)\n    and gitlab_reviewers.project_id = $repo_id\n  union\n  select \n    distinct author_username as user_name \n  from gitlab_merge_requests\n  WHERE\n    $__timeFilter(gitlab_created_at)\n    and project_id = $repo_id\n  union\n  select \n    distinct author_name as user_name \n  from gitlab_commits\n  WHERE\n   $__timeFilter(authored_date)\n    and project_id = $repo_id\n),\n\nreviewer as (\n  select distinct gitlab_reviewers.name from gitlab_reviewers\n  join gitlab_merge_requests on gitlab_reviewers.merge_request_id = gitlab_merge_requests.gitlab_id\nWHERE\n    $__timeFilter(gitlab_merge_requests.gitlab_created_at)\n    and gitlab_reviewers.project_id = $repo_id\n)\n\nSELECT\n  now() AS \"time\",\n  1.0*count(distinct reviewer.name)/count(distinct user_name) as value\nFROM reviewer, all_user_names"
    }
   ]
  }
 ]
}