{
 "title": "Delivery Quality",
 "tags": [
  "metrics",
  "quality"
 ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "board_id",
    "label": "Choose Board",
    "query": "select distinct format('%s: %s', name, id) from jira_boards"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "week : YYYY-WW, month : YYYY-MM"
   },
   {
    "name": "repo_id",
    "label": "Choose Repo",
    "query": "select distinct format('%s: %s', name, id) from gitlab_projects"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 15, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align:center;\">\n    <img border=\"0\" src=\"https://z3.ax1x.com/2021/08/06/fu5TUS.png\" alt=\"No.1\" width=\"120\"><br>\n    <img border=\"0\" src=\"https://z3.ax1x.com/2021/08/09/f8VkmF.png\" alt=\"Development\" width=\"120\"> \n    <p style=\"text-align:center;font-size:18px;margin:10px;text-decoration-color:rgb(255, 255, 255);color:#828487\"><b>Development<b></p>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "10.1 Number of Merge Request",
   "type": "stat",
   "description": "合并请求次数\nFiltered by **MR create time**",
   "gridPos": { "h": 7, "w": 7, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() AS \"time\",\n  count(*) as value\nFROM gitlab_merge_requests gmr\nLEFT JOIN jira_board_gitlab_projects jbgp ON (jbgp.project_id = gmr.project_id)\nWHERE\n  jbgp.board_id = $board_id\n  and jbgp.project_id = $repo_id\n  and $__timeFilter(gitlab_created_at)\ngroup by 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "11.1 Merge Request Pass Count",
   "type": "stat",
   "description": "Filtered by **MR create time**",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  count(merged_by_username) as value\nFROM\n  gitlab_merge_requests gmr\nLEFT JOIN jira_board_gitlab_projects jbgp ON (jbgp.project_id = gmr.project_id)\nWHERE\n  jbgp.board_id = $board_id\n  and jbgp.project_id = $repo_id\n  and $__timeFilter(gitlab_created_at)\n"
    }
   ]
  },
  {
   "title": "11.2 Merge Request Pass Rate (%)",
   "type": "stat",
   "description": "Filtered by **MR create time**",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  count(merged_by_username)::decimal / count(*)::decimal as value\nFROM\n  gitlab_merge_requests gmr\nLEFT JOIN jira_board_gitlab_projects jbgp ON (jbgp.project_id = gmr.project_id)\nWHERE\n  jbgp.board_id = $board_id\n  and jbgp.project_id = $repo_id\n  and $__timeFilter(gitlab_created_at)\n"
    }
   ]
  },
  {
   "title": "11.4 Merge Request Pass Rate (%)",
   "type": "timeseries",
   "description": "Filtered by **MR create time**",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "with t as (\nSELECT\n  to_char(gitlab_created_at, '$interval') as time,\n  count(merged_by_username)::decimal / count(*)::decimal * 100 as value\nFROM\n  gitlab_merge_requests gmr\nLEFT JOIN jira_board_gitlab_projects jbgp ON (jbgp.project_id = gmr.project_id)\nWHERE\n  jbgp.board_id = $board_id\n  and jbgp.project_id = $repo_id\n  and $__timeFilter(gitlab_created_at)\ngroup by to_char(gitlab_created_at, '$interval')\norder by 1\n) \n\nselect to_timestamp(time,  '$interval') as time, value \nfrom t"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 14, "w": 3, "x": 0, "y": 15 },
   "options": {
    "content": "<div style=\"text-align:center;\">\n  <img border=\"0\" src=\"https://z3.ax1x.com/2021/08/06/fu574g.png\" alt=\"No.2\" width=\"120\"><br>\n  <img border=\"0\" src=\"https://z3.ax1x.com/2021/08/09/f8VSWq.png\" alt=\"Test\" width=\"120\">\n  <p style=\"text-align:center;font-size:20px;margin:10px;text-decoration-color:rgb(255, 255, 255);color:#828487\"><b>Test<b></p>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "4.1 Total Number of Bugs found in Testing",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 3, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  count(*) as value\nFROM\n  jira_issues ji\n  join jira_board_issues jbi on ji.id = jbi.issue_id\nWHERE\n  issue_type in ('Bug')\n  and jbi.board_id in ($board_id)\n  and $__timeFilter(issue_created_at)\n"
    }
   ]
  },
  {
   "title": "4.2 Number of bugs found in Testing (Breakdown by Time)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "with _bugs as (\nSELECT\n  to_char(issue_created_at, '$interval') as time,\n  count(*)::decimal as bug_count\nFROM\n  jira_issues ji\n  LEFT JOIN jira_board_issues jbi ON jbi.issue_id = ji.id\nWHERE\n  issue_type = 'Bug'\n  and jbi.board_id in ($board_id)\n  and $__timeFilter(issue_created_at)\ngroup by to_char(issue_created_at, '$interval')\norder by 1\n) \n\nselect \n  to_timestamp(time,  '$interval') as time, \n  bug_count \nfrom _bugs"
    }
   ]
  },
  {
   "title": "6.1 - Bugs Count per 1k lines of code (Total)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 3, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with \n\tnoi as (\n\t\tselect count(*) as noi\n\t\tfrom jira_issues ji \n\t\tleft join jira_board_issues jbi on (jbi.issue_id = ji.id)\n\t\twhere \n\t\t  jbi.board_id = $board_id \n\t\t  and ji.issue_type = 'Bug'\n\t\t  and $__timeFilter(ji.issue_created_at)\n\t),\n\tloc as (\n\t\tselect sum(additions + deletions) as loc\n\t\tfrom gitlab_commits gc \n\t\tleft join jira_board_gitlab_projects jbgp on (jbgp.project_id = gc.project_id)\n\t\twhere\n\t\t  jbgp.board_id = $board_id\n\t\t  and jbgp.project_id = $repo_id\n\t\t  and gc.title not like 'Merge branch %'\n\t\t  and $__timeFilter(authored_date)\n\t)\nselect now() as time, noi::decimal / loc.loc::decimal * 1000 as value\nfrom loc, noi\n"
    }
   ]
  },
  {
   "title": "6.2 - Bug Count per 1k lines of code (Breakdown by Time)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 22 },
   "targets": [
    {
     "rawSql": "with t as (\nwith \n\tnoi as (\n\t\tselect to_char(issue_created_at, '$interval') as month, count(*) as noi\n\t\tfrom jira_issues ji \n\t\tleft join jira_board_issues jbi on (jbi.issue_id = ji.id)\n\t\twhere \n\t\t  jbi.board_id = $board_id \n\t\t  and ji.issue_type = 'Bug'\n\t\t  and $__timeFilter(ji.issue_created_at)\n\t\tgroup by to_char(issue_created_at, '$interval')\n\t),\n\tloc as (\n\t\tselect to_char(authored_date, '$interval') as month, sum(additions + deletions) as loc\n\t\tfrom gitlab_commits gc \n\t\tleft join jira_board_gitlab_projects jbgp on (jbgp.project_id = gc.project_id)\n\t\twhere \n\t\t  jbgp.board_id = $board_id \n\t\t  and jbgp.project_id = $repo_id\n\t\t  and gc.title not like 'Merge branch %'\n\t\t  and $__timeFilter(authored_date)\n\t\tgroup by to_char(authored_date, '$interval')\n\t)\n\nselect loc.month as time, noi::decimal / loc.loc::decimal * 1000 as bug_count_per_1k_loc\nfrom loc\nleft join noi on (noi.month = loc.month)\nwhere noi.noi is not null and loc.loc is not null\norder by time\n) \n\nselect \n  to_timestamp(time,  '$interval') as time, \n  bug_count_per_1k_loc \nfrom t;\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 16, "w": 3, "x": 0, "y": 29 },
   "options": {
    "content": "<div style=\"text-align:center;\">\n  <img border=\"0\" src=\"https://z3.ax1x.com/2021/08/06/fu5q3j.png\" alt=\"No.3\" width=\"120\"><br>\n  <img border=\"0\" src=\"https://z3.ax1x.com/2021/08/09/f8VZk9.png\" alt=\"Operation\"\" width=\"120\">\n  <p style=\"text-align:center;font-size:20px;margin:10px;text-decoration-color:rgb(255, 255, 255);color:#828487\"><b>Operation<b></p>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "7.1 Total Number of Incidents found after shipping",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 3, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  count(*) as value\nFROM\n  jira_issues ji\n  join jira_board_issues jbi on ji.id = jbi.issue_id\nWHERE\n  issue_type in ('Incident')\n  and jbi.board_id in ($board_id)\n  and $__timeFilter(issue_created_at)\n"
    }
   ]
  },
  {
   "title": "7.2 Number of Incidents found after shipping (Breakdown by Time)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "with _incidents as (\nSELECT\n  to_char(issue_created_at, '$interval') as time,\n  count(*)::decimal as incident_count\nFROM\n  jira_issues ji\n  LEFT JOIN jira_board_issues jbi ON jbi.issue_id = ji.id\nWHERE\n  issue_type = 'Incident'\n  and jbi.board_id in ($board_id)\n  and $__timeFilter(issue_created_at)\ngroup by to_char(issue_created_at, '$interval')\norder by 1\n) \nselect \n  to_timestamp(time,  '$interval') as time, \n  incident_count \nfrom _incidents"
    }
   ]
  },
  {
   "title": "9.1 - Incidents Count per 1k lines of code (Total)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 3, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with \n\tnoi as (\n\t\tselect count(*) as noi\n\t\tfrom jira_issues ji \n\t\tleft join jira_board_issues jbi on (jbi.issue_id = ji.id)\n\t\twhere jbi.board_id = $board_id and ji.issue_type = 'Incident'\n\t\t  and $__timeFilter(ji.issue_created_at)\n\t),\n\tloc as (\n\t\tselect sum(additions + deletions) as loc\n\t\tfrom gitlab_commits gc \n\t\tleft join jira_board_gitlab_projects jbgp on (jbgp.project_id = gc.project_id)\n\t\twhere jbgp.board_id = $board_id and gc.title not like 'Merge branch %'\n\t\t  and $__timeFilter(authored_date)\n\t)\nselect now() as time, noi::decimal / loc.loc::decimal * 1000 as value\nfrom loc, noi\n"
    }
   ]
  },
  {
   "title": "9.2 - Incident Count per 1k lines of code (Breakdown by Time)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with t as (\nwith \n\tnoi as (\n\t\tselect to_char(issue_created_at, '$interval') as month, count(*) as noi\n\t\tfrom jira_issues ji \n\t\tleft join jira_board_issues jbi on (jbi.issue_id = ji.id)\n\t\twhere jbi.board_id = $board_id and ji.issue_type = 'Incident'\n\t\t  and $__timeFilter(ji.issue_created_at)\n\t\tgroup by to_char(issue_created_at, '$interval')\n\t),\n\tloc as (\n\t\tselect to_char(authored_date, '$interval') as month, sum(additions + deletions) as loc\n\t\tfrom gitlab_commits gc \n\t\tleft join jira_board_gitlab_projects jbgp on (jbgp.project_id = gc.project_id)\n\t\twhere jbgp.board_id = $board_id and gc.title not like 'Merge branch %'\n\t\t  and $__timeFilter(authored_date)\n\t\tgroup by to_char(authored_date, '$interval')\n\t)\nselect loc.month as time, noi::decimal / loc.loc::decimal * 1000 as incident_count_per_1k_loc\nfrom loc\nleft join noi on (noi.month = loc.month)\nwhere noi.noi is not null and loc.loc is not null\norder by time\n) \n\nselect \n  to_timestamp(time,  '$interval') as time, \n  incident_count_per_1k_loc \nfrom t;\n"
    }
   ]
  }
 ]
}