{
 "title": "Github by Team",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project_id",
    "label": "Teams",
    "query": "select distinct name from projects"
   }
  ]
 },
 "panels": [
  { "title": "1. Contribution (PRs)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "3.1 Number of New Pull Requests [Selected Time Range]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n\tcount(distinct pr.id) as pull_request_count\nfrom \n\tpull_requests pr\n\tJOIN project_mapping pm on pr.base_repo_id = pm.row_id\nwhere pm.`table` = \"repos\"\n  and $__timeFilter(created_date)\n\tand pm.project_name in (${project_id})\n"
    }
   ]
  },
  {
   "title": "3.2 Total Number of New Pull Requests [Each Month]",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 1 },
   "targets": [
    {
     "rawSql": "with _prs as(\n  SELECT\n    DATE_ADD(date(created_date), INTERVAL -DAY(date(created_date))+1 DAY) as time,\n    count(distinct id) as pr_count\n  FROM pull_requests\n  JOIN project_mapping pm on pull_requests.base_repo_id = pm.row_id\nwhere pm.`table` = \"repos\"\n  and $__timeFilter(created_date)\n\tand pm.project_name in (${project_id})\n  and created_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n  group by 1\n)\n\nSELECT \n  date_format(time,'%M %Y') as month,\n  pr_count as \"Pull Request Count\"\nFROM _prs\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "3.3 Top Contributors By Merged PRs",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "-- The PR/MR statuses are standardized to DevLake's statuses 'OPEN', 'MERGED' and 'CLOSED'. You can check out the original status from the field `original_status`\nselect\n  author_name,\n\tcount(distinct pr.id) as merged_pull_request_count\nfrom \n\tpull_requests pr\n\tJOIN project_mapping pm on pr.base_repo_id = pm.row_id\nwhere pm.`table` = \"repos\" and\n  $__timeFilter(created_date)\n\tand pm.project_name in (${project_id})\n  and pr.status = 'MERGED'\ngroup by 1\norder by 2 desc\nlimit 20\n"
    }
   ]
  },
  { "title": "2. How PRs are handled?", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "4.1 Ratio of Non-merging Pull Requests of All Closed PRs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "-- The PR/MR statuses are standardized to DevLake's statuses 'OPEN', 'MERGED' and 'CLOSED'. You can check out the original status from the field `original_status`\nselect\n  count(distinct case when status = 'MERGED' then id else null end)/count(distinct case when status in ('CLOSED', 'MERGED') then id else null end) as ratio\nfrom \n\tpull_requests pr\n\tJOIN project_mapping pm on pr.base_repo_id = pm.row_id\nwhere pm.`table` = \"repos\" and\n  $__timeFilter(created_date)\n\tand pm.project_name in (${project_id})"
    }
   ]
  },
  {
   "title": "4.2 Pull Request Status Distribution [Each Month]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 14 },
   "targets": [
    {
     "rawSql": "-- The PR/MR statuses are standardized to DevLake's statuses 'OPEN', 'MERGED' and 'CLOSED'. You can check out the original status from the field `original_status`\nSELECT\n  DATE_ADD(date(created_date), INTERVAL -DAYOFMONTH(date(created_date))+1 DAY) as time,\n  count(distinct case when status = 'OPEN' then id else null end) as \"PR: Open\",\n  count(distinct case when status = 'CLOSED' then id else null end) as \"PR: Closed without merging\",\n  count(distinct case when status = 'MERGED' then id else null end) as \"PR: Closed and merged\"\nfrom \n\tpull_requests\n\tJOIN project_mapping pm on pull_requests.base_repo_id = pm.row_id\nwhere pm.`table` = \"repos\" and\n  $__timeFilter(created_date)\n\tand pm.project_name in (${project_id})\n  and created_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\ngroup by 1\n"
    }
   ]
  },
  {
   "title": "4.3 Number of Pull Requests Closed without Merging [Selected Time Range]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- The PR/MR statuses are standardized to DevLake's statuses 'OPEN', 'MERGED' and 'CLOSED'. You can check out the original status from the field `original_status`\nselect\n\tcount(distinct pr.id) as merged_pull_request_count\nfrom \n\tpull_requests pr\n\tJOIN project_mapping pm on pr.base_repo_id = pm.row_id\nwhere pm.`table` = \"repos\" and\n  $__timeFilter(created_date)\n\tand pm.project_name in (${project_id})\n\tand pr.status = 'CLOSED'"
    }
   ]
  },
  {
   "title": "4.4 Ratio of Non-merging Pull Requests of All Closed PRs [Each Month]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "-- The PR/MR statuses are standardized to DevLake's statuses 'OPEN', 'MERGED' and 'CLOSED'. You can check out the original status from the field `original_status`\nSELECT\n  DATE_ADD(date(created_date), INTERVAL -DAYOFMONTH(date(created_date))+1 DAY) as time,\n  count(distinct case when status = 'CLOSED' then id else null end)/count(distinct case when status in ('CLOSED', 'MERGED') then id else null end) as ratio\nfrom \n\tpull_requests pr\n\tJOIN project_mapping pm on pr.base_repo_id = pm.row_id\nwhere pm.`table` = \"repos\" and\n  $__timeFilter(created_date)\n\tand pm.project_name in (${project_id})\ngroup by 1\n"
    }
   ]
  },
  {
   "title": "4.5 Mean Time to Merge of Pull Requests in Days [Selected Time Range]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n\tavg(TIMESTAMPDIFF(Minute,created_date,merged_date)/1440)\nfrom \n\tpull_requests pr\n\tJOIN project_mapping pm on pr.base_repo_id = pm.row_id\nwhere pm.`table` = \"repos\" and\n  $__timeFilter(created_date)\n\tand pm.project_name in (${project_id})\n\tand pr.merged_date is not null\n\n\n"
    }
   ]
  },
  {
   "title": "4.6 Mean Time to Merge of Pull Requests in Days [Each Month]",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 26 },
   "targets": [
    {
     "rawSql": "with _prs as(\n  SELECT\n    DATE_ADD(date(created_date), INTERVAL -DAY(date(created_date))+1 DAY) as time,\n    avg(TIMESTAMPDIFF(Minute,created_date,merged_date)/1440) as time_to_merge\n  from \n\tpull_requests\n\tJOIN project_mapping pm on pull_requests.base_repo_id = pm.row_id\nwhere pm.`table` = \"repos\" and\n  $__timeFilter(created_date)\n\tand pm.project_name in (${project_id})\n    and created_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n  group by 1\n)\n\nSELECT \n  date_format(time,'%M %Y') as month,\n  time_to_merge as \"Time to Merge\"\nFROM _prs\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "4.7 Mean Time to Close of Pull Requests in Days [Selected Time Range]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "select\n\tavg(TIMESTAMPDIFF(Minute,created_date,closed_date)/1440) as time_to_close\nfrom \n\tpull_requests pr\n\tJOIN project_mapping pm on pr.base_repo_id = pm.row_id\nwhere pm.`table` = \"repos\" and\n  $__timeFilter(created_date)\n\tand pm.project_name in (${project_id})\n\tand pr.status in ('CLOSED', 'MERGED')\n\n\n"
    }
   ]
  },
  {
   "title": "4.8 Mean Time to Close of Pull Requests in Days [Each Month]",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 32 },
   "targets": [
    {
     "rawSql": "with _prs as(\n  SELECT\n    DATE_ADD(date(created_date), INTERVAL -DAY(date(created_date))+1 DAY) as time,\n    avg(TIMESTAMPDIFF(Minute,created_date,closed_date)/1440) as time_to_close\n  from \n\tpull_requests\n\tJOIN project_mapping pm on pull_requests.base_repo_id = pm.row_id\nwhere pm.`table` = \"repos\" and\n  $__timeFilter(created_date)\n\tand pm.project_name in (${project_id})\n    and created_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n    and status in ('CLOSED', 'MERGED')\n  group by 1\n)\n\nSELECT \n  date_format(time,'%M %Y') as month,\n  time_to_close as \"Time to Close\"\nFROM _prs\nORDER BY time\n"
    }
   ]
  },
  { "title": "3. CI/CD Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "5.1 Total Number of Successful workflow runs [Selected Time Range]",
   "type": "stat",
   "description": "Number of workflow runs executed in the selected time range",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct id)\nFROM \n  cicd_pipelines\n  JOIN project_mapping pm on cicd_pipelines.cicd_scope_id = pm.row_id\nWHERE pm.`table` = \"cicd_scopes\" and\n  $__timeFilter(finished_date)\n  AND pm.project_name IN (${project_id})\n  and result = 'SUCCESS'\n  and id like \"%github%\"\n  -- the following condition will remove the month with incomplete data\n  and finished_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)"
    }
   ]
  },
  {
   "title": "5.2 Mean Workflow Runs Success Rate",
   "type": "stat",
   "description": "Number of successful workflow runs / Number of total workflow runs",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  1.0 * count(case when result = 'SUCCESS' then id else null end)/count(distinct id)\nFROM \n  cicd_pipelines\n  JOIN project_mapping pm on cicd_pipelines.cicd_scope_id = pm.row_id\nWHERE pm.`table` = \"cicd_scopes\" and\n  $__timeFilter(finished_date)\n  AND pm.project_name IN (${project_id})\n  and id like \"%github%\"\n  -- the following condition will remove the month with incomplete data\n  and finished_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)"
    }
   ]
  },
  {
   "title": "5.3 Total Workflow Runs Result Distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  result,\n  count(distinct id) as build_count\nFROM \n  cicd_pipelines\n  JOIN project_mapping pm on cicd_pipelines.cicd_scope_id = pm.row_id\nWHERE pm.`table` = \"cicd_scopes\" and\n  $__timeFilter(finished_date)\n  AND pm.project_name IN (${project_id})\n  and id like \"%github%\"\n  -- the following condition will remove the month with incomplete data\n  and finished_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\nGROUP BY 1\nORDER BY 2 desc"
    }
   ]
  },
  {
   "title": "5.4 Mean Workflow Runs Duration in Minutes",
   "type": "stat",
   "description": "Number of successful workflow runs / Number of total workflow runs",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg(duration_sec/60) as duration_in_minutes\nFROM \n  cicd_pipelines\n  JOIN project_mapping pm on cicd_pipelines.cicd_scope_id = pm.row_id\nWHERE pm.`table` = \"cicd_scopes\" and\n  $__timeFilter(finished_date)\n  AND pm.project_name IN (${project_id})\n  and id like \"%github%\"\n  -- the following condition will remove the month with incomplete data\n  and finished_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)"
    }
   ]
  },
  {
   "title": "5.3.1 Number of Successful and Failed workflow runs [Each Month]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 45 },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_ADD(date(finished_date), INTERVAL -DAYOFMONTH(date(finished_date))+1 DAY) as time,\n  count(distinct case when result = 'SUCCESS' then id else null end) as successful_workflow_run_count,\n  count(distinct case when result != 'SUCCESS' then id else null end) as failed_workflow_run_count\nFROM \n  cicd_pipelines\n  JOIN project_mapping pm on cicd_pipelines.cicd_scope_id = pm.row_id\nWHERE pm.`table` = \"cicd_scopes\" and\n  $__timeFilter(finished_date)\n  AND pm.project_name IN (${project_id})\n  and id like \"%github%\"\n  -- the following condition will remove the month with incomplete data\n  and finished_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\nGROUP BY 1"
    }
   ]
  }
 ]
}