{
 "title": "Gitlab",
 "time": { "from": "now-5y", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Time Interval", "query": "Week : DAYOFWEEK, Month : DAY" },
   {
    "name": "board_id",
    "label": "Choose Board",
    "query": "select distinct concat(name, ': ', id) from jira_boards"
   },
   {
    "name": "repo_id",
    "label": "Choose Repo",
    "query": "select distinct concat(name, ': ', gitlab_id) from gitlab_projects"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Developer Count",
   "type": "stat",
   "description": "1. Number of people who have created or reviewed a Pull/Merge Request.\n2. The PR/MR being calculated are filtered by \"PR/MR creation time\" (time filter at the upper-right corner).",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "with all_developers as(\n  select \n    gitlab_reviewers.name as user_name\n  from gitlab_merge_requests\n  join gitlab_reviewers on gitlab_reviewers.merge_request_id = gitlab_merge_requests.gitlab_id\n\n  WHERE\n    $__timeFilter(gitlab_merge_requests.gitlab_created_at)\n    and gitlab_merge_requests.project_id = $repo_id\n  union\n  select \n    distinct author_username as user_name \n  from gitlab_merge_requests\n  WHERE\n    $__timeFilter(gitlab_merge_requests.gitlab_created_at)\n    and gitlab_merge_requests.project_id = $repo_id\n  union\n  select \n    distinct author_name as user_name \n  from gitlab_commits\n  WHERE\n    $__timeFilter(authored_date)\n    and gitlab_commits.project_id = $repo_id\n)\n\n\nSELECT\n  now() AS \"time\",\n  count(distinct user_name) as developer_count\nFROM all_developers"
    }
   ]
  },
  {
   "title": "80th Percentile Pull Request Review Time(day)",
   "type": "stat",
   "description": "1. The 80th percentile PR/MR review time.\n2. The PR/MR being calculated are filtered by \"PR/MR creation time\" (time filter at the upper-right corner) and \"Gitlab repo\"(\"Choose Repo\" filter at the upper-left corner)",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "with _ranks as(\n  select \n    TIMESTAMPDIFF(SECOND,gitlab_created_at,merged_at)/86400 as metric,\n    percent_rank() over (order by TIMESTAMPDIFF(MINUTE,gitlab_created_at,merged_at) asc) as ranks\n  from gitlab_merge_requests\n  WHERE\n    merged_at is not null\n\t\tand merged_at != ''\n    and $__timeFilter(gitlab_created_at)\n    and project_id = $repo_id\n  )\n  \nselect\n  now() as time,\n  max(metric) as value\nfrom _ranks\nwhere \n  ranks <= 0.8\ngroup by 1"
    }
   ]
  },
  {
   "title": "Pull Request Review Time over Time",
   "type": "timeseries",
   "description": "1. The average and 80th percentile PR/MR review time over time.\n2. The time granularity can be switched to week or month by \"Time Interval\" above. \n3. When Time Interval is set to \"month\", the average review time of \"2021-06-01\" refers to the review time of PR/MR whose creation time falls under [2020-06-01, 2020-07-01)",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "with reviewed_mr as(\n  select\n    DATE_ADD(date(gitlab_created_at), INTERVAL -$interval(date(gitlab_created_at))+1 DAY) as time,\n    TIMESTAMPDIFF(SECOND,first_comment_time,merged_at)/86400 as review_time\n  from gitlab_merge_requests\n  WHERE\n    merged_at is not null\n    and $__timeFilter(gitlab_created_at)\n    and project_id = $repo_id\n)\n\nselect \n  timestamp(time) as time,\n  avg(review_time) as \"Average Review Time\"\nfrom reviewed_mr\ngroup by 1\norder by 1 asc"
    }
   ]
  },
  {
   "title": "Commit Count",
   "type": "stat",
   "description": "1. Total number of commits created.\n2. The commits being calculated are filtered by \"authored_date\" (time filter at the upper-right corner) and \"Gitlab repo\"(\"Choose Repo\" filter at the upper-left corner)",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() AS \"time\",\n  count(*) as value\nFROM gitlab_commits\nWHERE\n  $__timeFilter(authored_date)\n  and project_id = $repo_id\ngroup by 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Commit Count over Time",
   "type": "timeseries",
   "description": "1. Number of commits created over time.\n2. When Time Interval is set to \"month\", the commit_count\" of \"2021-06-01\" calculates the commits whose creation time falls under [2020-06-01, 2020-07-01)",
   "gridPos": { "h": 7, "w": 12, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "with _commits as(\n  SELECT\n    DATE_ADD(date(authored_date), INTERVAL -$interval(date(authored_date))+1 DAY) as time,\n    count(*) as commit_count\n  FROM gitlab_commits\n  WHERE\n    $__timeFilter(authored_date)\n    and project_id = $repo_id\n  group by 1\n)\n\nSELECT \n  timestamp(time) as time,\n  commit_count as \"Commit Count\"\nFROM _commits\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Commit Count by Repo",
   "type": "graph",
   "description": "The number of commits from different repos.",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  gp.name as metric,\n  count(*) as value\nFROM gitlab_commits gc\n  join gitlab_projects gp on gc.project_id = gp.gitlab_id\nWHERE\n  $__timeFilter(authored_date)\n  and gc.project_id = $repo_id\ngroup by 1,2\norder by 1"
    }
   ]
  },
  {
   "title": "Commit Count by Author",
   "type": "barchart",
   "description": "The number of commits from different commit authors.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  gc.author_name as \"Author Name\",\n  count(*) as value\nFROM gitlab_commits gc \n  join gitlab_projects gp on gc.project_id = gp.gitlab_id\nWHERE\n  $__timeFilter(authored_date)\n  and gc.project_id = $repo_id\ngroup by 1,2\norder by 3 desc\nlimit 20"
    }
   ]
  },
  {
   "title": "Added LOC",
   "type": "stat",
   "description": "1. Sum of the number of added lines of code under all commits.\n2. The commits being calculated are filtered by \"authored_date\" (time filter at the upper-right corner) and \"Gitlab repo\"(\"Choose Repo\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() AS time,\n  sum(additions) as value\nFROM gitlab_commits gc\n  join gitlab_projects gp on gc.project_id = gp.gitlab_id \nWHERE\n  message not like '%Merge branch%'\n  and $__timeFilter(authored_date)\n  and gc.project_id = $repo_id\ngroup by 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Deleted LOC",
   "type": "stat",
   "description": "1. Sum of the number of deleted lines of code under all commits.\n2. The commits being calculated are filtered by \"authored_date\" (time filter at the upper-right corner) and \"Gitlab repo\"(\"Choose Repo\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() AS time,\n  sum(deletions) as value\nFROM gitlab_commits gc\n  join gitlab_projects gp on gc.project_id = gp.gitlab_id \nWHERE\n  message not like '%Merge branch%'\n  and $__timeFilter(authored_date)\n  and gc.project_id = $repo_id\ngroup by 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Added and Deleted LOC over Time",
   "type": "timeseries",
   "description": "Added/deleted number of lines of code over time.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with loc as(\n  SELECT\n    DATE_ADD(date(authored_date), INTERVAL -$interval(date(authored_date))+1 DAY) as time,\n    sum(additions) as added_LOC,\n    sum(deletions) as deleted_LOC\n  FROM gitlab_commits\n  WHERE\n    message not like '%Merge branch%'\n    and $__timeFilter(authored_date)\n    and project_id = $repo_id\n  group by 1\n)\n\nSELECT \n  timestamp(time) as time,\n  added_LOC as \"Added LOC\",\n  deleted_LOC as \"Deleted LOC\"\nFROM loc\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Added and Deleted LOC by Author",
   "type": "barchart",
   "description": "The number of added/deleted LOC from different commit authors.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  sum(additions) as \"Added LOC\",\n  sum(deletions) as \"Removed LOC\",\n  gc.author_name\nFROM gitlab_commits gc \n  join gitlab_projects gp on gc.project_id = gp.gitlab_id\nWHERE\n  author_name is not null\n  and message not like '%Merge branch%'\n  and $__timeFilter(authored_date)\n  and gc.project_id = $repo_id\ngroup by 1,4\norder by 2 desc\nlimit 20"
    }
   ]
  },
  {
   "title": "Commit Author Count",
   "type": "stat",
   "description": "1. Total number of Commit Authors.\n2. The commits being calculated are filtered by \"authored_date\" (time filter at the upper-right corner).",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() AS time,\n  count(distinct author_name) as value\nFROM gitlab_commits\nWHERE\n  $__timeFilter(authored_date)\n  and project_id = $repo_id\ngroup by 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Pull Request Reviewer Count",
   "type": "stat",
   "description": "1. Number of Pull/Merge Request Reviewers.\n2. The PR/MR being calculated are filtered by \"PR/MR creation time\" (time filter at the upper-right corner).",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select \n  now() as time,\n  count(distinct name)\nfrom\n  gitlab_reviewers"
    }
   ]
  },
  {
   "title": "Pull Request Reviewer Rate (%)",
   "type": "stat",
   "description": "Pull Request Reviewer Count/Total Developer Count",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "with all_user_names as(\n  select \n    distinct gitlab_reviewers.name as user_name\n  from gitlab_reviewers\n  join gitlab_merge_requests on gitlab_reviewers.merge_request_id = gitlab_merge_requests.gitlab_id\n  WHERE\n    $__timeFilter(gitlab_merge_requests.gitlab_created_at)\n    and gitlab_reviewers.project_id = $repo_id\n  union\n  select \n    distinct author_username as user_name \n  from gitlab_merge_requests\n  WHERE\n    $__timeFilter(gitlab_created_at)\n    and project_id = $repo_id\n  union\n  select \n    distinct author_name as user_name \n  from gitlab_commits\n  WHERE\n   $__timeFilter(authored_date)\n    and project_id = $repo_id\n),\n\nreviewer as (\n  select distinct gitlab_reviewers.name from gitlab_reviewers\n  join gitlab_merge_requests on gitlab_reviewers.merge_request_id = gitlab_merge_requests.gitlab_id\nWHERE\n    $__timeFilter(gitlab_merge_requests.gitlab_created_at)\n    and gitlab_reviewers.project_id = $repo_id\n)\n\nSELECT\n  now() AS \"time\",\n  1.0*count(distinct reviewer.name)/count(distinct user_name) as value\nFROM reviewer, all_user_names"
    }
   ]
  }
 ]
}