{
 "title": "Jira lead times & Gitlab basics",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   { "name": "ProjectId", "label": "ProjectId", "query": "Select id from gitlab_projects" }
  ]
 },
 "panels": [
  {
   "title": "Merge Review Time (Days)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  merged_at::varchar as \"Merged At Time\",\n  (merged_at::date - first_comment_time::date) as \"Review Time in Days\"\nFROM\n  gitlab_merge_requests\nWHERE\n  $__timeFilter(merged_at) AND project_id = $ProjectId \n\n"
    }
   ]
  },
  {
   "title": "Contributors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(email) from (\n\n  SELECT\n    committer_email\n  FROM gitlab_commits\n  WHERE\n    $__timeFilter(gitlab_commits.committed_date) AND gitlab_commits.project_id = $ProjectId\n  Group By committer_email\n) as email\n"
    }
   ]
  },
  {
   "title": "Reviewers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(id) from (\n  SELECT\n    unnest(reviewers) as reviewer\n  FROM\n    gitlab_merge_requests\n  WHERE\n    $__timeFilter(gitlab_created_at) AND project_id = $ProjectId\n  group by \n    reviewer\n) as id\n\n"
    }
   ]
  },
  {
   "title": "Lines Of Code",
   "type": "stat",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(id) as \"Commits\",\n  sum(additions) as \"Additions\",\n  sum(deletions) as \"Deletions\",\n  sum(additions - deletions) as \"LOC\"\nFROM gitlab_commits\nWHERE\n  $__timeFilter(gitlab_commits.committed_date) AND gitlab_commits.project_id = $ProjectId\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Merge Request Ratio",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\nWITH merged as (\nSELECT\n  count(id)\nFROM\n  gitlab_merge_requests\nWHERE\n  merged_at IS NOT NULL AND\n  $__timeFilter(gitlab_created_at) AND \n  project_id = $ProjectId\n), notMerged as (SELECT\n  count(id)\nFROM\n  gitlab_merge_requests\nWHERE\n  merged_at IS NULL AND\n  $__timeFilter(gitlab_created_at) AND \n  project_id = $ProjectId)\n\nSELECT (SELECT * FROM notMerged) as \"Not Merged\",\n (SELECT * FROM merged) as \"Merged\",\n \n(((SELECT * FROM merged)::float/((SELECT * FROM notMerged) + (SELECT * FROM merged)))::float) as \"Ratio\"\n  \n  \n\n\n\n\n"
    }
   ]
  },
  {
   "title": "Merge Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(id) as \"Merge Requests\"\nFROM gitlab_merge_requests\nWHERE\n  $__timeFilter(gitlab_created_at) AND project_id = $ProjectId\nORDER BY 1"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Issues Lead Time",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "select \r\n  now() as time,\r\n  title as title,\r\n  lead_time\r\nfrom jira_issues\r\nwhere \r\n  lead_time > 0\r\n  and $__timeFilter(issue_created_at)\r\norder by created_at;\r\n\r\n"
    }
   ]
  },
  {
   "title": "Lead Time Distribution",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select now() as time, count(*) as value, format('>%s', bucket*5) as metric\nfrom (\n  select lead_time, width_bucket(lead_time, ARRAY[5, 10, 15, 20]) as bucket\n  from jira_issues\n  where lead_time > 0\n    and $__timeFilter(issue_created_at)\n) as t\ngroup by bucket\norder by bucket"
    }
   ]
  },
  {
   "title": "Lead Time Median Trend",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select \n  to_date(to_char(issue_created_at, 'YYYY-MM'), 'YYYY-MM') as time_month,\n  percentile_cont(0.5) within group (order by lead_time) as value\nfrom jira_issues\nwhere lead_time > 0\n  and $__timeFilter(issue_created_at)\ngroup by to_char(issue_created_at, 'YYYY-MM')\norder by 1"
    }
   ]
  }
 ]
}