{
 "title": "Jenkins By Team",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project_id",
    "label": "Teams",
    "query": "select distinct name from projects"
   }
  ]
 },
 "panels": [
  {
   "title": "1. Total Number of Successful Builds [Selected Time Range]",
   "type": "stat",
   "description": "Number of builds executed in the selected time range",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct id)\nFROM \n  cicd_pipelines\n  JOIN project_mapping pm on cicd_pipelines.cicd_scope_id = pm.row_id\nWHERE pm.`table` = \"cicd_scopes\" and\n  $__timeFilter(finished_date)\n  AND pm.project_name IN (${project_id})\n  and result = 'SUCCESS'\n  and id like \"%jenkins%\"\n  -- the following condition will remove the month with incomplete data\n"
    }
   ]
  },
  {
   "title": "2. Mean Build Success Rate",
   "type": "stat",
   "description": "Number of successful builds / Number of total builds",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  1.0 * count(case when result = 'SUCCESS' then id else null end)/count(distinct id)\nFROM \n  cicd_pipelines\n  JOIN project_mapping pm on cicd_pipelines.cicd_scope_id = pm.row_id\nWHERE pm.`table` = \"cicd_scopes\" and\n  $__timeFilter(finished_date)\n  AND pm.project_name IN (${project_id})\n  and id like \"%jenkins%\"\n  -- the following condition will remove the month with incomplete data\n"
    }
   ]
  },
  {
   "title": "3. Total Build Result Distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  result,\n  count(distinct id) as build_count\nFROM \n  cicd_pipelines\n  JOIN project_mapping pm on cicd_pipelines.cicd_scope_id = pm.row_id\nWHERE pm.`table` = \"cicd_scopes\" and\n  $__timeFilter(finished_date)\n  AND pm.project_name IN (${project_id})\n  and id like \"%jenkins%\"\n  -- the following condition will remove the month with incomplete data\nGROUP BY 1\nORDER BY 2 desc"
    }
   ]
  },
  {
   "title": "4. Mean Build Duration in Minutes",
   "type": "stat",
   "description": "Number of successful builds / Number of total builds",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg(duration_sec/60) as duration_in_minutes\nFROM \n  cicd_pipelines\n  JOIN project_mapping pm on cicd_pipelines.cicd_scope_id = pm.row_id\nWHERE pm.`table` = \"cicd_scopes\" and\n  $__timeFilter(finished_date)\n  AND pm.project_name IN (${project_id})\n  and id like \"%jenkins%\"\n  -- the following condition will remove the month with incomplete data\n"
    }
   ]
  },
  {
   "title": "3.1 Number of Successful and Failed Builds [Each Month]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_ADD(date(finished_date), INTERVAL -DAYOFMONTH(date(finished_date))+1 DAY) as time,\n  count(distinct case when result = 'SUCCESS' then id else null end) as successful_build_count,\n  count(distinct case when result != 'SUCCESS' then id else null end) as failed_build_count\nFROM \n  cicd_pipelines\n  JOIN project_mapping pm on cicd_pipelines.cicd_scope_id = pm.row_id\nWHERE pm.`table` = \"cicd_scopes\" and\n  $__timeFilter(finished_date)\n  AND pm.project_name IN (${project_id})\n  and id like \"%jenkins%\"\n  -- the following condition will remove the month with incomplete data\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "2.1 Build Success Rate [Each Month]",
   "type": "barchart",
   "description": "1. Mean Build success rate over time.\n2. The builds being calculated are filtered by \"build starting time\" (time filter at the upper-right corner) and \"Jira board\" (\"Choose Board\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "WITH _build_success_rate as(\r\n  SELECT\r\n    DATE_ADD(date(finished_date), INTERVAL -DAYOFMONTH(date(finished_date))+1 DAY) as time,\r\n    result,\r\n    id\r\n  FROM \r\n  cicd_pipelines\r\n  JOIN project_mapping pm on cicd_pipelines.cicd_scope_id = pm.row_id\r\nWHERE pm.`table` = \"cicd_scopes\" and\r\n  $__timeFilter(finished_date)\r\n  AND pm.project_name IN (${project_id})\r\n    and id like \"%jenkins%\"\r\n    -- the following condition will remove the month with incomplete data\r\n  GROUP BY\r\n    time, result, id\r\n)\r\n\r\nSELECT \r\n  date_format(time,'%M %Y') as month,\r\n  1.0 * sum(case when result = 'SUCCESS' then 1 else 0 end)/ count(*) as \"Build Success Rate\"\r\nFROM _build_success_rate\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "1.1 Total Number of Successful Builds [Each Month]",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "rawSql": "WITH _builds as(\n  SELECT\n    DATE_ADD(date(finished_date), INTERVAL -DAYOFMONTH(date(finished_date))+1 DAY) as time,\n    count(distinct id) as build_count\n  FROM \n  cicd_pipelines\n  JOIN project_mapping pm on cicd_pipelines.cicd_scope_id = pm.row_id\nWHERE pm.`table` = \"cicd_scopes\" and\n  $__timeFilter(finished_date)\n  AND pm.project_name IN (${project_id})\n    and result = 'SUCCESS'\n    and id like \"%jenkins%\"\n    -- the following condition will remove the month with incomplete data\n  GROUP BY 1\n)\n\nSELECT \n  date_format(time,'%M %Y') as month,\n  build_count as \"Build Count\"\nFROM _builds\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "4.1 Mean Build Duration in Minutes [Each Month]",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "WITH _builds as(\n  SELECT\n    DATE_ADD(date(finished_date), INTERVAL -DAYOFMONTH(date(finished_date))+1 DAY) as time,\n    avg(duration_sec) as mean_duration_sec\n  FROM \n  cicd_pipelines\n  JOIN project_mapping pm on cicd_pipelines.cicd_scope_id = pm.row_id\n  WHERE pm.`table` = \"cicd_scopes\" and\n  $__timeFilter(finished_date)\n  AND pm.project_name IN (${project_id})\n    and id like \"%jenkins%\"\n    -- the following condition will remove the month with incomplete data\n  GROUP BY 1\n)\n\nSELECT \n  date_format(time,'%M %Y') as month,\n  mean_duration_sec/60 as mean_duration_minutes\nFROM _builds\nORDER BY time\n"
    }
   ]
  }
 ]
}