{
 "title": "Jira",
 "tags": [
  "Data Specific Dashboard",
  "Jira"
 ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Time Interval", "query": "Week : DAYOFWEEK, Month : DAY" },
   {
    "name": "board_id",
    "label": "Choose Board",
    "query": "select distinct concat(name, ': ', id) from jira_boards"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"display: block;text-align: center;margin-top: 56px;\">\n  <div style=\"display: inline-flex;\">\n    <img src=\"/public/img/lake/1.png\" alt=\"No.1\" width=\"56\">\n    <p style=\"font-size:24px; margin:10px; color:#BFC1C8;\"><b>Requirement Metrics<b></b></b></p><b><b>\n  </div>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Avg Requirement Lead Time (day)",
   "type": "stat",
   "description": "1. The average lead time of requirements.\n2. Lead time refers to the length of time from requirement creation to delivery.\n3. The requirements being calculated are filtered by \"requirement resolution time\" (time filter at the upper-right corner) and \"Jira board\"(\"Choose Board\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select \r\n  now() as time,\r\n  avg(lead_time/1440) as value\r\nfrom jira_issues ji\r\n  join jira_board_issues jbi on ji.id = jbi.issue_id\r\nwhere \r\n  std_type = 'Requirement'\r\n  and std_status = 'Resolved'\r\n  and $__timeFilter(resolution_date)\r\n  and jbi.board_id = $board_id\r\ngroup by 1;"
    }
   ]
  },
  {
   "title": "80th Percentile Requirement Lead Time (day)",
   "type": "stat",
   "description": "1. The lead time at which 80% requirements‘ lead time lies below it.\n2. The requirements being calculated are filtered by \"requirement resolution time\" (time filter at the upper-right corner) and \"Jira board\" (\"Choose Board\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with _ranks as(\r\n  select \r\n    ji.lead_time,\r\n    percent_rank() over (order by lead_time asc) as ranks\r\n  from jira_issues ji\r\n    join jira_board_issues jbi on ji.id = jbi.issue_id\r\n  where \r\n    std_type = 'Requirement'\r\n    and std_status = 'Resolved'\r\n    and $__timeFilter(resolution_date)\r\n    and jbi.board_id = $board_id\r\n)\r\n\r\nselect\r\n  now() as time,\r\n  max(lead_time/1440) as value\r\nfrom _ranks\r\nwhere \r\n  ranks <= 0.8\r\ngroup by 1"
    }
   ]
  },
  {
   "title": "Requirement Lead Time over Time",
   "type": "graph",
   "description": "1. The average requirement lead time over time.\n2. The time granularity can be switched to Week or Month by \"Time Interval\" above. \n3. When Time Interval is set to \"Month\", the average_lead_time of \"2021-06-01\" refers to the average lead time of requirements whose resolution time falls under [2020-06-01, 2020-07-01).",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Lead Time(day)" }
   ],
   "targets": [
    {
     "rawSql": "with _requirement as(\r\n  select \r\n    DATE_ADD(date(resolution_date), INTERVAL -$interval(date(resolution_date))+1 DAY) as time,\r\n    lead_time\r\n  from jira_issues ji\r\n    join jira_board_issues jbi on ji.id = jbi.issue_id\r\n  where \r\n    std_type = 'Requirement'\r\n    and std_status = 'Resolved'\r\n    and $__timeFilter(resolution_date)\r\n    and jbi.board_id = $board_id\r\n)\r\n\r\nselect \r\n  timestamp(time) as time,\r\n  avg(lead_time/1440) as average_lead_time\r\nfrom _requirement\r\ngroup by 1\r\norder by 1 asc"
    }
   ]
  },
  {
   "title": "Requirement Lead Time (Cumulative Distribution)",
   "type": "graph",
   "description": "1. The cumulative distribution of requirement lead time. \n2. Each point refers to the percent rank of a lead time.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent Rank (%)" }
   ],
   "targets": [
    {
     "rawSql": "with _ranks as(\r\n  select \r\n    round(ji.lead_time/1440) as lead_time_day\r\n  from jira_issues ji\r\n    join jira_board_issues jbi on ji.id = jbi.issue_id\r\n  where \r\n    std_type = 'Requirement'\r\n    and std_status = 'Resolved'\r\n    and $__timeFilter(resolution_date)\r\n    and jbi.board_id = $board_id\r\n  order by lead_time_day asc\r\n)\r\n\r\nselect \r\n  now() as time,\r\n  lpad(concat(lead_time_day,'d'), 4, ' ') as metric,\r\n  percent_rank() over (order by lead_time_day asc) as value\r\nfrom _ranks\r\norder by lead_time_day asc"
    }
   ]
  },
  {
   "title": "Average Requirement Lead Time by Epic",
   "type": "barchart",
   "description": "The average lead time of requirements under different Jira Epics.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "with _requirement as(\r\n  select\r\n    ji.id,\r\n    epic_key,\r\n    ji.lead_time\r\n  from\r\n    jira_issues ji\r\n    join jira_board_issues jbi on ji.id = jbi.issue_id\r\n  where \r\n    ji.std_type = 'Requirement'\r\n    and ji.std_status = 'Resolved'\r\n    and ji.epic_key is not null\r\n    and ji.epic_key != ''\r\n    and $__timeFilter(resolution_date)\r\n    and jbi.board_id = $board_id\r\n)\r\n\r\nselect \r\n  now() as time,\r\n  epic_key as \"Epic Key\",\r\n  avg(lead_time/1440) as value\r\nfrom _requirement\r\ngroup by 1,2\r\norder by 3 desc\r\nlimit 20"
    }
   ]
  },
  {
   "title": "Average Requirement Lead Time by Status",
   "type": "barchart",
   "description": "The average time spent in each state of a requirement, including all history states that have been used.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "with operation_history as(\n\tSELECT\n\t\tjc.issue_id,\n\t\tjc.created as operation_time,\n\t\tjci.changelog_id,\n\t\tjci.from,\n\t\tjci.from_string,\n\t\tjci.to,\n\t\tjci.to_string,\n\t\tji.created as issue_creation_time,\n\t\tcase \n\t\t\twhen lag(jc.created) over(PARTITION BY jc.issue_id ORDER BY jc.created ASC) is not null then\n\t\t\tTIMESTAMPDIFF(MINUTE, lag(jc.created) over(PARTITION BY jc.issue_id ORDER BY jc.created ASC), jc.created)\n\t\t\telse TIMESTAMPDIFF(MINUTE, ji.created, jc.created) end as time_in_status\n\tFROM\n\t\tjira_changelogs jc\n\t\tJOIN jira_changelog_items jci ON jc.id = jci.changelog_id\n\t\tJOIN jira_issues ji ON jc.issue_id = ji.id\n\t\tjoin jira_board_issues jbi on ji.id = jbi.issue_id\n\tWHERE\n\t\tjci.field = 'status'\n\t\tand ji.std_type = 'Requirement'\n\t\tand ji.std_status = 'Resolved'\n\t\tand $__timeFilter(ji.resolution_date)\n    and jbi.board_id = $board_id\n)\n\nSELECT\n  now() as time,\n\tfrom_string as \"Requirement Status\",\n\tavg(time_in_status)/1440 as \"Time in Status\"\nFROM operation_history\nGROUP BY 1,2\nORDER BY 3 desc"
    }
   ]
  },
  {
   "title": "Average Requirement Lead Time by Status in Last 2 Months",
   "type": "barchart",
   "description": "1. Compare the average time spent in each state of a requirement in the last 2 months.\n2. The requirements being calculated are the requirements delivered in the last 2 months.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with status_change_history as(\n\tSELECT\n\t\tjc.issue_id,\n\t\tjc.created as operation_time,\n\t\tjci.changelog_id,\n\t\tjci.from,\n\t\tjci.from_string,\n\t\tjci.to,\n\t\tjci.to_string,\n\t\tji.created as issue_creation_time,\n\t\tlag(jc.created) over(PARTITION BY jc.issue_id ORDER BY jc.created ASC) as last_operation_time,\n\t\tcase \n\t\t\twhen lag(jc.created) over(PARTITION BY jc.issue_id ORDER BY jc.created ASC) is not null then\n\t\t\tTIMESTAMPDIFF(MINUTE, lag(jc.created) over(PARTITION BY jc.issue_id ORDER BY jc.created ASC), jc.created)\n\t\t\telse TIMESTAMPDIFF(MINUTE, ji.created, jc.created) end as time_in_status\n\tFROM\n\t\tjira_changelogs jc\n\t\tJOIN jira_changelog_items jci ON jc.id = jci.changelog_id\n\t\tJOIN jira_issues ji ON jc.issue_id = ji.id\n\t\tjoin jira_board_issues jbi on ji.id = jbi.issue_id\n\tWHERE\n\t\tjci.field = 'status'\n\t\tand ji.std_type = 'Requirement'\n\t\tand ji.std_status = 'Resolved'\n\t\tand $__timeFilter(ji.resolution_date)\n    and jbi.board_id = $board_id\n),\n\ntime_in_status as(\n\tSELECT \n\t\tDATE_ADD(date(issue_creation_time), INTERVAL -DAY(date(issue_creation_time))+1 DAY) as time,\n\t\tfrom_string,\n\t\tavg(time_in_status)/60 as time_in_status\n\tFROM status_change_history\n\tGROUP BY 1,2\n),\n\nlast_month as(\n\tselect \n\t\tDATE_ADD(date(CURDATE()), INTERVAL -DAY(date(CURDATE()))+1 DAY) as last_month\n),\n\nmonth_before_last_month as(\n\tSELECT \n\t\tDATE_ADD(DATE_ADD(date(CURDATE()), INTERVAL -DAY(date(CURDATE()))+1 DAY), INTERVAL -1 MONTH) as two_month_before\n),\n\n\nlast_month_record as(\n\tSELECT\n\t\tfrom_string as issue_status,\n\t\tcase when time in (SELECT last_month from last_month) then time_in_status else null end as last_month\n\tfrom time_in_status\n\tWHERE \n\t\ttime in (SELECT last_month from last_month)\n),\n\ntwo_month_before_record as(\n\tSELECT\n\t\tfrom_string as issue_status,\n\t\tcase when time in (SELECT two_month_before from month_before_last_month) then time_in_status else null end as two_month_before\n\tfrom time_in_status\n\tWHERE \n\t\ttime in (SELECT two_month_before from month_before_last_month)\n)\n\nSELECT\n\tnow() as time,\n\tmbr.two_month_before AS \"The Month Before Last\",\n\tlmr.last_month AS \"Last Month\",\n\tlmr.issue_status\nFROM last_month_record lmr\nleft join two_month_before_record mbr on lmr.issue_status = mbr.issue_status "
    }
   ]
  },
  {
   "title": "Requirement Count",
   "type": "stat",
   "description": "1. Total number of requirements created.\n2. The requirements being calculated are filtered by \"requirement creation time\" (time filter at the upper-right corner) and \"Jira board\" (\"Choose Board\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \r\n  now() as time,\r\n  count(*) as value\r\nfrom jira_issues ji\r\n  join jira_board_issues jbi on ji.id = jbi.issue_id\r\nwhere \r\n  std_type = 'Requirement'\r\n  and created is not null \r\n  and $__timeFilter(created)\r\n  and jbi.board_id = $board_id\r\ngroup by 1;"
    }
   ]
  },
  {
   "title": "Requirement Count over Time",
   "type": "timeseries",
   "description": "1. The number of requirements created over time.\n2. The time granularity can be switched to week or month by \"Time Interval\" above. \n3. When Time Interval is set to \"month\", the requirement_count of \"2021-06-01\" refers to the number of requirements whose creation time falls under [2020-06-01, 2020-07-01)",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with _requirement as(\r\n  select\r\n    ji.id,\r\n    DATE_ADD(date(created), INTERVAL -$interval(date(created))+1 DAY) as time\r\n  from\r\n    jira_issues ji\r\n    join jira_board_issues jbi on ji.id = jbi.issue_id\r\n  where \r\n    std_type = 'Requirement'\r\n    and created is not null \r\n    and $__timeFilter(created)\r\n    and jbi.board_id = $board_id\r\n)\r\n\r\nselect\r\n  timestamp(time) as time,\r\n  count(distinct id) as requirement_count\r\nfrom _requirement\r\ngroup by 1\r\norder by 1 asc"
    }
   ]
  },
  {
   "title": "Requirement Count by Epic",
   "type": "barchart",
   "description": "1. The number of requirements under different Jira Epics.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "with _requirement as(\r\n  select\r\n    ji.id,\r\n    ji.epic_key\r\n  from\r\n    jira_issues ji\r\n    join jira_board_issues jbi on ji.id = jbi.issue_id\r\n  where \r\n    std_type = 'Requirement'\r\n    and created is not null\r\n    and epic_key is not null\r\n    and epic_key != ''\r\n    and std_status = 'Resolved'\r\n    and $__timeFilter(created)\r\n    and jbi.board_id = $board_id\r\n)\r\n\r\nselect \r\n  now() as time,\r\n  epic_key as \"Epic Key\",\r\n  count(*) as value\r\nfrom _requirement\r\ngroup by 1,2\r\norder by 3 desc\r\nlimit 20"
    }
   ]
  },
  {
   "title": "Delivered Requirement Count",
   "type": "stat",
   "description": "1. Number of requirements that have been delivered.\n2. A requirement is delivered when its status equals 'delivered'.\n3. The requirements being calculated are filtered by \"requirement creation time\" (time filter at the upper-right corner) and \"Jira board\" (\"Choose Board\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\r\n  now() as time,\r\n  count(*) as delivered_count\r\nfrom jira_issues ji\r\n  join jira_board_issues jbi on ji.id = jbi.issue_id\r\nwhere \r\n  std_type = 'Requirement'\r\n  and ji.std_status = 'Resolved'\r\n  and $__timeFilter(created)\r\n  and jbi.board_id = $board_id"
    }
   ]
  },
  {
   "title": "Requirement Delivery Rate",
   "type": "stat",
   "description": "Delivered Requirement Count/Requirement Count (Total)",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with _requirement as(\r\n  select\r\n    count(distinct ji.id) as total_count,\r\n    count(distinct case when ji.std_status = 'Resolved' then ji.id else null end) as delivered_count\r\n  from jira_issues ji\r\n    join jira_board_issues jbi on ji.id = jbi.issue_id\r\n  where \r\n    std_type = 'Requirement'\r\n    and $__timeFilter(created)\r\n    and jbi.board_id = $board_id\r\n)\r\n\r\n\r\nselect \r\n  now() as time,\r\n  1.0 * delivered_count/total_count as requirement_delivery_rate\r\nfrom _requirement"
    }
   ]
  },
  {
   "title": "Requirement Delivery Rate over Time",
   "type": "timeseries",
   "description": "1. The requirement delivery rate over time.\n2. When Time Interval is set to \"month\", value \"requirement_delivery_rate\" of \"2021-06-01\" calculates the requirements whose creation time falls under [2020-06-01, 2020-07-01)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "with _requirement as(\r\n  select\r\n    DATE_ADD(date(created), INTERVAL -$interval(date(created))+1 DAY) as time,\r\n    count(distinct ji.id) as total_count,\r\n    count(distinct case when ji.std_status = 'Resolved' then ji.id else null end) as delivered_count\r\n  from jira_issues ji\r\n    join jira_board_issues jbi on ji.id = jbi.issue_id\r\n  where \r\n    std_type = 'Requirement'\r\n    and $__timeFilter(created)\r\n    and jbi.board_id = $board_id\r\n  group by 1\r\n)\r\n\r\n\r\nselect \r\n  timestamp(time) as time,\r\n  1.0 * delivered_count/total_count as requirement_delivery_rate\r\nfrom _requirement\r\norder by 1"
    }
   ]
  },
  {
   "title": "Requirement Delivery Rate by Epic",
   "type": "barchart",
   "description": "The average delivery rate of requirements under different Jira Epics.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "with _requirement as(\r\n  select\r\n    ji.epic_key as metric,\r\n    count(distinct ji.id) as total_count,\r\n    count(distinct case when ji.std_status = 'Resolved' then ji.id else null end) as delivered_count\r\n  from jira_issues ji\r\n    join jira_board_issues jbi on ji.id = jbi.issue_id\r\n  where \r\n    std_type = 'Requirement'\r\n    and epic_key is not null\r\n    and epic_key != ''\r\n    and $__timeFilter(created)\r\n    and jbi.board_id = $board_id\r\n  group by 1\r\n)\r\n\r\n\r\nselect \r\n  now() as time,\r\n  metric,\r\n  1.0 * delivered_count/total_count as requirement_delivery_rate\r\nfrom _requirement\r\norder by 3 desc\r\nlimit 20"
    }
   ]
  },
  {
   "title": "Avg Requirement Granunarity(Story Point)",
   "type": "stat",
   "description": "1. The average story point (workload) of requirements.\n2. The requirements being calculated are filtered by \"requirement creation time\" (time filter at the upper-right corner) and \"Jira board\" (\"Choose Board\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \r\n  now() as time,\r\n  avg(std_story_point) as value\r\nfrom jira_issues ji\r\n  join jira_board_issues jbi on ji.id = jbi.issue_id\r\nwhere \r\n  std_type = 'Requirement'\r\n  and std_story_point != 0\r\n  and $__timeFilter(created)\r\n  and jbi.board_id = $board_id\r\ngroup by 1;"
    }
   ]
  },
  {
   "title": "80th Percentile Requirement Granunarity(Story point)",
   "type": "stat",
   "description": "1. The story point/estimated hours at which 80% requirements' story point/estimated hours lies below it.\n2. The requirements being calculated are filtered by \"requirement creation time\" (time filter at the upper-right corner) and \"Jira board\" (\"Choose Board\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with _ranks as(\r\n  select \r\n    std_story_point,\r\n    percent_rank() over (order by std_story_point asc) as ranks\r\n  from jira_issues ji\r\n    join jira_board_issues jbi on ji.id = jbi.issue_id\r\n  where \r\n    std_type = 'Requirement'\r\n    and std_story_point != 0\r\n    and $__timeFilter(created)\r\n    and jbi.board_id = $board_id\r\n)\r\n\r\nselect\r\n  now() as time,\r\n  max(std_story_point) as value\r\nfrom _ranks\r\nwhere \r\n  ranks <= 0.8\r\ngroup by 1"
    }
   ]
  },
  {
   "title": "Requirement Granularity over Time",
   "type": "graph",
   "description": "The average and 80th percentile requirement granularity over time.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Story Points" }
   ],
   "targets": [
    {
     "rawSql": "with _requirement as(\r\n  select \r\n    ji.id,\r\n    DATE_ADD(date(resolution_date), INTERVAL -$interval(date(resolution_date))+1 DAY) as time,\r\n    std_story_point\r\n  from jira_issues ji\r\n    join jira_board_issues jbi on ji.id = jbi.issue_id\r\n  where \r\n    std_type = 'Requirement'\r\n    and std_story_point != 0\r\n    and $__timeFilter(created)\r\n    and jbi.board_id = $board_id\r\n)\r\n\r\nselect \r\n  timestamp(time) as time,\r\n  avg(std_story_point) as average_story_point\r\nfrom _requirement\r\ngroup by 1\r\norder by 1 asc"
    }
   ]
  },
  {
   "title": "Requirement Granularity (Cumulative Distribution)",
   "type": "graph",
   "description": "1. The cumulative distribution of requirement granularity.\n2. Each point refers to the percent rank of a value of granularity.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent Rank (%)" }
   ],
   "targets": [
    {
     "rawSql": "with _ranks as(\r\n  select \r\n    round(std_story_point) as std_story_point\r\n  from jira_issues ji\r\n    join jira_board_issues jbi on ji.id = jbi.issue_id\r\n  where \r\n    std_type = 'Requirement'\r\n    and std_story_point != 0\r\n    and $__timeFilter(created)\r\n    and jbi.board_id = $board_id\r\n  order by std_story_point asc\r\n)\r\n\r\nselect \r\n  now() as time,\r\n  lpad(std_story_point, 4, ' ') as metric,\r\n  percent_rank() over (order by std_story_point asc) as value\r\nfrom _ranks\r\norder by std_story_point asc"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 70 },
   "options": {
    "content": "<div style=\"display: block;text-align: center;margin-top: 56px;\">\n  <div style=\"display: inline-flex;\">\n    <img src=\"/public/img/lake/2.png\" alt=\"No.2\" width=\"56\">\n    <p style=\"font-size:24px; margin:10px; color:#BFC1C8;\"><b>Bug Metrics<b></b></b></p><b><b>\n  </div>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of Bugs found in Testing",
   "type": "stat",
   "description": "1. Total number of bugs created.\n2. The bugs being calculated are filtered by \"bug creation time\" (time filter at the upper-right corner)",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  count(*) as value\nFROM\n  jira_issues ji\n  join jira_board_issues jbi on ji.id = jbi.issue_id\nWHERE\n  std_type = 'Bug'\n  and jbi.board_id = $board_id\n  and $__timeFilter(created)\n"
    }
   ]
  },
  {
   "title": "Number of Bugs found in Testing over Time",
   "type": "timeseries",
   "description": "1. Number of bugs created over time.\n2. The time granularity can be switched to week or month by \"Time Interval\" above. \n3. When Time Interval is set to \"month\", bug_count of \"2021-06-01\" calculates the bugs whose creation time falls under [2020-06-01, 2020-07-01)",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "with _bugs as (\n  SELECT\n    DATE_ADD(date(ji.created), INTERVAL -$interval(date(ji.created))+1 DAY) as time,\n    count(distinct ji.id) as bug_count\n  FROM\n    jira_issues ji\n    LEFT JOIN jira_board_issues jbi ON jbi.issue_id = ji.id\n  WHERE\n    std_type = 'Bug'\n    and jbi.board_id = $board_id\n    and $__timeFilter(ji.created)\n  group by 1\n  order by 1\n) \n\nselect \n  timestamp(time) as time,\n  bug_count\nfrom _bugs"
    }
   ]
  },
  {
   "title": "Average Bug Age (day)",
   "type": "stat",
   "description": "1. The average bug age.\n2. Bug age refers to the length of time from bug creation to resolution.\n3. The bugs being calculated are filtered by \"bug resolution time\" (time filter at the upper-right corner) and \"Jira board\"(\"Choose Board\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select \r\n  now() as time,\r\n  avg(lead_time/1440) as value\r\nfrom jira_issues ji\r\n  join jira_board_issues jbi on ji.id = jbi.issue_id\r\nwhere \r\n  std_type = 'Bug'\r\n  and std_status = 'Resolved'\r\n  and $__timeFilter(resolution_date)\r\n  and jbi.board_id = $board_id\r\ngroup by 1;"
    }
   ]
  },
  {
   "title": "80th Percentile Bug Age (day)",
   "type": "stat",
   "description": "1. The bug age at which 80% bugs‘ age lies below it.\n2. The bugs being calculated are filtered by \"bug resolution time\" (time filter at the upper-right corner) and \"Jira board\" (\"Choose Board\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "with _ranks as(\r\n  select \r\n    ji.lead_time,\r\n    percent_rank() over (order by lead_time asc) as ranks\r\n  from jira_issues ji\r\n    join jira_board_issues jbi on ji.id = jbi.issue_id\r\n  where \r\n    std_type = 'Bug'\r\n    and std_status = 'Resolved'\r\n    and $__timeFilter(resolution_date)\r\n    and jbi.board_id = $board_id\r\n)\r\n\r\nselect\r\n  now() as time,\r\n  max(lead_time/1440) as value\r\nfrom _ranks\r\nwhere \r\n  ranks <= 0.8\r\ngroup by 1"
    }
   ]
  },
  {
   "title": "Average Bug Age over Time",
   "type": "timeseries",
   "description": "1. The average and 80th percentile bug age over time.\n2. The time granularity can be switched to Week or Month by \"Time Interval\" above. \n3. When Time Interval is set to \"Month\", the average_bug_age of \"2021-06-01\" refers to the average age of bugs whose resolution time falls under [2020-06-01, 2020-07-01).",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with _bugs as(\r\n  select \r\n    ji.id,\r\n    DATE_ADD(date(resolution_date), INTERVAL -$interval(date(resolution_date))+1 DAY) as time,\r\n    lead_time,\r\n    round(lead_time/1440) as lead_time_day\r\n  from jira_issues ji\r\n    join jira_board_issues jbi on ji.id = jbi.issue_id\r\n  where \r\n    std_type = 'Bug'\r\n    and std_status = 'Resolved'\r\n    and $__timeFilter(resolution_date)\r\n    and jbi.board_id = $board_id\r\n)\r\n\r\nselect \r\n  timestamp(time) as time,\r\n  avg(lead_time/1440) as \"Average Lead Time\"\r\nfrom _bugs\r\ngroup by 1\r\norder by 1 asc"
    }
   ]
  },
  {
   "title": "Bug Age (Cumulative Distribution)",
   "type": "graph",
   "description": "1. The cumulative distribution of bug age. \n2. Each point refers to the percent rank of a bug age.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit", "label": "Percent Rank (%)" }
   ],
   "targets": [
    {
     "rawSql": "with _ranks as(\r\n  select \r\n    round(ji.lead_time/1440) as lead_time_day\r\n  from jira_issues ji\r\n    join jira_board_issues jbi on ji.id = jbi.issue_id\r\n  where \r\n    std_type = 'Bug'\r\n    and std_status = 'Resolved'\r\n    and $__timeFilter(resolution_date)\r\n    and jbi.board_id = $board_id\r\n  order by lead_time_day asc\r\n)\r\n\r\nselect \r\n  now() as time,\r\n  lpad(concat(lead_time_day,'d'), 4, ' ') as metric,\r\n  percent_rank() over (order by lead_time_day asc) as value\r\nfrom _ranks\r\norder by lead_time_day asc"
    }
   ]
  },
  {
   "title": "Average Bug Age by Epic",
   "type": "barchart",
   "description": "The average time spent on fixing bugs under different Jira Epics.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 92 },
   "targets": [
    {
     "rawSql": "with _bugs as(\r\n  select\r\n    ji.id,\r\n    ji.epic_key,\r\n    ji.lead_time\r\n  from\r\n    jira_issues ji\r\n    join jira_board_issues jbi on ji.id = jbi.issue_id\r\n  where \r\n    std_type = 'Bug'\r\n    and std_status = 'Resolved'\r\n    and epic_key is not null\r\n    and epic_key != ''\r\n    and $__timeFilter(resolution_date)\r\n    and jbi.board_id = $board_id\r\n)\r\n\r\nselect \r\n  now() as time,\r\n  epic_key as \"Epic Key\",\r\n  avg(lead_time)/1440 as \"Bug Age\"\r\nfrom _bugs\r\ngroup by 1,2\r\norder by 3 desc\r\nlimit 20"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 98 },
   "options": {
    "content": "<div style=\"display: block;text-align: center;margin-top: 56px;\">\n  <div style=\"display: inline-flex;\">\n    <img src=\"/public/img/lake/3.png\" alt=\"No.3\" width=\"56\">\n    <p style=\"font-size:24px; margin:10px; color:#BFC1C8;\"><b>Incident Metrics<b></b></b></p><b><b>\n  </div>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of Incidents found after shipping",
   "type": "stat",
   "description": "1. Total number of incidents created.\n2. The incidents being calculated are filtered by \"incident creation time\" (time filter at the upper-right corner)",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 102 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  count(*) as value\nFROM\n  jira_issues ji\n  join jira_board_issues jbi on ji.id = jbi.issue_id\nWHERE\n  std_type = 'Incident'\n  and jbi.board_id = $board_id\n  and $__timeFilter(created)\n"
    }
   ]
  },
  {
   "title": "Number of Incidents found after shipping over Time",
   "type": "timeseries",
   "description": "1. Number of incidents created over time.\n2. The time granularity can be switched to week or month by \"Time Interval\" above. \n3. When Time Interval is set to \"month\", incident_count of \"2021-06-01\" calculates the incidents whose creation time falls under [2020-06-01, 2020-07-01)",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "with _incidents as (\n  SELECT\n    DATE_ADD(date(ji.created), INTERVAL -$interval(date(ji.created))+1 DAY) as time,\n    count(distinct ji.id) as incident_count\n  FROM\n    jira_issues ji\n    LEFT JOIN jira_board_issues jbi ON jbi.issue_id = ji.id\n  WHERE\n    std_type = 'Incident'\n    and jbi.board_id = $board_id\n    and $__timeFilter(ji.created)\n  group by 1\n  order by 1\n) \n\nselect \n  timestamp(time) as time,\n  incident_count\nfrom _incidents"
    }
   ]
  },
  {
   "title": "Average Incident Age (day)",
   "type": "stat",
   "description": "1. The average incident age.\n2. Incident age refers to the length of time from incident creation to resolution.\n3. The incidents being calculated are filtered by \"incident resolution time\" (time filter at the upper-right corner) and \"Jira board\"(\"Choose Board\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 108 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select \r\n  now() as time,\r\n  avg(lead_time/1440) as value\r\nfrom jira_issues ji\r\n  join jira_board_issues jbi on ji.id = jbi.issue_id\r\nwhere \r\n  std_type = 'Incident'\r\n  and std_status = 'Resolved'\r\n  and $__timeFilter(resolution_date)\r\n  and jbi.board_id = $board_id\r\ngroup by 1;"
    }
   ]
  },
  {
   "title": "80th Percentile Incident Age (day)",
   "type": "stat",
   "description": "1. The incident age at which 80% incidents‘ age lies below it.\n2. The incidents being calculated are filtered by \"incident resolution time\" (time filter at the upper-right corner) and \"Jira board\" (\"Choose Board\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 108 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "with _ranks as(\r\n  select \r\n    ji.lead_time,\r\n    percent_rank() over (order by lead_time asc) as ranks\r\n  from jira_issues ji\r\n    join jira_board_issues jbi on ji.id = jbi.issue_id\r\n  where \r\n    std_type = 'Incident'\r\n    and std_status = 'Resolved'\r\n    and $__timeFilter(resolution_date)\r\n    and jbi.board_id = $board_id\r\n)\r\n\r\nselect\r\n  now() as time,\r\n  max(lead_time/1440) as value\r\nfrom _ranks\r\nwhere \r\n  ranks <= 0.8\r\ngroup by 1"
    }
   ]
  },
  {
   "title": "Average Incident Age over Time",
   "type": "timeseries",
   "description": "1. The average and 80th percentile incident age over time.\n2. The time granularity can be switched to Week or Month by \"Time Interval\" above. \n3. When Time Interval is set to \"Month\", the average_incident_age of \"2021-06-01\" refers to the average age of incidents whose resolution time falls under [2020-06-01, 2020-07-01).",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with _incidents as(\r\n  select \r\n    ji.id,\r\n    DATE_ADD(date(resolution_date), INTERVAL -$interval(date(resolution_date))+1 DAY) as time,\r\n    lead_time,\r\n    round(lead_time/1440) as lead_time_day\r\n  from jira_issues ji\r\n    join jira_board_issues jbi on ji.id = jbi.issue_id\r\n  where \r\n    std_type = 'Incident'\r\n    and std_status = 'Resolved'\r\n    and $__timeFilter(resolution_date)\r\n    and jbi.board_id = $board_id\r\n)\r\n\r\nselect \r\n  timestamp(time) as time,\r\n  avg(lead_time/1440) as \"Average Lead Time\"\r\nfrom _incidents\r\ngroup by 1\r\norder by 1 asc"
    }
   ]
  },
  {
   "title": "Incident Age (Cumulative Distribution)",
   "type": "graph",
   "description": "1. The cumulative distribution of incident age.\n2. Each point refers to the percent rank of a incident age.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit", "label": "Percent Rank (%)" }
   ],
   "targets": [
    {
     "rawSql": "with _ranks as(\r\n  select \r\n    round(ji.lead_time/1440) as lead_time_day\r\n  from jira_issues ji\r\n    join jira_board_issues jbi on ji.id = jbi.issue_id\r\n  where \r\n    std_type = 'Incident'\r\n    and std_status = 'Resolved'\r\n    and $__timeFilter(resolution_date)\r\n    and jbi.board_id = $board_id\r\n  order by lead_time_day asc\r\n)\r\n\r\nselect \r\n  now() as time,\r\n  lpad(concat(lead_time_day,'d'), 4, ' ') as metric,\r\n  percent_rank() over (order by lead_time_day asc) as value\r\nfrom _ranks\r\norder by lead_time_day asc"
    }
   ]
  },
  {
   "title": "Average Incident Age by Epic",
   "type": "barchart",
   "description": "The average time spent on fixing incidents under different Jira Epics.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 120 },
   "targets": [
    {
     "rawSql": "with _incidents as(\r\n  select\r\n    ji.id,\r\n    ji.epic_key,\r\n    ji.lead_time\r\n  from\r\n    jira_issues ji\r\n    join jira_board_issues jbi on ji.id = jbi.issue_id\r\n  where \r\n    std_type = 'Incident'\r\n    and std_status = 'Resolved'\r\n    and epic_key is not null\r\n    and epic_key != ''\r\n    and $__timeFilter(resolution_date)\r\n    and jbi.board_id = $board_id\r\n)\r\n\r\nselect \r\n  now() as time,\r\n  epic_key as \"Epic Key\",\r\n  avg(lead_time)/1440 as \"Incident Age\"\r\nfrom _incidents\r\ngroup by 1,2\r\norder by 3 desc\r\nlimit 20"
    }
   ]
  }
 ]
}