{
 "title": "Jira ART",
 "tags": [ "Migros" ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "board_id",
    "label": "Choose Board",
    "query": "select concat(name, '--', id) from boards where id like 'jira%' and  name like 'ART%'"
   },
   {
    "name": "type",
    "label": "Issue Type",
    "query": "select distinct type from issues limit 50"
   }
  ]
 },
 "panels": [
  { "title": "Work in Progress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Anzahl offene Features",
   "type": "stat",
   "gridPos": { "h": 14, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \r\n  count(*) as value\r\nfrom issues i\r\n  join board_issues bi on i.id = bi.issue_id\r\nwhere \r\n  i.type in ($type)\r\n  and i.status != 'DONE'\r\n  and bi.board_id in ($board_id)"
    }
   ]
  },
  {
   "title": "Aktuelle Epics",
   "type": "table",
   "gridPos": { "h": 14, "w": 14, "x": 4, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT \r\n--  si.issue_key as JiraTicket,\r\n--  si.status as Status,\r\n  ti.issue_key as Epic,\r\n  ti.title as Bezeichnung,\r\n  ti.status as Status\r\nFROM\r\n  issues si\r\n  left join issue_relationships ir on ir.source_issue_id = si.id\r\n  left join issues ti on ir.target_issue_id = ti.id\r\n  left JOIN board_issues bi ON si.id = bi.issue_id\r\nWHERE\r\n  si.type in ($type)\r\n  AND bi.board_id in ($board_id)\r\n  and (ti.issue_key like 'CTP%' or ti.issue_key like 'NLP%' or ti.issue_key like 'FIP%' or ti.issue_key like 'FIP%' or ti.issue_key like 'LPMSC%')\r\n  and ti.status in ('TODO', 'IN_PROGRESS')\r\nORDER BY ti.status\r\n"
    }
   ]
  },
  {
   "title": "Backlog Epic vs. non Epic Features",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select \r\n epic_issues.source_epicissue_count as 'Anzahl Epic Features',\r\n non_epic_issues.source_non_epicissue_count as 'Anzahl non Epic Features'\r\n FROM (\r\nSELECT \r\n    COUNT(si.issue_key) AS source_epicissue_count\r\nFROM \r\n  issues si\r\n  left join issue_relationships ir on ir.source_issue_id = si.id\r\n  left join issues ti on ir.target_issue_id = ti.id\r\n  left JOIN board_issues bi ON si.id = bi.issue_id\r\nWHERE\r\n  si.type in ($type)\r\n--  AND $__timeFilter(si.created_date)\r\n  AND bi.board_id in ($board_id)\r\n  and (ti.issue_key like 'CTP%' or ti.issue_key like 'NLP%' or ti.issue_key like 'FIP%' or ti.issue_key like 'LPMSC%')\r\n  AND si.status = 'TODO'\r\n) as epic_issues\r\nJOIN (SELECT\r\n    COUNT(DISTINCT si.issue_key) AS source_non_epicissue_count\r\nFROM \r\nissues si\r\n  left JOIN board_issues bi ON si.id = bi.issue_id\r\nWHERE\r\n  si.type in ($type)\r\n--  AND $__timeFilter(si.created_date)\r\n  AND bi.board_id in ($board_id)\r\n  AND si.issue_key NOT IN (\r\n    SELECT\r\n  si.issue_key as JiraTicket\r\nFROM\r\n  issues si\r\n  left join issue_relationships ir on ir.source_issue_id = si.id\r\n  left join issues ti on ir.target_issue_id = ti.id\r\n  left JOIN board_issues bi ON si.id = bi.issue_id\r\nWHERE\r\n  si.type in ($type)\r\n--  AND $__timeFilter(si.created_date)\r\n  AND bi.board_id in ($board_id)\r\n  and (ti.issue_key like 'CTP%' or ti.issue_key like 'NLP%' or ti.issue_key like 'FIP%' or ti.issue_key like 'LPMSC%')\r\n)\r\n  AND si.status = 'TODO'\r\n) as non_epic_issues\r\n;"
    }
   ]
  },
  {
   "title": "In Progress Epic vs. non Epic Features",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select \r\n epic_issues.source_epicissue_count as 'Anzahl Epic Features',\r\n non_epic_issues.source_non_epicissue_count as 'Anzahl non Epic Features'\r\n FROM (\r\nSELECT \r\n    COUNT(si.issue_key) AS source_epicissue_count\r\nFROM \r\n  issues si\r\n  left join issue_relationships ir on ir.source_issue_id = si.id\r\n  left join issues ti on ir.target_issue_id = ti.id\r\n  left JOIN board_issues bi ON si.id = bi.issue_id\r\nWHERE\r\n  si.type in ($type)\r\n--  AND $__timeFilter(si.created_date)\r\n  AND bi.board_id in ($board_id)\r\n  and (ti.issue_key like 'CTP%' or ti.issue_key like 'NLP%' or ti.issue_key like 'FIP%' or ti.issue_key like 'FIP%' or ti.issue_key like 'LPMSC%')\r\n  AND si.status = 'IN_PROGRESS'\r\n) as epic_issues\r\nJOIN (SELECT\r\n    COUNT(DISTINCT si.issue_key) AS source_non_epicissue_count\r\nFROM \r\nissues si\r\n  left JOIN board_issues bi ON si.id = bi.issue_id\r\nWHERE\r\n  si.type in ($type)\r\n--  AND $__timeFilter(si.created_date)\r\n  AND bi.board_id in ($board_id)\r\n  AND si.issue_key NOT IN (\r\n    SELECT\r\n  si.issue_key as JiraTicket\r\nFROM\r\n  issues si\r\n  left join issue_relationships ir on ir.source_issue_id = si.id\r\n  left join issues ti on ir.target_issue_id = ti.id\r\n  left JOIN board_issues bi ON si.id = bi.issue_id\r\nWHERE\r\n  si.type in ($type)\r\n--  AND $__timeFilter(si.created_date)\r\n  AND bi.board_id in ($board_id)\r\n  and (ti.issue_key like 'CTP%' or ti.issue_key like 'NLP%' or ti.issue_key like 'FIP%' or ti.issue_key like 'LPMSC%')\r\n)\r\n  AND si.status = 'IN_PROGRESS'\r\n) as non_epic_issues\r\n;"
    }
   ]
  },
  {
   "title": "Durchsatz im ausgewählten Zeitraum",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Anzahl Features Done",
   "type": "stat",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \r\n  count(*) as value\r\nfrom issues i\r\n  join board_issues bi on i.id = bi.issue_id\r\nwhere \r\n  i.type in ($type)\r\n  and i.status = 'DONE'\r\n  and $__timeFilter(i.resolution_date)\r\n  and bi.board_id in ($board_id)"
    }
   ]
  },
  {
   "title": "Nr. of Features Done pro Monat (Velocity)",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 14, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  DATE(i.resolution_date - INTERVAL DAY(i.resolution_date)-1 DAY) as time,\r\n  COUNT(DISTINCT CASE WHEN status = 'DONE' THEN i.id ELSE NULL END) as \"Number of Delivered Issues\"\r\nFROM issues i\r\n  JOIN board_issues bi ON i.id = bi.issue_id\r\nWHERE \r\n  i.type in ($type)\r\n  AND $__timeFilter(i.resolution_date)\r\n  AND bi.board_id in ($board_id)\r\nGROUP BY time"
    }
   ]
  },
  {
   "title": "Done Features",
   "type": "table",
   "gridPos": { "h": 24, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  issue_key as JiraTicket,\r\n  resolution_date as ResolutionDate,\r\n  lead_time_minutes/1440 as LeadTimeDays,\r\n  story_point\r\nFROM\r\n  issues i\r\n  JOIN board_issues bi ON i.id = bi.issue_id\r\nWHERE\r\n  i.type in ($type)\r\n  AND i.status = 'DONE'\r\n  AND $__timeFilter(i.resolution_date)\r\n  AND bi.board_id in ($board_id)\r\nORDER BY resolution_date desc\r\n"
    }
   ]
  },
  {
   "title": "Verteilung Done Featues (Epic vs. nonEpic)",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select \r\n epic_issues.source_epicissue_count as 'Anzahl Epic Features',\r\n non_epic_issues.source_non_epicissue_count as 'Anzahl non Epic Features'\r\n FROM (\r\nSELECT \r\n    COUNT(si.issue_key) AS source_epicissue_count\r\nFROM \r\n  issues si\r\n  left join issue_relationships ir on ir.source_issue_id = si.id\r\n  left join issues ti on ir.target_issue_id = ti.id\r\n  left JOIN board_issues bi ON si.id = bi.issue_id\r\nWHERE\r\n  si.type in ($type)\r\n  AND $__timeFilter(si.resolution_date)\r\n  AND bi.board_id in ($board_id)\r\n  and (ti.issue_key like 'CTP%' or ti.issue_key like 'NLP%' or ti.issue_key like 'FIP%' or ti.issue_key like 'LPMSC%')\r\n  AND si.status = 'DONE'\r\n) as epic_issues\r\nJOIN (SELECT\r\n    COUNT(DISTINCT si.issue_key) AS source_non_epicissue_count\r\nFROM \r\nissues si\r\n  left JOIN board_issues bi ON si.id = bi.issue_id\r\nWHERE\r\n  si.type in ($type)\r\n  AND $__timeFilter(si.resolution_date)\r\n  AND bi.board_id in ($board_id)\r\n  AND si.issue_key NOT IN (\r\n    SELECT\r\n  si.issue_key as JiraTicket\r\nFROM\r\n  issues si\r\n  left join issue_relationships ir on ir.source_issue_id = si.id\r\n  left join issues ti on ir.target_issue_id = ti.id\r\n  left JOIN board_issues bi ON si.id = bi.issue_id\r\nWHERE\r\n  si.type in ($type)\r\n  AND $__timeFilter(si.resolution_date)\r\n  AND bi.board_id in ($board_id)\r\n  and (ti.issue_key like 'CTP%' or ti.issue_key like 'NLP%' or ti.issue_key like 'FIP%' or ti.issue_key like 'LPMSC%')\r\n)\r\n  AND si.status = 'DONE'\r\n) as non_epic_issues\r\n;"
    }
   ]
  },
  {
   "title": "Verteilung Done Features (Epic vs. non Epic)",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 6, "y": 28 },
   "targets": [
    {
     "rawSql": "Select \r\n COALESCE(epic_issues.time, non_epic_issues.time) as time,\r\n epic_issues.source_epicissue_count,\r\n non_epic_issues.source_non_epicissue_count\r\n FROM (\r\nSELECT \r\n    DATE(si.resolution_date - INTERVAL DAY(si.resolution_date)-1 DAY) as time,\r\n    COUNT(si.issue_key) AS source_epicissue_count\r\nFROM \r\n  issues si\r\n  left join issue_relationships ir on ir.source_issue_id = si.id\r\n  left join issues ti on ir.target_issue_id = ti.id\r\n  left JOIN board_issues bi ON si.id = bi.issue_id\r\nWHERE\r\n  si.type in ($type)\r\n  AND $__timeFilter(si.resolution_date)\r\n  AND bi.board_id in ($board_id)\r\n  and (ti.issue_key like 'CTP%' or ti.issue_key like 'NLP%' or ti.issue_key like 'FIP%' or ti.issue_key like 'LPMSC%')\r\n  and si.status = 'DONE'\r\nGROUP BY \r\n    time\r\n) as epic_issues\r\nright JOIN (SELECT\r\n    DATE(si.resolution_date - INTERVAL DAY(si.resolution_date)-1 DAY) as time,\r\n    COUNT(DISTINCT si.issue_key) AS source_non_epicissue_count\r\nFROM \r\n    issues si\r\n  left JOIN board_issues bi ON si.id = bi.issue_id\r\nWHERE\r\n  si.type in ($type)\r\n  AND $__timeFilter(si.resolution_date)\r\n  AND bi.board_id in ($board_id)\r\n  and si.status = 'DONE'\r\n  AND si.issue_key NOT IN (\r\n    SELECT\r\n  si.issue_key as JiraTicket\r\nFROM\r\n  issues si\r\n  left join issue_relationships ir on ir.source_issue_id = si.id\r\n  left join issues ti on ir.target_issue_id = ti.id\r\n  left JOIN board_issues bi ON si.id = bi.issue_id\r\nWHERE\r\n  si.type in ($type)\r\n  AND $__timeFilter(si.resolution_date)\r\n  AND bi.board_id in ($board_id)\r\n  and (ti.issue_key like 'CTP%' or ti.issue_key like 'NLP%' or ti.issue_key like 'FIP%' or ti.issue_key like 'LPMSC%')\r\n  and si.status = 'DONE'\r\n)\r\nGROUP BY \r\n    time\r\n) as non_epic_issues\r\non epic_issues.time = non_epic_issues.time\r\n;"
    }
   ]
  },
  {
   "title": "Feature Lead Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Durchnittliche Lead Time Features [ Features done im ausgwählten Zeitraum]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select \r\n  avg(lead_time_minutes/1440) as value\r\nfrom issues i\r\n  join board_issues bi on i.id = bi.issue_id\r\nwhere \r\n  i.type in ($type)\r\n  and i.status = 'DONE'\r\n  and $__timeFilter(i.resolution_date)\r\n  and bi.board_id in ($board_id)"
    }
   ]
  },
  {
   "title": "Durchnittliche Lead Time Features [ Features done im ausgwählten Zeitraum]",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 20, "x": 4, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with _requirements as(\r\n  select \r\n    DATE_ADD(date(i.resolution_date), INTERVAL -DAYOFMONTH(date(i.resolution_date))+1 DAY) as time,\r\n    avg(lead_time_minutes/1440) as mean_lead_time\r\n  from issues i\r\n    join board_issues bi on i.id = bi.issue_id\r\n  where \r\n    i.type in ($type)\r\n    and i.status = 'DONE'\r\n    and $__timeFilter(i.resolution_date)\r\n    and bi.board_id in ($board_id)\r\n  group by 1\r\n)\r\n\r\nselect \r\n  date_format(time,'%M %Y') as month,\r\n  mean_lead_time\r\nfrom _requirements\r\norder by time asc"
    }
   ]
  },
  {
   "title": "80% Feature Lead Time sind weniger als # Tage[Features Done im ausgwählten Zeitraum]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with _ranks as(\r\n  select \r\n    i.lead_time_minutes,\r\n    percent_rank() over (order by lead_time_minutes asc) as ranks\r\n  from issues i\r\n    join board_issues bi on i.id = bi.issue_id\r\n  where \r\n    i.type in ($type)\r\n    and i.status = 'DONE'\r\n    and $__timeFilter(i.resolution_date)\r\n    and bi.board_id in ($board_id)\r\n)\r\n\r\nselect\r\n  max(lead_time_minutes/1440) as value\r\nfrom _ranks\r\nwhere \r\n  ranks <= 0.8"
    }
   ]
  },
  {
   "title": "Überläufer",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "WITH ReleaseDates AS (\r\n    SELECT \r\n        issue_id, \r\n        field_value AS releasedate,\r\n        ROW_NUMBER() OVER (PARTITION BY issue_id ORDER BY field_value) AS rn\r\n    FROM \r\n        issue_custom_array_fields\r\n    WHERE \r\n        field_id = 'x_releasedate'\r\n        -- Filtere nur die Einträge für Release-Daten\r\n       \r\n)\r\nSELECT \r\n    MIN(r.releasedate) AS releasedate,\r\n    -- Bestimme das früheste Release-Datum\r\n    SUM(CASE WHEN i.resolution_date <= r.releasedate THEN 1 ELSE 0 END) AS abgeschlossen_count,\r\n    -- Zähle die Anzahl der rechtzeitig abgeschlossenen Issues\r\n    SUM(CASE WHEN i.resolution_date > r.releasedate THEN 1 ELSE 0 END) AS ueberlaeufer_abgeschlossen_count,\r\n    -- Zähle die Anzahl der Überläufer (später abgeschlossen als geplant)\r\n    SUM(CASE WHEN i.resolution_date IS NULL AND CURRENT_DATE > r.releasedate THEN 1 ELSE 0 END) AS ueberlaeufer_offen_count\r\n    -- Zähle die Anzahl der offenen Überläufer (kein Abschlussdatum und Release-Datum ist vergangen)\r\nFROM \r\n    issues i\r\nJOIN \r\n    ReleaseDates r ON i.id = r.issue_id\r\n    -- Verbinde die Release-Daten mit der Issues-Tabelle\r\nLEFT JOIN \r\n    board_issues bi ON i.id = bi.issue_id\r\n    -- Optionale Verbindung mit der Board-Issues-Tabelle\r\nWHERE\r\n    bi.board_id IN ($board_id)\r\n    -- Filtere nach spezifischen Board-IDs\r\n     and r.releasedate < CURRENT_DATE\r\nGROUP BY \r\n    r.releasedate\r\n    -- Gruppiere die Ergebnisse nach Release-Datum\r\nORDER BY \r\n    MIN(r.releasedate) asc;\r\n    -- Sortiere die Ergebnisse nach dem frühesten Release-Datum\r\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 53 },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "WITH ReleaseDates AS (\r\n    SELECT \r\n        issue_id, \r\n        field_value AS releasedate,\r\n        ROW_NUMBER() OVER (PARTITION BY issue_id ORDER BY field_value) AS rn\r\n    FROM \r\n        issue_custom_array_fields\r\n    WHERE \r\n        field_id = 'x_releasedate'\r\n        -- Filtere nur die Einträge für Release-Daten\r\n)\r\nSELECT \r\n    MIN(r.releasedate) AS releasedate,\r\n    -- Bestimme das früheste Release-Datum\r\n    COUNT(i.id) AS issue_count,\r\n    -- Zähle die Anzahl der Issues pro Release-Datum\r\n    SUM(CASE WHEN i.resolution_date <= r.releasedate THEN 1 ELSE 0 END) AS abgeschlossen_count,\r\n    -- Zähle die Anzahl der rechtzeitig abgeschlossenen Issues\r\n    SUM(CASE WHEN i.resolution_date > r.releasedate THEN 1 ELSE 0 END) AS ueberlaeufer_abgeschlossen_count,\r\n    -- Zähle die Anzahl der Überläufer (später abgeschlossen als geplant)\r\n    SUM(CASE WHEN i.resolution_date IS NULL AND CURRENT_DATE > r.releasedate THEN 1 ELSE 0 END) AS ueberlaeufer_offen_count\r\n    -- Zähle die Anzahl der offenen Überläufer (kein Abschlussdatum und Release-Datum ist vergangen)\r\nFROM \r\n    issues i\r\nJOIN \r\n    ReleaseDates r ON i.id = r.issue_id\r\n    -- Verbinde die Release-Daten mit der Issues-Tabelle\r\nLEFT JOIN \r\n    board_issues bi ON i.id = bi.issue_id\r\n    -- Optionale Verbindung mit der Board-Issues-Tabelle\r\nWHERE\r\n    bi.board_id IN ($board_id)\r\n    -- Filtere nach spezifischen Board-IDs\r\nGROUP BY \r\n    r.releasedate\r\n    -- Gruppiere die Ergebnisse nach Release-Datum\r\nORDER BY \r\n    MIN(r.releasedate) DESC;\r\n    -- Sortiere die Ergebnisse nach dem frühesten Release-Datum\r\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 14, "w": 9, "x": 15, "y": 65 },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "WITH ReleaseDates AS (\r\n    SELECT \r\n        issue_id, \r\n        field_value AS releasedate\r\n    FROM \r\n        issue_custom_array_fields\r\n    WHERE \r\n        field_id = 'x_releasedate'\r\n        -- Filtere nur die Einträge für Release-Daten\r\n)\r\nSELECT \r\n    i.issue_key,\r\n    i.resolution_date,\r\n    r.releasedate\r\nFROM \r\n    issues i\r\nJOIN \r\n    ReleaseDates r ON i.id = r.issue_id\r\n    -- Verbinde die Release-Daten mit der Issues-Tabelle\r\nLEFT JOIN \r\n    board_issues bi ON i.id = bi.issue_id\r\n    -- Optionale Verbindung mit der Board-Issues-Tabelle\r\nWHERE\r\n    bi.board_id IN ($board_id)\r\n    -- Filtere nach spezifischen Board-IDs\r\nORDER BY \r\n    r.releasedate, i.issue_key;\r\n    -- Sortiere die Ergebnisse nach Release-Datum und Issue-Key\r\n"
    }
   ]
  }
 ]
}