{
 "title": "PingCAP_Release_Quality",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "repo_id",
    "label": "Repo",
    "query": "select concat(name, '-', id) as text from repos"
   }
  ]
 },
 "panels": [
  {
   "title": "1. Bug distribution in minor versions",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Get the bug distribution in major versions\nwith bugs_in_each_tag as(\n\tselect \n\t\tSUBSTRING_INDEX(rid.new_ref_name,'refs/tags/', -1) as tag_name, \n\t\tSUBSTRING_INDEX(rid.new_ref_name,':', 3) as repo_id,\n\t\ti.key, i.type, i.title, i.summary\n\tfrom\n\t\trefs_issues_diffs rid\n\t\tleft join issues i on rid.issue_id = i.id\n\twhere\n\t\tSUBSTRING_INDEX(rid.new_ref_name,':', 3) = '$repo_id'\n\t\t-- and i.type = 'BUG'\n)\n\n\nSELECT \n\tconcat(SUBSTRING_INDEX(biet.tag_name,'.',2), '.x') as major_version,\n\tcount(*) as bug_count\nFROM \n\tbugs_in_each_tag biet\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "2. Bug fixed count and rework cost percentage in the last 10 tags",
   "type": "barchart",
   "description": "'Rework cost percentage' = dev_eq in bugfix/total_dev_eq",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "-- Get the number of fixed bugs in the last 10 tags\nwith _last_10_tags as(\n  SELECT \n    distinct new_ref_name, old_ref_name\n  FROM \n    refs_commits_diffs\n  WHERE\n\t\tSUBSTRING_INDEX(new_ref_name,':', 3) = '$repo_id'\n\tORDER BY 1 desc\n\tLIMIT 10\n),\n\n_bugs_of_tags as(\n\tselect \n\t\tSUBSTRING_INDEX(rid.new_ref_name,'refs/', -1) as tag_name, \n\t\tSUBSTRING_INDEX(rid.new_ref_name,':', 3) as repo_id,\n\t\tcount(*) as bug_count\n\tfrom\n\t\trefs_issues_diffs rid\n\t\tleft join issues i on rid.issue_id = i.id\n\twhere\n\t\tSUBSTRING_INDEX(rid.new_ref_name,':', 3) = '$repo_id'\n\t\tand rid.new_ref_name in (SELECT new_ref_name FROM _last_10_tags)\n\t\tand i.type = 'BUG'\n\tGROUP BY 1,2\n),\n\n_dev_eq_of_pr as(\n  select\n    SUBSTRING_INDEX(rcd.new_ref_name,'refs/', -1) as tag_name, \n\t\tSUBSTRING_INDEX(rcd.new_ref_name,':', 3) as repo_id,\n    pr.id as pull_request_id,\n    sum(c.dev_eq) as dev_eq\n  FROM \n    refs_commits_diffs rcd\n\t\tleft join commits c on rcd.commit_sha = c.sha\n\t\t-- left join pull_request_commits prc on c.sha = prc.commit_sha\n\t\tleft join pull_requests pr on c.sha = pr.merge_commit_sha\n\twhere\n\t\tSUBSTRING_INDEX(rcd.new_ref_name,':', 3) = '$repo_id'\n\t\tand rcd.new_ref_name in (SELECT new_ref_name FROM _last_10_tags)\n\tgroup by 1,2,3\n),\n\n_pr_worktype as(\n  select\n    distinct pri.pull_request_id,i.type\n  from\n    pull_request_issues pri\n    left join pull_requests pr on pri.pull_request_id = pr.id\n    left join issues i on pri.issue_id = i.id\n  where \n    issue_number != 0\n),\n\n_pr_elco_and_worktype as(\n  select\n    deop.tag_name, \n    sum(case when pw.type = 'BUG' then dev_eq else 0 end)/sum(dev_eq) as rework_cost_percentage\n  from \n    _dev_eq_of_pr deop\n    left join _pr_worktype pw on deop.pull_request_id = pw.pull_request_id\n  GROUP BY 1\n)\n\nSELECT \n\tbot.tag_name,\n\tbot.bug_count,\n\tpeaw.rework_cost_percentage\nFROM \n\t_bugs_of_tags bot\n\tjoin _pr_elco_and_worktype peaw on bot.tag_name = peaw.tag_name\nORDER BY 1"
    }
   ]
  },
  {
   "title": "3.1 Component distribution of bugs fixed in the last 10 tags",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Component distribution of bugs fixed in the last 10 tags\nwith _last_10_tags as(\n  SELECT \n    distinct new_ref_name, old_ref_name\n  FROM \n    refs_commits_diffs\n  WHERE\n\t\tSUBSTRING_INDEX(new_ref_name,':', 3) = '$repo_id'\n\tORDER BY 1 desc\n\tLIMIT 10\n),\n\nbugs_in_each_tag as(\n\tselect \n\t\tSUBSTRING_INDEX(rid.new_ref_name,'refs/', -1) as tag_name, \n\t\tSUBSTRING_INDEX(rid.new_ref_name,':', 3) as repo_id,\n\t\ti.key, i.component, i.severity, i.title, i.summary\n\tfrom\n\t\trefs_issues_diffs rid\n\t\tleft join issues i on rid.issue_id = i.id\n\twhere\n\t\tSUBSTRING_INDEX(rid.new_ref_name,':', 3) = '$repo_id'\n\t\tand rid.new_ref_name in (SELECT new_ref_name FROM _last_10_tags)\n\t\tand i.type = 'BUG'\n)\n\n\nSELECT\n\tcase when component = '' then 'unlabeled' else 'labeled' end as component,\n\tcount(*) as bug_count\nFROM \n\tbugs_in_each_tag biet\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "3.2 Component distribution of bugs fixed in the last 10 tags",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Component distribution of bugs fixed in the last 10 tags\nwith _last_10_tags as(\n  SELECT \n    distinct new_ref_name, old_ref_name\n  FROM \n    refs_commits_diffs\n  WHERE\n\t\tSUBSTRING_INDEX(new_ref_name,':', 3) = '$repo_id'\n\tORDER BY 1 desc\n\tLIMIT 10\n),\n\nbugs_in_each_tag as(\n\tselect \n\t\tSUBSTRING_INDEX(rid.new_ref_name,'refs/', -1) as tag_name, \n\t\tSUBSTRING_INDEX(rid.new_ref_name,':', 3) as repo_id,\n\t\ti.key, i.component, i.severity, i.title, i.summary\n\tfrom\n\t\trefs_issues_diffs rid\n\t\tleft join issues i on rid.issue_id = i.id\n\twhere\n\t\tSUBSTRING_INDEX(rid.new_ref_name,':', 3) = '$repo_id'\n\t\tand rid.new_ref_name in (SELECT new_ref_name FROM _last_10_tags)\n\t\tand i.type = 'BUG'\n)\n\n\nSELECT\n\tcomponent,\n\tcount(*) as bug_count\nFROM \n\tbugs_in_each_tag biet\nwhere \n  component != ''\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "4.1 % of contributors who fixed 80% of bugs in the last 10 tags",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Get the bug fixer distribution in the last 10 tags\nwith _last_10_tags as(\n  SELECT \n    distinct new_ref_name, old_ref_name\n  FROM \n    refs_commits_diffs\n  WHERE\n\t\tSUBSTRING_INDEX(new_ref_name,':', 3) = '$repo_id'\n\tORDER BY 1 desc\n\tLIMIT 10\n),\n\n_bugs as(\n\tselect \n\t\ti.key, i.type, i.severity, i.title, i.summary,\n\t\tpr.id, pr.author_name as pr_author, pr.created_date,\n\t\trank() over(partition by i.id order by pr.created_date asc) as pr_rank\n\tfrom\n\t\trefs_issues_diffs rid\n\t\tleft join issues i on rid.issue_id = i.id\n\t\tleft join pull_request_issues pri on i.id = pri.issue_id\n\t\tleft join pull_requests pr on pri.pull_request_id = pr.id\n\twhere\n\t\tSUBSTRING_INDEX(rid.new_ref_name,':', 3) = '$repo_id'\n\t\tand rid.new_ref_name in (SELECT new_ref_name FROM _last_10_tags)\n\t\tand i.type = 'BUG'\n\torder by i.key\n),\n\n_bug_fixed_count as(\n  SELECT \n    pr_author,\n    count(*) bug_fixed_count\n  FROM _bugs\n  WHERE pr_rank = 1\n  GROUP BY 1\n),\n\n_bug_fixed_count_running_total as(\n  SELECT \n    *, \n    sum(bug_fixed_count) OVER (Order by bug_fixed_count desc) AS running_total\n  FROM \n    _bug_fixed_count\n),\n\n_percentile as(\n  SELECT \n    pr_author,\n    bug_fixed_count,\n    running_total/sum(bug_fixed_count) OVER () AS cumulative_percentage\n  FROM \n    _bug_fixed_count_running_total\n)\n\n\nSELECT \n  count(case when cumulative_percentage <= 0.8 then pr_author else null end)/count(*) as \"% of contributors who fixed 80% of the bugs\"\nFROM _percentile"
    }
   ]
  },
  {
   "title": "4.2 Top 15 contributors in bug-fixing in the last 10 tags",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "-- Get the bug fixer distribution in the last 10 tags\nwith _last_10_tags as(\n  SELECT \n    distinct new_ref_name, old_ref_name\n  FROM \n    refs_commits_diffs\n  WHERE\n\t\tSUBSTRING_INDEX(new_ref_name,':', 3) = '$repo_id'\n\tORDER BY 1 desc\n\tLIMIT 10\n),\n\n_bugs as(\n\tselect \n\t\ti.key, i.type, i.severity, i.title, i.summary,\n\t\tpr.id, pr.author_name as pr_author, pr.created_date,\n\t\trank() over(partition by i.id order by pr.created_date asc) as pr_rank\n\tfrom\n\t\trefs_issues_diffs rid\n\t\tleft join issues i on rid.issue_id = i.id\n\t\tleft join pull_request_issues pri on i.id = pri.issue_id\n\t\tleft join pull_requests pr on pri.pull_request_id = pr.id\n\twhere\n\t\tSUBSTRING_INDEX(rid.new_ref_name,':', 3) = '$repo_id'\n\t\tand rid.new_ref_name in (SELECT new_ref_name FROM _last_10_tags)\n\t\tand i.type = 'BUG'\n\torder by i.key\n)\n\nSELECT \n  pr_author,\n  count(*) bug_fixed_count\nFROM _bugs\nWHERE pr_rank = 1\nGROUP BY 1\nORDER BY 2 desc\nlimit 15"
    }
   ]
  },
  {
   "title": "5.1 Average bug age (day) in history",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Get the avg bug age in history\nselect \n  avg(lead_time_minutes)/1440 as average_bug_age\nfrom issues\nwhere \n  type = 'BUG'\n  and status = 'DONE'"
    }
   ]
  },
  {
   "title": "5.3 Average and 80th bug age (day) in the last 10 tags",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 15, "x": 3, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "-- Get the bug fixer distribution in the last 10 tags\nwith _last_10_tags as(\n  SELECT \n    distinct new_ref_name, old_ref_name\n  FROM \n    refs_commits_diffs\n  WHERE\n\t\tSUBSTRING_INDEX(new_ref_name,':', 3) = '$repo_id'\n\tORDER BY 1 desc\n\tLIMIT 10\n),\n\n_bugs as(\n\tselect distinct\n\t\tSUBSTRING_INDEX(rid.new_ref_name,'refs/', -1) as tag_name,\n\t\ti.id,\n\t\ti.lead_time_minutes\n\tfrom\n\t\trefs_issues_diffs rid\n\t\tleft join issues i on rid.issue_id = i.id\n\t\tleft join pull_request_issues pri on i.id = pri.issue_id\n\twhere\n\t\tSUBSTRING_INDEX(rid.new_ref_name,':', 3) = '$repo_id'\n\t\tand rid.new_ref_name in (SELECT new_ref_name FROM _last_10_tags)\n\t\tand i.type = 'BUG'\n),\n\n_bugs_percentile as(\n  select \n    *,\n    percent_rank() over (partition by tag_name order by lead_time_minutes) as percentile\n  from _bugs order by 1\n),\n\n_avg_bug_age as(\n  select \n    tag_name,\n    avg(lead_time_minutes)/1440 as average_bug_age\n  from _bugs_percentile\n  group by 1\n),\n\n_80th_bug_age as(\n  select \n    tag_name,\n    min(lead_time_minutes)/1440 as \"80th_bug_age\"\n  from _bugs_percentile\n    where percentile >= 0.8\n  group by 1\n)\n\nselect \n  aba.*,\n  eba.80th_bug_age\nfrom \n  _avg_bug_age aba\n  join _80th_bug_age eba on aba.tag_name = eba.tag_name"
    }
   ]
  },
  {
   "title": "5.4 Queue time for all backlog bugs",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Get the avg bug age in history\nwith _avg_bug_age as(\n  select \n    type,\n    avg(lead_time_minutes) as average_bug_age\n  from issues\n  where \n    type = 'BUG'\n    and status = 'DONE'\n  group by 1\n),\n\n\n_bug_queue_time as(\n  select \n    i.id,\n    abg.average_bug_age,\n    TIMESTAMPDIFF(MINUTE,created_date,NOW()) as queue_time,\n    case when TIMESTAMPDIFF(MINUTE,created_date,NOW()) >= average_bug_age then \">=avg_bug_age\" else \"<avg_bug_age\" end as distribution\n  from \n    issues i\n    left join _avg_bug_age abg on i.type = abg.type\n  where\n    i.type = 'BUG'\n    and status != 'DONE'\n)\n\nselect\n  distribution,\n  count(*) as bug_count\nfrom\n  _bug_queue_time\ngroup by 1"
    }
   ]
  },
  {
   "title": "5.2 80th bug age (day) in history",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Get the 80th perccentile bug age in history\nwith _bugs_percentile as(\n  select \n    id,\n    lead_time_minutes,\n    percent_rank() over (order by lead_time_minutes) as percentile\n  from issues\n  where \n    type = 'BUG'\n    and status = 'DONE'\n)\n\nselect \n  min(lead_time_minutes)/1440 as \"80th_bug_age\"\nfrom \n  _bugs_percentile\nwhere \n  percentile >= 0.8\n"
    }
   ]
  },
  {
   "title": "6.1 Work-type distribution (dev_eq) in the last tag",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Get the work-type distribution in the last 10 tags\nwith _last_10_tags as(\n  SELECT \n    distinct new_ref_name, old_ref_name\n  FROM \n    refs_commits_diffs\n  WHERE\n\t\tSUBSTRING_INDEX(new_ref_name,':', 3) = '$repo_id'\n\tORDER BY 1 desc\n\tLIMIT 1\n),\n\n_dev_eq_of_pr as(\n  select\n    SUBSTRING_INDEX(rcd.new_ref_name,'tags/', -1) as tag_name,\n    pr.id as pull_request_id,\n    sum(c.dev_eq) as pr_eloc\n  FROM \n    refs_commits_diffs rcd\n\t\tleft join commits c on rcd.commit_sha = c.sha\n\t\t-- left join pull_request_commits prc on c.sha = prc.commit_sha\n\t\tleft join pull_requests pr on c.sha = pr.merge_commit_sha\n\twhere\n\t\tSUBSTRING_INDEX(rcd.new_ref_name,':', 3) = '$repo_id'\n\t\tand rcd.new_ref_name in (SELECT new_ref_name FROM _last_10_tags)\n\tgroup by 1,2\n),\n\n_pr_issues as(\n  select\n    pri.pull_request_id,\n    pri.issue_id,\n    i.key,\n    i.type,\n    row_number() over(partition by issue_id ORDER by pr.created_date asc) as pr_rank\n  from\n    pull_request_issues pri\n    left join pull_requests pr on pri.pull_request_id = pr.id\n    left join issues i on pri.issue_id = i.id\n  where \n    issue_number != 0\n),\n\n_final_results as(\n  select\n    distinct deop.*, pi.type\n  from \n    _dev_eq_of_pr deop\n    left join _pr_issues pi on deop.pull_request_id = pi.pull_request_id\n  where pi.pr_rank = 1\n  order by 1\n)\n\nSELECT\n  tag_name,\n  case when type != '' then type else 'UNKNOWN' end as type,\n  sum(pr_eloc) as dev_eq\nfrom _final_results\ngroup by 1,2"
    }
   ]
  },
  {
   "title": "6.2 Work-type distribution (dev_eq) in the tag before last",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Get the work-type distribution in the last 10 tags\nwith _last_10_tags as(\n  SELECT \n    distinct new_ref_name, old_ref_name\n  FROM \n    refs_commits_diffs\n  WHERE\n\t\tSUBSTRING_INDEX(new_ref_name,':', 3) = '$repo_id'\n\tORDER BY 1 desc\n\tLIMIT 1,1\n),\n\n_dev_eq_of_pr as(\n  select\n    SUBSTRING_INDEX(rcd.new_ref_name,'tags/', -1) as tag_name,\n    pr.id as pull_request_id,\n    sum(c.dev_eq) as pr_eloc\n  FROM \n    refs_commits_diffs rcd\n\t\tleft join commits c on rcd.commit_sha = c.sha\n\t\t-- left join pull_request_commits prc on c.sha = prc.commit_sha\n\t\tleft join pull_requests pr on c.sha = pr.merge_commit_sha\n\twhere\n\t\tSUBSTRING_INDEX(rcd.new_ref_name,':', 3) = '$repo_id'\n\t\tand rcd.new_ref_name in (SELECT new_ref_name FROM _last_10_tags)\n\tgroup by 1,2\n),\n\n_pr_issues as(\n  select\n    pri.pull_request_id,\n    pri.issue_id,\n    i.key,\n    i.type,\n    row_number() over(partition by issue_id ORDER by pr.created_date asc) as pr_rank\n  from\n    pull_request_issues pri\n    left join pull_requests pr on pri.pull_request_id = pr.id\n    left join issues i on pri.issue_id = i.id\n  where \n    issue_number != 0\n),\n\n_final_results as(\n  select\n    distinct deop.*, pi.type\n  from \n    _dev_eq_of_pr deop\n    left join _pr_issues pi on deop.pull_request_id = pi.pull_request_id\n  where pi.pr_rank = 1\n  order by 1\n)\n\nSELECT\n  tag_name,\n  case when type != '' then type else 'UNKNOWN' end as type,\n  sum(pr_eloc) as dev_eq\nfrom _final_results\ngroup by 1,2"
    }
   ]
  },
  {
   "title": "6.3 Work-type distribution (dev_eq) in the 2nd tag before last",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Get the work-type distribution in the last 10 tags\nwith _last_10_tags as(\n  SELECT \n    distinct new_ref_name, old_ref_name\n  FROM \n    refs_commits_diffs\n  WHERE\n\t\tSUBSTRING_INDEX(new_ref_name,':', 3) = '$repo_id'\n\tORDER BY 1 desc\n\tLIMIT 2,1\n),\n\n_dev_eq_of_pr as(\n  select\n    SUBSTRING_INDEX(rcd.new_ref_name,'tags/', -1) as tag_name,\n    pr.id as pull_request_id,\n    sum(c.dev_eq) as pr_eloc\n  FROM \n    refs_commits_diffs rcd\n\t\tleft join commits c on rcd.commit_sha = c.sha\n\t\t-- left join pull_request_commits prc on c.sha = prc.commit_sha\n\t\tleft join pull_requests pr on c.sha = pr.merge_commit_sha\n\twhere\n\t\tSUBSTRING_INDEX(rcd.new_ref_name,':', 3) = '$repo_id'\n\t\tand rcd.new_ref_name in (SELECT new_ref_name FROM _last_10_tags)\n\tgroup by 1,2\n),\n\n_pr_issues as(\n  select\n    pri.pull_request_id,\n    pri.issue_id,\n    i.key,\n    i.type,\n    row_number() over(partition by issue_id ORDER by pr.created_date asc) as pr_rank\n  from\n    pull_request_issues pri\n    left join pull_requests pr on pri.pull_request_id = pr.id\n    left join issues i on pri.issue_id = i.id\n  where \n    issue_number != 0\n),\n\n_final_results as(\n  select\n    distinct deop.*, pi.type\n  from \n    _dev_eq_of_pr deop\n    left join _pr_issues pi on deop.pull_request_id = pi.pull_request_id\n  where pi.pr_rank = 1\n  order by 1\n)\n\nSELECT\n  tag_name,\n  case when type != '' then type else 'UNKNOWN' end as type,\n  sum(pr_eloc) as dev_eq\nfrom _final_results\ngroup by 1,2"
    }
   ]
  },
  {
   "title": "7.1 % of contributors who contributed 80% of dev_eq in the last 10 tags",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Get the bug fixer distribution in the last 10 tags\nwith _last_10_tags as(\n  SELECT \n    distinct new_ref_name, old_ref_name\n  FROM \n    refs_commits_diffs\n  WHERE\n\t\tSUBSTRING_INDEX(new_ref_name,':', 3) = '$repo_id'\n\tORDER BY 1 desc\n\tLIMIT 10\n),\n\n_author_eloc as(\n  SELECT \n  \tc.author_name,\n    sum(c.dev_eq) total_dev_eq\n  FROM \n    refs_commits_diffs rcf\n    left join commits c on rcf.commit_sha = c.dev_eq\n  WHERE\n  \trcf.new_ref_name in (SELECT new_ref_name FROM _last_10_tags)\n  GROUP BY 1\n),\n\n_author_eloc_running_total as(\n  SELECT \n    *, \n    sum(total_dev_eq) OVER (Order by total_dev_eq desc) AS running_total\n  FROM \n    _author_eloc\n),\n\n_percentile as(\n  SELECT \n    author_name,\n    total_dev_eq,\n    running_total/sum(total_dev_eq) OVER () AS cumulative_percentage\n  FROM \n    _author_eloc_running_total\n)\n\n\nSELECT \n  count(case when cumulative_percentage <= 0.8 then author_name else null end)/count(*) as \"contributors who contributed 80% of dev_eq\"\nFROM _percentile"
    }
   ]
  },
  {
   "title": "7.2 Dev Equivalent per commit author (top 15) in last 10 tags",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 42 },
   "targets": [
    {
     "rawSql": "with _last_10_tags as(\n  SELECT \n    distinct new_ref_name, old_ref_name\n  FROM \n    refs_commits_diffs\n  WHERE\n\t\tSUBSTRING_INDEX(new_ref_name,':', 3) = '$repo_id'\n\tORDER BY 1 desc\n\tLIMIT 10\n)\n\n\nSELECT \n\tc.author_name,\n  sum(c.dev_eq) total_dev_eq\nFROM \n  refs_commits_diffs rcf\n  left join commits c on rcf.commit_sha = c.dev_eq\nWHERE\n\trcf.new_ref_name in (SELECT new_ref_name FROM _last_10_tags)\nGROUP BY 1\nORDER BY 2 desc\nlimit 15"
    }
   ]
  }
 ]
}