{
 "title": "Sonarqube By Teams",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project_id",
    "label": "Teams",
    "query": "select distinct name from projects"
   }
  ]
 },
 "panels": [
  { "title": "Reliability & Security", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Reliability",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bugs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "devlake_prod",
     "rawSql": "-- SELECT row_id from devlake_prod.project_mapping WHERE `table`=\"cq_projects\" and project_name = \"2W\"\n-- select * from devlake_prod.cq_projects;\n  -- SELECT row_id from devlake_prod.project_mapping WHERE `table`=\"cq_projects\" and project_name = \"2W\" \nSELECT COUNT(DISTINCT i.id) AS \"Bugs\"\nFROM devlake_prod.cq_issues i\nJOIN devlake_prod.project_mapping pm ON i.project_key = pm.row_id\nWHERE pm.`table` = \"cq_projects\"\n  AND pm.project_name IN (${project_id})\n  AND i.type = \"BUG\"\n  AND i.severity IN (\"\", \"MAJOR\", \"INFO\", \"CRITICAL\", \"MINOR\", \"BLOCKER\");\n\n-- SELECT count(distinct id) as \"Bugs\"\n--  from devlake_prod.cq_issues IN (\n--   SELECT row_id from devlake_prod.project_mapping WHERE `table`=\"cq_projects\" and project_name = \"2W\" \n-- ) and type = \"BUG\"\n--   and severity in (\"\",\"MAJOR\",\"INFO\",\"CRITICAL\",\"MINOR\",\"BLOCKER\")\n  "
    }
   ]
  },
  {
   "title": "Security",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "vulnerabilities" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "devlake_prod",
     "rawSql": "SELECT COUNT(DISTINCT i.id) AS \"Vulnerabilities\"\nFROM devlake_prod.cq_issues i\nJOIN devlake_prod.project_mapping pm ON i.project_key = pm.row_id\nWHERE pm.`table` = \"cq_projects\"\n  AND pm.project_name IN (${project_id})\n  AND i.type = \"VULNERABILITY\"\n  AND i.severity IN (\"\", \"MAJOR\", \"INFO\", \"CRITICAL\", \"MINOR\", \"BLOCKER\");"
    }
   ]
  },
  {
   "title": "Security Hotspots",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "hotspots" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "devlake_prod",
     "rawSql": "SELECT COUNT(DISTINCT i.id) AS \"hotsports\"\nFROM devlake_prod.cq_issues i\nJOIN devlake_prod.project_mapping pm ON i.project_key = pm.row_id\nWHERE pm.`table` = \"cq_projects\"\n  AND pm.project_name IN (${project_id})\n  AND i.type = \"HOTSPOTS\"\n  AND i.severity IN (\"\", \"MAJOR\", \"INFO\", \"CRITICAL\", \"MINOR\", \"BLOCKER\")\n  and i.status in (\"TO_REVIEW\", \"ACKNOWLEDGED\")\n"
    }
   ]
  },
  { "title": "Test & Maintainability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Lines To Cover",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "devlake_prod",
     "rawSql": "SELECT CONCAT(ROUND((sum(lines_to_cover) - sum(uncovered_lines)) / sum(lines_to_cover) * 100, 1), \"% \", \"Coverage on \", ROUND(sum(lines_to_cover) / 1000, 0), \"k Lines to cover\")\n AS \"Test coverage\"\nFROM devlake_prod.cq_file_metrics i\nJOIN devlake_prod.project_mapping pm ON i.project_key = pm.row_id\nWHERE pm.`table` = \"cq_projects\"\n  AND pm.project_name IN (${project_id})\n\n\n\n\n "
    }
   ]
  },
  {
   "title": "Maintainability - Debt",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "devlake_prod",
     "rawSql": "SELECT concat(FLOOR(SUM(debt)/8/60), \" day(s) \", FLOOR((SUM(debt)%480)/60), \" hour(s) \") AS 'Debt'\nFROM devlake_prod.cq_issues i\nJOIN devlake_prod.project_mapping pm ON i.project_key = pm.row_id\nWHERE pm.`table` = \"cq_projects\"\n  AND pm.project_name IN (${project_id})\n  AND i.type = \"CODE_SMELL\"\n  AND i.severity IN (\"\", \"MAJOR\", \"INFO\", \"CRITICAL\", \"MINOR\", \"BLOCKER\")\n  and i.status in (\"OPEN\")\n\n\n  "
    }
   ]
  },
  {
   "title": "Maintainability - Code Smells",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "code smells" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\tCOUNT(distinct id) as 'Code Smells'\nFROM devlake_prod.cq_issues i\nJOIN devlake_prod.project_mapping pm ON i.project_key = pm.row_id\nWHERE pm.`table` = \"cq_projects\"\n  AND pm.project_name IN (${project_id})\n  and i.type = 'CODE_SMELL'\n  and i.status = \"OPEN\""
    }
   ]
  },
  { "title": "Duplication & Code", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Duplicated Blocks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "devlake_prod",
     "rawSql": "SELECT\n  sum(duplicated_blocks)\nFROM devlake_prod.cq_file_metrics i\nJOIN devlake_prod.project_mapping pm ON i.project_key = pm.row_id\nWHERE pm.`table` = \"cq_projects\"\n  AND pm.project_name IN (${project_id})\n\n"
    }
   ]
  },
  {
   "title": "Duplicated Lines",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "devlake_prod",
     "rawSql": "SELECT CONCAT(ROUND(sum(duplicated_lines) / sum(num_of_lines) * 100, 1), '% ', 'Duplications on ', ROUND(sum(ncloc) / 1000, 0),'k Lines')\nFROM devlake_prod.cq_file_metrics i\nJOIN devlake_prod.project_mapping pm ON i.project_key = pm.row_id\nWHERE pm.`table` = \"cq_projects\"\nAND pm.project_name IN (${project_id})\n"
    }
   ]
  }
 ]
}