{
 "title": "Team Weekly",
 "tags": [ "Developer" ],
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "PR review count in the last 30 days",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT \n  a.user_name as reviewer,\n  COUNT(DISTINCT prc.pull_request_id) as total_prs_reviewed\nFROM \n  pull_request_comments prc\n  JOIN accounts a ON prc.account_id = a.id\n  JOIN pull_requests pr ON prc.pull_request_id = pr.id\n  JOIN project_mapping pm ON pr.base_repo_id = pm.row_id AND pm.table = 'repos'\nWHERE \n  prc.created_date >= DATE_SUB(CURDATE(), INTERVAL 30 DAY)\n  AND pm.project_name in ('Agendrix-web')\n  AND a.user_name IS NOT NULL\n  AND a.user_name NOT IN ('agendrix-bot')\nGROUP BY \n  prc.account_id, a.user_name, a.full_name\nORDER BY \n  total_prs_reviewed DESC;"
    }
   ]
  },
  {
   "title": "Avg time to merge for the last 30 days (days)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "days" } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT \n  pr.author_name as developer,\n  AVG(TIMESTAMPDIFF(MINUTE, pr.created_date, pr.merged_date) / 1440) as avg_pr_time_to_merge_days\nFROM \n  pull_requests pr\n  JOIN project_mapping pm ON pr.base_repo_id = pm.row_id AND pm.table = 'repos'\nWHERE \n  pr.merged_date IS NOT NULL\n  AND pr.merged_date >= DATE_SUB(CURDATE(), INTERVAL 30 DAY)\n  AND pr.author_name NOT IN ('agendrix-bot')\nGROUP BY \n  pr.author_name\nHAVING \n  COUNT(DISTINCT pr.id) >= 1  -- Only include developers with at least 1 merged PR\nORDER BY \n  avg_pr_time_to_merge_days asc;"
    }
   ]
  },
  {
   "title": "PRs Merged over Month",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 17 },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "with _merged_prs as(\n  select\n    DATE_ADD(date(pr.merged_date), INTERVAL -DAY(date(pr.merged_date))+1 DAY) as time,\n    count(distinct pr.id) as pr_merged_count\n  from\n    pull_requests pr\n    join project_mapping pm on pr.base_repo_id = pm.row_id and pm.table = 'repos' \n  where\n    pm.project_name in ('Agendrix-web')\n    and pr.merged_date is not null\n    and $__timeFilter(pr.merged_date)\n    and pr.merged_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n  group by time\n)\n\nselect\n  date_format(time,'%M %Y') as month,\n  pr_merged_count\nfrom _merged_prs\norder by time asc"
    }
   ]
  },
  {
   "title": "PR Time to merge",
   "type": "barchart",
   "description": "PR Time to Merge = PR Pickup Time + PR Review Time",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "days" } },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "with _merged_prs as(\n  \n  select\n    DATE_ADD(date(pr.created_date), INTERVAL -DAY(date(pr.created_date))+1 DAY) as time,\n    AVG(TIMESTAMPDIFF(MINUTE, pr.created_date, pr.merged_date) / 1440) as pr_time_to_merge_in_days\n  from\n    pull_requests pr\n    join project_mapping pm on pr.base_repo_id = pm.row_id and pm.table = 'repos' \n  where\n    pm.project_name in ('Agendrix-web') and\n    pr.merged_date is not null\n    and $__timeFilter(pr.created_date)\n    and pr.created_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n  group by time\n)\n\nselect\n  date_format(time,'%M %Y') as month,\n  pr_time_to_merge_in_days\nfrom _merged_prs\norder by time asc"
    }
   ]
  }
 ]
}