{
 "title": "Weekly Report",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "select distinct name from projects"
   },
   {
    "name": "title_value",
    "label": "TitleValue",
    "query": "SELECT \n  CASE \n    WHEN dora_report = '2023' THEN \"Failed Deployment Recovery Time\"\n    WHEN dora_report = '2021' THEN \"Median Time to Restore Service\"\n    ELSE NULL \n  END AS title_value\nFROM dora_benchmarks\nWHERE dora_report = '${dora_report:raw}'"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Introduction",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "- This dashboard shows all the key metrics in the weekly report."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "PR Cycle Time",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "with _deployed_prs as(\n  SELECT\n    pr.id,\n    cdc.finished_date as pr_deployed_date,\n    -- convert null to 0 if a PR has no cycle_time to make sure cycle_time equals the sum of the four metrics below\n\t\tcoalesce(prm.pr_cycle_time/60,0) as cycle_time\n  FROM pull_requests pr\n    left join project_pr_metrics prm on pr.id = prm.id\n    join project_mapping pm on pr.base_repo_id = pm.row_id and pm.table = 'repos' \n    join cicd_deployment_commits cdc on prm.deployment_commit_id = cdc.id\n  WHERE\n    -- filter the deployed PRs\n    cdc.finished_date >= curdate() - INTERVAL WEEKDAY(curdate()) + 7 DAY - INTERVAL 6 MONTH\n    and pm.project_name in (${project})\n  GROUP BY 1,2,3\n)\n\nSELECT\n\t'Last week' as period,\n\tIFNULL(avg(cycle_time),0.00001) as avg_cycle_time_in_hour_per_week\nFROM \n\t_deployed_prs\nWHERE \n\tpr_deployed_date >= curdate() - INTERVAL WEEKDAY(curdate()) + 7 DAY \n\tand pr_deployed_date < curdate() - INTERVAL WEEKDAY(curdate()) DAY\n\nunion\n\nSELECT \n\t'3 months before last week' as period,\n\tIFNULL(avg(cycle_time), 0.00001) as avg_cycle_time_in_hour_per_week\nFROM \n\t_deployed_prs\nWHERE \n\tpr_deployed_date >= curdate() - INTERVAL WEEKDAY(curdate()) + 7 DAY - INTERVAL 6 MONTH \n\tand pr_deployed_date < curdate() - INTERVAL WEEKDAY(curdate()) + 7 DAY \n"
    }
   ]
  },
  {
   "title": "PR Throughput",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "with _deployed_prs as(\n  SELECT\n    pr.id,\n    cdc.finished_date as pr_deployed_date,\n    -- convert null to 0 if a PR has no cycle_time to make sure cycle_time equals the sum of the four metrics below\n\t\tcoalesce(prm.pr_cycle_time/60,0) as cycle_time\n  FROM pull_requests pr\n    left join project_pr_metrics prm on pr.id = prm.id\n    join project_mapping pm on pr.base_repo_id = pm.row_id and pm.table = 'repos' \n    join cicd_deployment_commits cdc on prm.deployment_commit_id = cdc.id\n  WHERE\n    -- filter the deployed PRs\n    pr.merged_date is not null and prm.pr_cycle_time is not null and cdc.result = 'SUCCESS' and cdc.environment = 'PRODUCTION' \n    and cdc.finished_date >= curdate() - INTERVAL WEEKDAY(curdate()) + 7 DAY - INTERVAL 6 MONTH\n    and pm.project_name in (${project})\n  GROUP BY 1,2,3\n)\n\nSELECT\n\t'Last week' as period,\n\tcase when count(distinct id) = 0 then 0.00001 else count(distinct id) end as avg_pr_count_per_week\nFROM \n\t_deployed_prs\nWHERE \n\tpr_deployed_date >= curdate() - INTERVAL WEEKDAY(curdate()) + 7 DAY \n\tand pr_deployed_date < curdate() - INTERVAL WEEKDAY(curdate()) DAY\n\nunion\n\nSELECT \n\t'3 months before last week' as period,\n\tcount(distinct id)/(DATEDIFF(curdate() - INTERVAL WEEKDAY(curdate())+7 DAY, curdate() - INTERVAL WEEKDAY(curdate()) + 7 DAY - INTERVAL 3 MONTH))*7 as avg_pr_count_per_week\nFROM \n\t_deployed_prs\nWHERE \n\tpr_deployed_date >= curdate() - INTERVAL WEEKDAY(curdate()) + 7 DAY - INTERVAL 6 MONTH \n\tand pr_deployed_date < curdate() - INTERVAL WEEKDAY(curdate()) + 7 DAY \n"
    }
   ]
  },
  {
   "title": "Deployment frequency",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "-- Metric 1: Number of deployments per month\nwith _deployments as(\n-- When deploying multiple commits in one pipeline, GitLab and BitBucket may generate more than one deployment. However, DevLake consider these deployments as ONE production deployment and use the last one's finished_date as the finished date.\n\t\tSELECT\n\t\t\tcdc.cicd_deployment_id,\n\t\t\tmax(cdc.finished_date) as deployment_finished_date\n\t\tFROM cicd_deployment_commits cdc\n\t\tJOIN project_mapping pm on cdc.cicd_scope_id = pm.row_id and pm.`table` = 'cicd_scopes'\n\t\tWHERE\n\t\t\tpm.project_name in (${project})\n\t\t\tand cdc.result = 'SUCCESS'\n\t\t\tand cdc.environment = 'PRODUCTION'\n\t\tGROUP BY 1\n\t\tHAVING max(cdc.finished_date) >= curdate() - INTERVAL WEEKDAY(curdate()) + 7 DAY - INTERVAL 6 MONTH\n)\n\nSELECT\n\t'Last week' as period,\n\tcase when count(cicd_deployment_id) = 0 then 0.0001 else count(cicd_deployment_id) end as avg_deployment_count_per_week\nFROM \n\t_deployments\nWHERE \n\tdeployment_finished_date >= curdate() - INTERVAL WEEKDAY(curdate()) + 7 DAY \n\tand deployment_finished_date < curdate() - INTERVAL WEEKDAY(curdate()) DAY\n\nunion\n\nSELECT \n\t'3 months before last week' as period,\n\tround(count(cicd_deployment_id)/(DATEDIFF(curdate() - INTERVAL WEEKDAY(curdate())+7 DAY, curdate() - INTERVAL WEEKDAY(curdate()) + 7 DAY - INTERVAL 3 MONTH))*7, 1) as avg_deployment_count_per_week\nFROM \n\t_deployments\nWHERE \n\tdeployment_finished_date >= curdate() - INTERVAL WEEKDAY(curdate()) + 7 DAY - INTERVAL 6 MONTH \n\tand deployment_finished_date < curdate() - INTERVAL WEEKDAY(curdate()) + 7 DAY \n"
    }
   ]
  },
  {
   "title": "Change Failure Rate",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "-- Metric 3: change failure rate per month\nwith _deployments as (\n-- When deploying multiple commits in one pipeline, GitLab and BitBucket may generate more than one deployment. However, DevLake consider these deployments as ONE production deployment and use the last one's finished_date as the finished date.\n\tSELECT\n\t\tcdc.cicd_deployment_id as deployment_id,\n\t\tmax(cdc.finished_date) as deployment_finished_date\n\tFROM \n\t\tcicd_deployment_commits cdc\n\t\tJOIN project_mapping pm on cdc.cicd_scope_id = pm.row_id and pm.`table` = 'cicd_scopes'\n\tWHERE\n\t\tpm.project_name in (${project})\n\t\tand cdc.result = 'SUCCESS'\n\t\tand cdc.environment = 'PRODUCTION'\n\tGROUP BY 1\n\tHAVING max(cdc.finished_date) >= curdate() - INTERVAL WEEKDAY(curdate()) + 7 DAY - INTERVAL 6 MONTH\n),\n\n_failure_caused_by_deployments as (\n-- calculate the number of incidents caused by each deployment\n\tSELECT\n\t\td.deployment_id,\n\t\td.deployment_finished_date,\n\t\tcount(distinct case when i.type = 'INCIDENT' then d.deployment_id else null end) as has_incident\n\tFROM\n\t\t_deployments d\n\t\tleft join project_issue_metrics pim on d.deployment_id = pim.deployment_id\n\t\tleft join issues i on pim.id = i.id\n\tGROUP BY 1,2\n)\n\nSELECT\n\t'Last week' as period,\n\tIFNULL(sum(has_incident)/count(deployment_id), 0.00001) as change_failure_rate\nFROM _failure_caused_by_deployments\nWHERE deployment_finished_date >= curdate() - INTERVAL WEEKDAY(curdate()) + 7 DAY and deployment_finished_date < curdate() - INTERVAL WEEKDAY(curdate()) DAY\n\nunion\n\nSELECT  \n\t'3 months before last week' as period,\n\tIFNULL(sum(has_incident)/count(deployment_id), 0) as change_failure_rate\nFROM _failure_caused_by_deployments\nWHERE deployment_finished_date >= curdate() - INTERVAL WEEKDAY(curdate()) + 7 DAY - INTERVAL 6 MONTH and deployment_finished_date < curdate() - INTERVAL WEEKDAY(curdate()) + 7 DAY\n"
    }
   ]
  }
 ]
}