{
 "title": "Bamboo",
 "tags": [ "Data Source Dashboard" ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "plan_id",
    "label": "Plan Name",
    "query": "SELECT name || '--' || id AS text FROM cicd_scopes WHERE id::text LIKE 'bamboo%'"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Introduction",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "- Use Cases: This dashboard shows the basic CI/CD metrics from Bamboo, such as [Build Count](https://devlake.apache.org/docs/Metrics/BuildCount), [Build Duration](https://devlake.apache.org/docs/Metrics/BuildDuration) and [Build Success Rate](https://devlake.apache.org/docs/Metrics/BuildSuccessRate). A build in Bamboo is an execution of a Bamboo Plan.\n- Data Source Required: Bamboo"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "1. Total Number of Successful Builds [Selected Time Range]",
   "type": "stat",
   "description": "Number of builds executed in the selected time range",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT id) FROM cicd_pipelines WHERE $__timeFilter(finished_date) AND result = 'SUCCESS' AND id::text LIKE '%bamboo%' AND ('${plan_id:csv}' = '' OR cicd_scope_id::text = ANY(ARRAY[${plan_id:singlequote}]::text[])) AND /* the following condition will remove the month with incomplete data */ finished_date >= $__timeFrom()::timestamp + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST($__timeFrom() AS DATE)) + 1) + INTERVAL '1 MONTH'"
    }
   ]
  },
  {
   "title": "2. Mean Build Success Rate",
   "type": "stat",
   "description": "Number of successful builds / Number of total builds",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CAST(1.0 * COUNT(CASE WHEN result = 'SUCCESS' THEN id ELSE NULL END) AS NUMERIC) / NULLIF(COUNT(DISTINCT id), 0) FROM cicd_pipelines WHERE $__timeFilter(finished_date) AND id::text LIKE '%bamboo%' AND ('${plan_id:csv}' = '' OR cicd_scope_id::text = ANY(ARRAY[${plan_id:singlequote}]::text[])) AND /* the following condition will remove the month with incomplete data */ finished_date >= $__timeFrom()::timestamp + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST($__timeFrom() AS DATE)) + 1) + INTERVAL '1 MONTH'"
    }
   ]
  },
  {
   "title": "3. Total Build Result Distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT result, COUNT(DISTINCT id) AS build_count FROM cicd_pipelines WHERE $__timeFilter(finished_date) AND id::text LIKE '%bamboo%' AND ('${plan_id:csv}' = '' OR cicd_scope_id::text = ANY(ARRAY[${plan_id:singlequote}]::text[])) AND /* the following condition will remove the month with incomplete data */ finished_date >= $__timeFrom()::timestamp + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST($__timeFrom() AS DATE)) + 1) + INTERVAL '1 MONTH' GROUP BY 1 ORDER BY 2 DESC NULLS LAST"
    }
   ]
  },
  {
   "title": "4. Mean Build Duration in Minutes",
   "type": "stat",
   "description": "Number of successful builds / Number of total builds",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT AVG(CAST(duration_sec AS NUMERIC) / NULLIF(60, 0)) AS duration_in_minutes FROM cicd_pipelines WHERE $__timeFilter(finished_date) AND id::text LIKE '%bamboo%' AND ('${plan_id:csv}' = '' OR cicd_scope_id::text = ANY(ARRAY[${plan_id:singlequote}]::text[])) AND /* the following condition will remove the month with incomplete data */ finished_date >= $__timeFrom()::timestamp + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST($__timeFrom() AS DATE)) + 1) + INTERVAL '1 MONTH'"
    }
   ]
  },
  {
   "title": "1.1 Total Number of Successful Builds [Each Month]",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "WITH _builds AS (SELECT CAST(finished_date AS DATE) + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST(finished_date AS DATE)) + 1) AS time, COUNT(DISTINCT id) AS build_count FROM cicd_pipelines WHERE $__timeFilter(finished_date) AND result = 'SUCCESS' AND id::text LIKE '%bamboo%' AND ('${plan_id:csv}' = '' OR cicd_scope_id::text = ANY(ARRAY[${plan_id:singlequote}]::text[])) AND /* the following condition will remove the month with incomplete data */ finished_date >= $__timeFrom()::timestamp + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST($__timeFrom() AS DATE)) + 1) + INTERVAL '1 MONTH' GROUP BY 1) SELECT TO_CHAR(CAST(time AS TIMESTAMP), 'FMMonth YYYY') AS month, build_count AS \"Build Count\" FROM _builds ORDER BY time NULLS FIRST"
    }
   ]
  },
  {
   "title": "2.1 Build Success Rate [Each Month]",
   "type": "barchart",
   "description": "1. Mean Build success rate over time.\n2. The builds being calculated are filtered by \"build starting time\" (time filter at the upper-right corner) and \"Jira board\" (\"Choose Board\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "WITH _build_success_rate AS (SELECT CAST(finished_date AS DATE) + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST(finished_date AS DATE)) + 1) AS time, result, id FROM cicd_pipelines WHERE $__timeFilter(finished_date) AND id::text LIKE '%bamboo%' AND ('${plan_id:csv}' = '' OR cicd_scope_id::text = ANY(ARRAY[${plan_id:singlequote}]::text[])) AND /* the following condition will remove the month with incomplete data */ finished_date >= $__timeFrom()::timestamp + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST($__timeFrom() AS DATE)) + 1) + INTERVAL '1 MONTH' GROUP BY \"time\", \"result\", id) SELECT TO_CHAR(CAST(time AS TIMESTAMP), 'FMMonth YYYY') AS month, CAST(1.0 * SUM(CASE WHEN result = 'SUCCESS' THEN 1 ELSE 0 END) AS NUMERIC) / NULLIF(COUNT(*), 0) AS \"Build Success Rate\" FROM _build_success_rate GROUP BY time ORDER BY time NULLS FIRST"
    }
   ]
  },
  {
   "title": "3.1 Number of Successful and Failed Builds [Each Month]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT CAST(finished_date AS DATE) + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST(finished_date AS DATE)) + 1) AS time, COUNT(DISTINCT CASE WHEN result = 'SUCCESS' THEN id ELSE NULL END) AS successful_build_count, COUNT(DISTINCT CASE WHEN result <> 'SUCCESS' THEN id ELSE NULL END) AS failed_build_count FROM cicd_pipelines WHERE $__timeFilter(finished_date) AND id::text LIKE '%bamboo%' AND ('${plan_id:csv}' = '' OR cicd_scope_id::text = ANY(ARRAY[${plan_id:singlequote}]::text[])) AND /* the following condition will remove the month with incomplete data */ finished_date >= $__timeFrom()::timestamp + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST($__timeFrom() AS DATE)) + 1) + INTERVAL '1 MONTH' GROUP BY 1"
    }
   ]
  },
  {
   "title": "4.1 Mean Build Duration in Minutes [Each Month]",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "WITH _builds AS (SELECT CAST(finished_date AS DATE) + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST(finished_date AS DATE)) + 1) AS time, AVG(duration_sec) AS mean_duration_sec FROM cicd_pipelines WHERE $__timeFilter(finished_date) AND id::text LIKE '%bamboo%' AND ('${plan_id:csv}' = '' OR cicd_scope_id::text = ANY(ARRAY[${plan_id:singlequote}]::text[])) AND /* the following condition will remove the month with incomplete data */ finished_date >= $__timeFrom()::timestamp + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST($__timeFrom() AS DATE)) + 1) + INTERVAL '1 MONTH' GROUP BY 1) SELECT TO_CHAR(CAST(time AS TIMESTAMP), 'FMMonth YYYY') AS month, CAST(mean_duration_sec AS NUMERIC) / NULLIF(60, 0) AS mean_duration_minutes FROM _builds ORDER BY time NULLS FIRST"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 27 },
   "options": {
    "content": "<br/>\n\nThis dashboard is created based on this [data schema](https://devlake.apache.org/docs/DataModels/DevLakeDomainLayerSchema). Want to add more metrics? Please follow the [guide](https://devlake.apache.org/docs/Configuration/Dashboards/GrafanaUserGuide)."
   },
   "targets": [
    {}
   ]
  }
 ]
}