{
 "title": "DORA (by Team)",
 "tags": [ "Engineering Leads Dashboard" ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "team",
    "label": "Team",
    "query": "SELECT DISTINCT name FROM teams"
   },
   {
    "name": "dora_report",
    "label": "DORA Report",
    "query": "SELECT dora_report FROM dora_benchmarks"
   },
   {
    "name": "title_value",
    "label": "TitleValue",
    "query": "SELECT CASE WHEN dora_report = '2023' THEN 'Failed Deployment Recovery Time' WHEN dora_report = '2021' THEN 'Median Time to Restore Service' ELSE NULL END AS title_value FROM dora_benchmarks WHERE dora_report = '${dora_report:raw}'"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Introduction",
   "type": "text",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "- See [how to config](https://devlake.apache.org/docs/DORA) this dashboard\n- Data Sources Required: \n  - `Deployments` from Jenkins, GitLab CI, GitHub Action, webhook, etc. \n  - `Pull Requests` from GitHub PRs, GitLab MRs, BitBucket PRs, Azure DevOps PRs, etc.\n  - `Incidents` from Jira issues, GitHub issues, TAPD issues, PagerDuty Incidents, etc. \n- Transformation Required: Define `deployments` and `incidents` in [data transformations](https://devlake.apache.org/docs/Configuration/Tutorial#step-3---add-transformations-optional) while configuring the blueprint of a project.\n- You can validate/debug this dashboard with the [DORA validation dashboard](/grafana/d/KGkUnV-Vz/dora-dashboard-validation) \n- You also need to do [team configuration](https://devlake.apache.org/docs/Configuration/TeamConfiguration) to use this dashboard. \n- DORA benchmarks vary in different years. You can switch the benchmarks to change them.\n- In DORA's official report in 2023, metric 'failed deployment recovery time' has replaced 'MTTR'.\n- How does this work? \n  - Gets the author of the specific commit and then navigates to the team the user belongs to. \n  - Gets the team from the PR's author. \n  - Gets the team from the commit author."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Overall DORA Metrics",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "/* Metric 1: Deployment Frequency */ WITH last_few_calendar_months AS (/* construct the last few calendar months within the selected time period in the top-right corner */ SELECT CAST(($__timeTo()::timestamp - INTERVAL '1 day') AS DATE) AS day FROM (SELECT 0 AS \"H\" UNION ALL SELECT 100 UNION ALL SELECT 200 UNION ALL SELECT 300) AS \"H\" CROSS JOIN (SELECT 0 AS \"T\" UNION ALL SELECT 10 UNION ALL SELECT 20 UNION ALL SELECT 30 UNION ALL SELECT 40 UNION ALL SELECT 50 UNION ALL SELECT 60 UNION ALL SELECT 70 UNION ALL SELECT 80 UNION ALL SELECT 90) AS \"T\" CROSS JOIN (SELECT 0 AS \"U\" UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS \"U\" WHERE ($__timeTo()::timestamp - INTERVAL '1 day') > $__timeFrom()), _production_deployment_days AS (/* When deploying multiple commits in one pipeline, GitLab and BitBucket may generate more than one deployment. However, DevLake consider these deployments as ONE production deployment and use the last one's finished_date as the finished date. */ SELECT cdc.cicd_deployment_id AS deployment_id, MAX(CAST(cdc.finished_date AS DATE)) AS day FROM cicd_deployment_commits AS cdc JOIN commits AS c ON cdc.commit_sha = c.sha JOIN user_accounts AS ua ON c.author_id = ua.account_id JOIN users AS u ON ua.user_id = u.id JOIN team_users AS tu ON u.id = tu.user_id JOIN teams AS t ON tu.team_id = t.id JOIN project_mapping AS pm ON cdc.cicd_scope_id = pm.row_id AND pm.\"table\" = 'cicd_scopes' WHERE ('${team:csv}' = '' OR t.name::text = ANY(ARRAY[${team:singlequote}]::text[])) AND cdc.result = 'SUCCESS' AND cdc.environment = 'PRODUCTION' GROUP BY 1), _days_weekly_deploy AS (/* calculate the number of deployment days every week */ SELECT CAST(last_few_calendar_months.day + -(EXTRACT(ISODOW FROM last_few_calendar_months.day) - 1) * INTERVAL '1 day' AS DATE) AS week, MAX(CASE WHEN NOT _production_deployment_days.day IS NULL THEN 1 ELSE 0 END) AS weeks_deployed, COUNT(DISTINCT _production_deployment_days.day) AS days_deployed FROM last_few_calendar_months LEFT JOIN _production_deployment_days ON _production_deployment_days.day = last_few_calendar_months.day GROUP BY week), _days_monthly_deploy AS (/* calculate the number of deployment days every month */ SELECT CAST(last_few_calendar_months.day + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST(last_few_calendar_months.day AS DATE)) + 1) AS DATE) AS month, MAX(CASE WHEN NOT _production_deployment_days.day IS NULL THEN 1 ELSE NULL END) AS months_deployed, COUNT(DISTINCT _production_deployment_days.day) AS days_deployed FROM last_few_calendar_months LEFT JOIN _production_deployment_days ON _production_deployment_days.day = last_few_calendar_months.day GROUP BY month), _days_six_months_deploy AS (SELECT month, SUM(days_deployed) OVER (ORDER BY month NULLS FIRST ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS days_deployed_per_six_months, COUNT(months_deployed) OVER (ORDER BY month NULLS FIRST ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS months_deployed_count, ROW_NUMBER() OVER (PARTITION BY ((EXTRACT(YEAR FROM CAST(month AS TIMESTAMP)) * 12 + EXTRACT(MONTH FROM CAST(month AS TIMESTAMP))) / 6) ORDER BY month DESC NULLS LAST) AS rn FROM _days_monthly_deploy), _median_number_of_deployment_days_per_week_ranks AS (SELECT *, PERCENT_RANK() OVER (ORDER BY days_deployed NULLS FIRST) AS ranks FROM _days_weekly_deploy), _median_number_of_deployment_days_per_week AS (SELECT MAX(days_deployed) AS median_number_of_deployment_days_per_week FROM _median_number_of_deployment_days_per_week_ranks WHERE ranks <= 0.5), _median_number_of_deployment_days_per_month_ranks AS (SELECT *, PERCENT_RANK() OVER (ORDER BY days_deployed NULLS FIRST) AS ranks FROM _days_monthly_deploy), _median_number_of_deployment_days_per_month AS (SELECT MAX(days_deployed) AS median_number_of_deployment_days_per_month FROM _median_number_of_deployment_days_per_month_ranks WHERE ranks <= 0.5), _days_per_six_months_deploy_by_filter AS (SELECT month, days_deployed_per_six_months, months_deployed_count FROM _days_six_months_deploy WHERE rn % 6 = 1), _median_number_of_deployment_days_per_six_months_ranks AS (SELECT *, PERCENT_RANK() OVER (ORDER BY days_deployed_per_six_months NULLS FIRST) AS ranks FROM _days_per_six_months_deploy_by_filter), _median_number_of_deployment_days_per_six_months AS (SELECT MIN(days_deployed_per_six_months) AS median_number_of_deployment_days_per_six_months, MIN(months_deployed_count) AS is_collected FROM _median_number_of_deployment_days_per_six_months_ranks WHERE ranks >= 0.5), _metric_deployment_frequency AS (SELECT 'Deployment frequency' AS metric, CASE WHEN ('$dora_report') = '2023' THEN CASE WHEN median_number_of_deployment_days_per_week >= 5 THEN 'On-demand(elite)' WHEN median_number_of_deployment_days_per_week >= 1 THEN 'Between once per day and once per week(high)' WHEN median_number_of_deployment_days_per_month >= 1 THEN 'Between once per week and once per month(medium)' WHEN median_number_of_deployment_days_per_month < 1 AND NOT is_collected IS NULL THEN 'Fewer than once per month(low)' ELSE 'N/A. Please check if you have collected deployments.' END WHEN ('$dora_report') = '2021' THEN CASE WHEN median_number_of_deployment_days_per_week >= 5 THEN 'On-demand(elite)' WHEN median_number_of_deployment_days_per_month >= 1 THEN 'Between once per day and once per month(high)' WHEN median_number_of_deployment_days_per_six_months >= 1 THEN 'Between once per month and once every 6 months(medium)' WHEN median_number_of_deployment_days_per_six_months < 1 AND NOT is_collected IS NULL THEN 'Fewer than once per six months(low)' ELSE 'N/A. Please check if you have collected deployments.' END ELSE 'Invalid dora report' END AS value FROM _median_number_of_deployment_days_per_week, _median_number_of_deployment_days_per_month, _median_number_of_deployment_days_per_six_months), _pr_stats /* Metric 2: median lead time for changes */ AS (/* get the cycle time of PRs deployed by the deployments finished in the selected period */ SELECT DISTINCT pr.id, ppm.pr_cycle_time FROM pull_requests AS pr JOIN user_accounts AS ua ON pr.author_id = ua.account_id JOIN users AS u ON ua.user_id = u.id JOIN team_users AS tu ON u.id = tu.user_id JOIN teams AS t ON tu.team_id = t.id JOIN project_pr_metrics AS ppm ON ppm.id = pr.id JOIN project_mapping AS pm ON pr.base_repo_id = pm.row_id AND pm.\"table\" = 'repos' JOIN cicd_deployment_commits AS cdc ON ppm.deployment_commit_id = cdc.id WHERE ('${team:csv}' = '' OR t.name::text = ANY(ARRAY[${team:singlequote}]::text[])) AND NOT pr.merged_date IS NULL AND NOT ppm.pr_cycle_time IS NULL AND $__timeFilter(cdc.finished_date)), _median_change_lead_time_ranks AS (SELECT *, PERCENT_RANK() OVER (ORDER BY pr_cycle_time NULLS FIRST) AS ranks FROM _pr_stats), _median_change_lead_time AS (/* use median PR cycle time as the median change lead time */ SELECT MAX(pr_cycle_time) AS median_change_lead_time FROM _median_change_lead_time_ranks WHERE ranks <= 0.5), _metric_change_lead_time AS (SELECT 'Lead time for changes' AS metric, CASE WHEN ('$dora_report') = '2023' THEN CASE WHEN median_change_lead_time < 24 * 60 THEN 'Less than one day(elite)' WHEN median_change_lead_time < 7 * 24 * 60 THEN 'Between one day and one week(high)' WHEN median_change_lead_time < 30 * 24 * 60 THEN 'Between one week and one month(medium)' WHEN median_change_lead_time >= 30 * 24 * 60 THEN 'More than one month(low)' ELSE 'N/A. Please check if you have collected deployments/pull_requests.' END WHEN ('$dora_report') = '2021' THEN CASE WHEN median_change_lead_time < 60 THEN 'Less than one hour(elite)' WHEN median_change_lead_time < 7 * 24 * 60 THEN 'Less than one week(high)' WHEN median_change_lead_time < 180 * 24 * 60 THEN 'Between one week and six months(medium)' WHEN median_change_lead_time >= 180 * 24 * 60 THEN 'More than six months(low)' ELSE 'N/A. Please check if you have collected deployments/pull_requests.' END ELSE 'Invalid dora report' END AS value FROM _median_change_lead_time), _deployments /* Metric 3: change failure rate */ AS (/* When deploying multiple commits in one pipeline, GitLab and BitBucket may generate more than one deployment. However, DevLake consider these deployments as ONE production deployment and use the last one's finished_date as the finished date. */ SELECT cdc.cicd_deployment_id AS deployment_id, MAX(cdc.finished_date) AS deployment_finished_date FROM cicd_deployment_commits AS cdc JOIN commits AS c ON cdc.commit_sha = c.sha JOIN user_accounts AS ua ON c.author_id = ua.account_id JOIN users AS u ON ua.user_id = u.id JOIN team_users AS tu ON u.id = tu.user_id JOIN teams AS t ON tu.team_id = t.id JOIN project_mapping AS pm ON cdc.cicd_scope_id = pm.row_id AND pm.\"table\" = 'cicd_scopes' WHERE ('${team:csv}' = '' OR t.name::text = ANY(ARRAY[${team:singlequote}]::text[])) AND cdc.result = 'SUCCESS' AND cdc.environment = 'PRODUCTION' GROUP BY 1 HAVING MAX(cdc.finished_date) BETWEEN $__timeFrom() AND $__timeTo()), _failure_caused_by_deployments AS (/* calculate the number of incidents caused by each deployment */ SELECT d.deployment_id, d.deployment_finished_date, COUNT(DISTINCT CASE WHEN NOT i.id IS NULL THEN d.deployment_id ELSE NULL END) AS has_incident FROM _deployments AS d LEFT JOIN project_incident_deployment_relationships AS pim ON d.deployment_id = pim.deployment_id LEFT JOIN incidents AS i ON pim.id = i.id GROUP BY 1, 2), _change_failure_rate AS (SELECT CASE WHEN COUNT(deployment_id) IS NULL THEN NULL ELSE CAST(SUM(has_incident) AS NUMERIC) / NULLIF(COUNT(deployment_id), 0) END AS change_failure_rate FROM _failure_caused_by_deployments), _is_collected_data AS (SELECT CASE WHEN COUNT(i.id) = 0 AND COUNT(cdc.id) = 0 THEN 'No All' WHEN COUNT(i.id) = 0 THEN 'No Incidents' WHEN COUNT(cdc.id) = 0 THEN 'No Deployments' END AS is_collected FROM (SELECT 1) AS dummy LEFT JOIN incidents AS i ON 1 = 1 LEFT JOIN cicd_deployment_commits AS cdc ON 1 = 1), _metric_cfr AS (SELECT 'Change failure rate' AS metric, CASE WHEN ('$dora_report') = '2023' THEN CASE WHEN is_collected = 'No All' THEN 'N/A. Please check if you have collected deployments/incidents.' WHEN is_collected = 'No Incidents' THEN 'N/A. Please check if you have collected incidents.' WHEN is_collected = 'No Deployments' THEN 'N/A. Please check if you have collected deployments.' WHEN change_failure_rate <= 0.05 THEN '0-5%(elite)' WHEN change_failure_rate <= 0.10 THEN '5%-10%(high)' WHEN change_failure_rate <= 0.15 THEN '10%-15%(medium)' WHEN change_failure_rate > 0.15 THEN '> 15%(low)' ELSE 'N/A. Please check if you have collected deployments/incidents.' END WHEN ('$dora_report') = '2021' THEN CASE WHEN is_collected = 'No All' THEN 'N/A. Please check if you have collected deployments/incidents.' WHEN is_collected = 'No Incidents' THEN 'N/A. Please check if you have collected incidents.' WHEN is_collected = 'No Deployments' THEN 'N/A. Please check if you have collected deployments.' WHEN change_failure_rate <= 0.15 THEN '0-15%(elite)' WHEN change_failure_rate <= 0.20 THEN '16%-20%(high)' WHEN change_failure_rate <= 0.30 THEN '21%-30%(medium)' WHEN change_failure_rate > 0.30 THEN '> 30%(low)' ELSE 'N/A. Please check if you have collected deployments/incidents.' END ELSE 'Invalid dora report' END AS value FROM _change_failure_rate, _is_collected_data), _incidents_for_deployments /*  ***** 2023 report ***** -- */ /*  Metric 4: Failed deployment recovery time */ AS (SELECT i.id AS incident_id, i.created_date AS incident_create_date, i.resolution_date AS incident_resolution_date, fd.deployment_id AS caused_by_deployment, fd.deployment_finished_date, TO_CHAR(CAST(fd.deployment_finished_date AS TIMESTAMP), 'YY/MM') AS deployment_finished_month FROM incidents AS i LEFT JOIN project_incident_deployment_relationships AS pim ON i.id = pim.id JOIN _deployments AS fd ON pim.deployment_id = fd.deployment_id WHERE $__timeFilter(i.resolution_date)), _recovery_time_ranks AS (SELECT *, PERCENT_RANK() OVER (ORDER BY (EXTRACT(EPOCH FROM (incident_resolution_date - deployment_finished_date))/60) NULLS FIRST) AS ranks FROM _incidents_for_deployments), _median_recovery_time AS (SELECT MAX((EXTRACT(EPOCH FROM (incident_resolution_date - deployment_finished_date))/60)) AS median_recovery_time FROM _recovery_time_ranks WHERE ranks <= 0.5), _metric_recovery_time_2023_report AS (SELECT 'Failed deployment recovery time' AS metric, CASE WHEN ('$dora_report') = '2023' THEN CASE WHEN median_recovery_time < 60 THEN 'Less than one hour(elite)' WHEN median_recovery_time < 24 * 60 THEN 'Less than one day(high)' WHEN median_recovery_time < 7 * 24 * 60 THEN 'Between one day and one week(medium)' WHEN median_recovery_time >= 7 * 24 * 60 THEN 'More than one week(low)' ELSE 'N/A. Please check if you have collected deployments or incidents.' END END AS median_recovery_time FROM _median_recovery_time), _incidents /*  ***** 2021 report ***** -- */ /* Metric 4: Median time to restore service */ AS (/* get the incidents created within the selected time period in the top-right corner */ SELECT DISTINCT i.id, CAST(lead_time_minutes AS BIGINT) AS lead_time_minutes FROM incidents AS i JOIN project_mapping AS pm ON i.scope_id = pm.row_id AND pm.\"table\" = i.\"table\" JOIN user_accounts AS ua ON i.assignee_id = ua.account_id JOIN users AS u ON ua.user_id = u.id JOIN team_users AS tu ON u.id = tu.user_id JOIN teams AS t ON tu.team_id = t.id WHERE ('${team:csv}' = '' OR t.name::text = ANY(ARRAY[${team:singlequote}]::text[])) AND $__timeFilter(i.resolution_date)), _median_mttr_ranks AS (SELECT *, PERCENT_RANK() OVER (ORDER BY lead_time_minutes NULLS FIRST) AS ranks FROM _incidents), _median_mttr AS (SELECT MAX(lead_time_minutes) AS median_time_to_resolve FROM _median_mttr_ranks WHERE ranks <= 0.5), _metric_mttr_2021_report AS (SELECT 'Time to restore service' AS metric, CASE WHEN ('$dora_report') = '2021' THEN CASE WHEN median_time_to_resolve < 60 THEN 'Less than one hour(elite)' WHEN median_time_to_resolve < 24 * 60 THEN 'Less than one day(high)' WHEN median_time_to_resolve < 7 * 24 * 60 THEN 'Between one day and one week(medium)' WHEN median_time_to_resolve >= 7 * 24 * 60 THEN 'More than one week(low)' ELSE 'N/A. Please check if you have collected incidents.' END END AS median_time_to_resolve FROM _median_mttr), _metric_mrt_or_mm AS (SELECT metric, median_recovery_time AS value FROM _metric_recovery_time_2023_report WHERE ('$dora_report') = '2023' UNION SELECT metric, median_time_to_resolve AS value FROM _metric_mttr_2021_report WHERE ('$dora_report') = '2021'), _final_results AS (SELECT DISTINCT db.id, db.metric, db.low, db.medium, db.high, db.elite, m1.metric AS _metric, m1.value FROM dora_benchmarks AS db LEFT JOIN _metric_deployment_frequency AS m1 ON db.metric = m1.metric WHERE NOT m1.metric IS NULL AND db.dora_report = ('$dora_report') UNION SELECT DISTINCT db.id, db.metric, db.low, db.medium, db.high, db.elite, m2.metric AS _metric, m2.value FROM dora_benchmarks AS db LEFT JOIN _metric_change_lead_time AS m2 ON db.metric = m2.metric WHERE NOT m2.metric IS NULL AND db.dora_report = ('$dora_report') UNION SELECT DISTINCT db.id, db.metric, db.low, db.medium, db.high, db.elite, m3.metric AS _metric, m3.value FROM dora_benchmarks AS db LEFT JOIN _metric_cfr AS m3 ON db.metric = m3.metric WHERE NOT m3.metric IS NULL AND db.dora_report = ('$dora_report') UNION SELECT DISTINCT db.id, db.metric, db.low, db.medium, db.high, db.elite, m4.metric AS _metric, m4.value FROM dora_benchmarks AS db LEFT JOIN _metric_mrt_or_mm AS m4 ON db.metric = m4.metric WHERE NOT m4.metric IS NULL AND db.dora_report = ('$dora_report')) SELECT metric, CASE WHEN low = value THEN low ELSE NULL END AS low, CASE WHEN medium = value THEN medium ELSE NULL END AS medium, CASE WHEN high = value THEN high ELSE NULL END AS high, CASE WHEN elite = value THEN elite ELSE NULL END AS elite FROM _final_results ORDER BY id NULLS FIRST"
    }
   ]
  },
  {
   "title": "Deployment Frequency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "/* Metric 1: Deployment Frequency */ WITH last_few_calendar_months AS (/* construct the last few calendar months within the selected time period in the top-right corner */ SELECT CAST(($__timeTo()::timestamp - INTERVAL '1 day') AS DATE) AS day FROM (SELECT 0 AS \"H\" UNION ALL SELECT 100 UNION ALL SELECT 200 UNION ALL SELECT 300) AS \"H\" CROSS JOIN (SELECT 0 AS \"T\" UNION ALL SELECT 10 UNION ALL SELECT 20 UNION ALL SELECT 30 UNION ALL SELECT 40 UNION ALL SELECT 50 UNION ALL SELECT 60 UNION ALL SELECT 70 UNION ALL SELECT 80 UNION ALL SELECT 90) AS \"T\" CROSS JOIN (SELECT 0 AS \"U\" UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS \"U\" WHERE ($__timeTo()::timestamp - INTERVAL '1 day') > $__timeFrom()), _production_deployment_days AS (/* When deploying multiple commits in one pipeline, GitLab and BitBucket may generate more than one deployment. However, DevLake consider these deployments as ONE production deployment and use the last one's finished_date as the finished date. */ SELECT cdc.cicd_deployment_id AS deployment_id, MAX(CAST(cdc.finished_date AS DATE)) AS day FROM cicd_deployment_commits AS cdc JOIN commits AS c ON cdc.commit_sha = c.sha JOIN user_accounts AS ua ON c.author_id = ua.account_id JOIN users AS u ON ua.user_id = u.id JOIN team_users AS tu ON u.id = tu.user_id JOIN teams AS t ON tu.team_id = t.id JOIN project_mapping AS pm ON cdc.cicd_scope_id = pm.row_id AND pm.\"table\" = 'cicd_scopes' WHERE ('${team:csv}' = '' OR t.name::text = ANY(ARRAY[${team:singlequote}]::text[])) AND cdc.result = 'SUCCESS' AND cdc.environment = 'PRODUCTION' GROUP BY 1), _days_weekly_deploy AS (/* calculate the number of deployment days every week */ SELECT CAST(last_few_calendar_months.day + -(EXTRACT(ISODOW FROM last_few_calendar_months.day) - 1) * INTERVAL '1 day' AS DATE) AS week, MAX(CASE WHEN NOT _production_deployment_days.day IS NULL THEN 1 ELSE 0 END) AS weeks_deployed, COUNT(DISTINCT _production_deployment_days.day) AS days_deployed FROM last_few_calendar_months LEFT JOIN _production_deployment_days ON _production_deployment_days.day = last_few_calendar_months.day GROUP BY week), _days_monthly_deploy AS (/* calculate the number of deployment days every month */ SELECT CAST(last_few_calendar_months.day + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST(last_few_calendar_months.day AS DATE)) + 1) AS DATE) AS month, MAX(CASE WHEN NOT _production_deployment_days.day IS NULL THEN 1 ELSE NULL END) AS months_deployed, COUNT(DISTINCT _production_deployment_days.day) AS days_deployed FROM last_few_calendar_months LEFT JOIN _production_deployment_days ON _production_deployment_days.day = last_few_calendar_months.day GROUP BY month), _days_six_months_deploy AS (SELECT month, SUM(days_deployed) OVER (ORDER BY month NULLS FIRST ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS days_deployed_per_six_months, COUNT(months_deployed) OVER (ORDER BY month NULLS FIRST ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS months_deployed_count, ROW_NUMBER() OVER (PARTITION BY ((EXTRACT(YEAR FROM CAST(month AS TIMESTAMP)) * 12 + EXTRACT(MONTH FROM CAST(month AS TIMESTAMP))) / 6) ORDER BY month DESC NULLS LAST) AS rn FROM _days_monthly_deploy), _median_number_of_deployment_days_per_week_ranks AS (SELECT *, PERCENT_RANK() OVER (ORDER BY days_deployed NULLS FIRST) AS ranks FROM _days_weekly_deploy), _median_number_of_deployment_days_per_week AS (SELECT MAX(days_deployed) AS median_number_of_deployment_days_per_week FROM _median_number_of_deployment_days_per_week_ranks WHERE ranks <= 0.5), _median_number_of_deployment_days_per_month_ranks AS (SELECT *, PERCENT_RANK() OVER (ORDER BY days_deployed NULLS FIRST) AS ranks FROM _days_monthly_deploy), _median_number_of_deployment_days_per_month AS (SELECT MAX(days_deployed) AS median_number_of_deployment_days_per_month FROM _median_number_of_deployment_days_per_month_ranks WHERE ranks <= 0.5), _days_per_six_months_deploy_by_filter AS (SELECT month, days_deployed_per_six_months, months_deployed_count FROM _days_six_months_deploy WHERE rn % 6 = 1), _median_number_of_deployment_days_per_six_months_ranks AS (SELECT *, PERCENT_RANK() OVER (ORDER BY days_deployed_per_six_months NULLS FIRST) AS ranks FROM _days_per_six_months_deploy_by_filter), _median_number_of_deployment_days_per_six_months AS (SELECT MIN(days_deployed_per_six_months) AS median_number_of_deployment_days_per_six_months, MIN(months_deployed_count) AS is_collected FROM _median_number_of_deployment_days_per_six_months_ranks WHERE ranks >= 0.5) SELECT CASE WHEN ('$dora_report') = '2023' THEN CASE WHEN median_number_of_deployment_days_per_week >= 5 THEN median_number_of_deployment_days_per_week || ' deployment days per week(elite)' WHEN median_number_of_deployment_days_per_week >= 1 THEN median_number_of_deployment_days_per_week || ' deployment days per week(high)' WHEN median_number_of_deployment_days_per_month >= 1 THEN median_number_of_deployment_days_per_month || ' deployment days per month(medium)' WHEN median_number_of_deployment_days_per_month < 1 AND NOT is_collected IS NULL THEN median_number_of_deployment_days_per_month || ' deployment days per month(low)' ELSE 'N/A. Please check if you have collected deployments.' END WHEN ('$dora_report') = '2021' THEN CASE WHEN median_number_of_deployment_days_per_week >= 5 THEN median_number_of_deployment_days_per_week || ' deployment days per week(elite)' WHEN median_number_of_deployment_days_per_month >= 1 THEN median_number_of_deployment_days_per_month || ' deployment days per month(high)' WHEN median_number_of_deployment_days_per_six_months >= 1 THEN median_number_of_deployment_days_per_six_months || ' deployment days per six months(medium)' WHEN median_number_of_deployment_days_per_six_months < 1 AND NOT is_collected IS NULL THEN median_number_of_deployment_days_per_six_months || ' deployment days per six months(low)' ELSE 'N/A. Please check if you have collected deployments.' END ELSE 'Invalid dora report' END AS \"Deployment Frequency\" FROM _median_number_of_deployment_days_per_week, _median_number_of_deployment_days_per_month, _median_number_of_deployment_days_per_six_months"
    }
   ]
  },
  {
   "title": "Median Lead Time for Changes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "/* Metric 2: median lead time for changes */ WITH _pr_stats AS (/* get the cycle time of PRs deployed by the deployments finished in the selected period */ SELECT DISTINCT pr.id, ppm.pr_cycle_time FROM pull_requests AS pr JOIN user_accounts AS ua ON pr.author_id = ua.account_id JOIN users AS u ON ua.user_id = u.id JOIN team_users AS tu ON u.id = tu.user_id JOIN teams AS t ON tu.team_id = t.id JOIN project_pr_metrics AS ppm ON ppm.id = pr.id JOIN project_mapping AS pm ON pr.base_repo_id = pm.row_id AND pm.\"table\" = 'repos' JOIN cicd_deployment_commits AS cdc ON ppm.deployment_commit_id = cdc.id WHERE ('${team:csv}' = '' OR t.name::text = ANY(ARRAY[${team:singlequote}]::text[])) AND NOT pr.merged_date IS NULL AND NOT ppm.pr_cycle_time IS NULL AND $__timeFilter(cdc.finished_date)), _median_change_lead_time_ranks AS (SELECT *, PERCENT_RANK() OVER (ORDER BY pr_cycle_time NULLS FIRST) AS ranks FROM _pr_stats), _median_change_lead_time AS (/* use median PR cycle time as the median change lead time */ SELECT MAX(pr_cycle_time) AS median_change_lead_time FROM _median_change_lead_time_ranks WHERE ranks <= 0.5) SELECT CASE WHEN ('$dora_report') = '2023' THEN CASE WHEN median_change_lead_time < 24 * 60 THEN ROUND(CAST(CAST(median_change_lead_time AS NUMERIC) / NULLIF(60, 0) AS DECIMAL), 1) || '(elite)' WHEN median_change_lead_time < 7 * 24 * 60 THEN ROUND(CAST(CAST(median_change_lead_time AS NUMERIC) / NULLIF(60, 0) AS DECIMAL), 1) || '(high)' WHEN median_change_lead_time < 30 * 24 * 60 THEN ROUND(CAST(CAST(median_change_lead_time AS NUMERIC) / NULLIF(60, 0) AS DECIMAL), 1) || '(medium)' WHEN median_change_lead_time >= 30 * 24 * 60 THEN ROUND(CAST(CAST(median_change_lead_time AS NUMERIC) / NULLIF(60, 0) AS DECIMAL), 1) || '(low)' ELSE 'N/A. Please check if you have collected deployments/pull_requests.' END WHEN ('$dora_report') = '2021' THEN CASE WHEN median_change_lead_time < 60 THEN ROUND(CAST(CAST(median_change_lead_time AS NUMERIC) / NULLIF(60, 0) AS DECIMAL), 1) || '(elite)' WHEN median_change_lead_time < 7 * 24 * 60 THEN ROUND(CAST(CAST(median_change_lead_time AS NUMERIC) / NULLIF(60, 0) AS DECIMAL), 1) || '(high)' WHEN median_change_lead_time < 180 * 24 * 60 THEN ROUND(CAST(CAST(median_change_lead_time AS NUMERIC) / NULLIF(60, 0) AS DECIMAL), 1) || '(medium)' WHEN median_change_lead_time >= 180 * 24 * 60 THEN (ROUND(CAST(CAST(median_change_lead_time AS NUMERIC) / NULLIF(60, 0) AS DECIMAL), 1) || '(low)')::TEXT ELSE 'N/A. Please check if you have collected deployments/pull_requests.' END ELSE 'Invalid dora report' END AS median_change_lead_time FROM _median_change_lead_time"
    }
   ]
  },
  {
   "title": "Change Failure Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "/* Metric 4: change failure rate */ WITH _deployments AS (/* When deploying multiple commits in one pipeline, GitLab and BitBucket may generate more than one deployment. However, DevLake consider these deployments as ONE production deployment and use the last one's finished_date as the finished date. */ SELECT cdc.cicd_deployment_id AS deployment_id, MAX(cdc.finished_date) AS deployment_finished_date FROM cicd_deployment_commits AS cdc JOIN commits AS c ON cdc.commit_sha = c.sha JOIN user_accounts AS ua ON c.author_id = ua.account_id JOIN users AS u ON ua.user_id = u.id JOIN team_users AS tu ON u.id = tu.user_id JOIN teams AS t ON tu.team_id = t.id JOIN project_mapping AS pm ON cdc.cicd_scope_id = pm.row_id AND pm.\"table\" = 'cicd_scopes' WHERE ('${team:csv}' = '' OR t.name::text = ANY(ARRAY[${team:singlequote}]::text[])) AND cdc.result = 'SUCCESS' AND cdc.environment = 'PRODUCTION' GROUP BY 1 HAVING MAX(cdc.finished_date) BETWEEN $__timeFrom() AND $__timeTo()), _failure_caused_by_deployments AS (/* calculate the number of incidents caused by each deployment */ SELECT d.deployment_id, d.deployment_finished_date, COUNT(DISTINCT CASE WHEN NOT i.id IS NULL THEN d.deployment_id ELSE NULL END) AS has_incident FROM _deployments AS d LEFT JOIN project_incident_deployment_relationships AS pim ON d.deployment_id = pim.deployment_id LEFT JOIN incidents AS i ON pim.id = i.id GROUP BY 1, 2), _change_failure_rate AS (SELECT CASE WHEN COUNT(deployment_id) IS NULL THEN NULL ELSE CAST(SUM(has_incident) AS NUMERIC) / NULLIF(COUNT(deployment_id), 0) END AS change_failure_rate FROM _failure_caused_by_deployments), _is_collected_data AS (SELECT CASE WHEN COUNT(i.id) = 0 AND COUNT(cdc.id) = 0 THEN 'No All' WHEN COUNT(i.id) = 0 THEN 'No Incidents' WHEN COUNT(cdc.id) = 0 THEN 'No Deployments' END AS is_collected FROM (SELECT 1) AS dummy LEFT JOIN incidents AS i ON 1 = 1 LEFT JOIN cicd_deployment_commits AS cdc ON 1 = 1) SELECT CASE WHEN ('$dora_report') = '2023' THEN CASE WHEN is_collected = 'No All' THEN 'N/A. Please check if you have collected deployments/incidents.' WHEN is_collected = 'No Incidents' THEN 'N/A. Please check if you have collected incidents.' WHEN is_collected = 'No Deployments' THEN 'N/A. Please check if you have collected deployments.' WHEN change_failure_rate <= 0.05 THEN ROUND(change_failure_rate * 100, 1) || '%(elite)' WHEN change_failure_rate <= 0.10 THEN ROUND(change_failure_rate * 100, 1) || '%(high)' WHEN change_failure_rate <= 0.15 THEN ROUND(change_failure_rate * 100, 1) || '%(medium)' WHEN change_failure_rate > 0.15 THEN ROUND(change_failure_rate * 100, 1) || '%(low)' ELSE 'N/A. Please check if you have collected deployments/incidents.' END WHEN ('$dora_report') = '2021' THEN CASE WHEN is_collected = 'No All' THEN 'N/A. Please check if you have collected deployments/incidents.' WHEN is_collected = 'No Incidents' THEN 'N/A. Please check if you have collected incidents.' WHEN is_collected = 'No Deployments' THEN 'N/A. Please check if you have collected deployments.' WHEN change_failure_rate <= 0.15 THEN ROUND(change_failure_rate * 100, 1) || '%(elite)' WHEN change_failure_rate <= 0.20 THEN ROUND(change_failure_rate * 100, 1) || '%(high)' WHEN change_failure_rate <= 0.30 THEN ROUND(change_failure_rate * 100, 1) || '%(medium)' WHEN change_failure_rate > 0.30 THEN ROUND(change_failure_rate * 100, 1) || '%(low)' ELSE 'N/A. Please check if you have collected deployments/incidents.' END ELSE 'Invalid dora report' END AS change_failure_rate FROM _change_failure_rate, \"_is_collected_data\""
    }
   ]
  },
  {
   "title": "${title_value}",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "/*  ***** 2023 report ***** -- */ /*  Metric 4: Failed deployment recovery time */ WITH _deployments AS (SELECT cdc.cicd_deployment_id AS deployment_id, MAX(cdc.finished_date) AS deployment_finished_date FROM cicd_deployment_commits AS cdc JOIN commits AS c ON cdc.commit_sha = c.sha JOIN user_accounts AS ua ON c.author_id = ua.account_id JOIN users AS u ON ua.user_id = u.id JOIN team_users AS tu ON u.id = tu.user_id JOIN teams AS t ON tu.team_id = t.id JOIN project_mapping AS pm ON cdc.cicd_scope_id = pm.row_id AND pm.\"table\" = 'cicd_scopes' WHERE ('${team:csv}' = '' OR t.name::text = ANY(ARRAY[${team:singlequote}]::text[])) AND cdc.result = 'SUCCESS' AND cdc.environment = 'PRODUCTION' GROUP BY 1 HAVING MAX(cdc.finished_date) BETWEEN $__timeFrom() AND $__timeTo()), _incidents_for_deployments AS (SELECT i.id AS incident_id, i.created_date AS incident_create_date, i.resolution_date AS incident_resolution_date, fd.deployment_id AS caused_by_deployment, fd.deployment_finished_date, TO_CHAR(CAST(fd.deployment_finished_date AS TIMESTAMP), 'YY/MM') AS deployment_finished_month FROM incidents AS i LEFT JOIN project_incident_deployment_relationships AS pim ON i.id = pim.id JOIN _deployments AS fd ON pim.deployment_id = fd.deployment_id WHERE $__timeFilter(i.resolution_date)), _recovery_time_ranks AS (SELECT *, PERCENT_RANK() OVER (ORDER BY (EXTRACT(EPOCH FROM (incident_resolution_date - deployment_finished_date))/60) NULLS FIRST) AS ranks FROM _incidents_for_deployments), _median_recovery_time AS (SELECT MAX((EXTRACT(EPOCH FROM (incident_resolution_date - deployment_finished_date))/60)) AS median_recovery_time FROM _recovery_time_ranks WHERE ranks <= 0.5), _metric_recovery_time_2023_report AS (SELECT CASE WHEN ('$dora_report') = '2023' THEN CASE WHEN median_recovery_time < 60 THEN ROUND(CAST(CAST(median_recovery_time AS NUMERIC) / NULLIF(60, 0) AS DECIMAL), 1) || '(elite)' WHEN median_recovery_time < 24 * 60 THEN ROUND(CAST(CAST(median_recovery_time AS NUMERIC) / NULLIF(60, 0) AS DECIMAL), 1) || '(high)' WHEN median_recovery_time < 7 * 24 * 60 THEN ROUND(CAST(CAST(median_recovery_time AS NUMERIC) / NULLIF(60, 0) AS DECIMAL), 1) || '(medium)' WHEN median_recovery_time >= 7 * 24 * 60 THEN ROUND(CAST(CAST(median_recovery_time AS NUMERIC) / NULLIF(60, 0) AS DECIMAL), 1) || '(low)' ELSE 'N/A. Please check if you have collected deployments or incidents.' END END AS median_recovery_time FROM _median_recovery_time), _incidents /*  ***** 2021 report ***** -- */ /* Metric 4: Median time to restore service */ AS (/* get the incidents created within the selected time period in the top-right corner */ SELECT DISTINCT i.id, CAST(lead_time_minutes AS BIGINT) AS lead_time_minutes FROM incidents AS i JOIN project_mapping AS pm ON i.scope_id = pm.row_id AND pm.\"table\" = i.\"table\" JOIN user_accounts AS ua ON i.assignee_id = ua.account_id JOIN users AS u ON ua.user_id = u.id JOIN team_users AS tu ON u.id = tu.user_id JOIN teams AS t ON tu.team_id = t.id WHERE ('${team:csv}' = '' OR t.name::text = ANY(ARRAY[${team:singlequote}]::text[])) AND $__timeFilter(i.resolution_date)), _median_mttr_ranks AS (SELECT *, PERCENT_RANK() OVER (ORDER BY lead_time_minutes NULLS FIRST) AS ranks FROM _incidents), _median_mttr AS (SELECT MAX(lead_time_minutes) AS median_time_to_resolve FROM _median_mttr_ranks WHERE ranks <= 0.5), _metric_mttr_2021_report AS (SELECT CASE WHEN ('$dora_report') = '2021' THEN CASE WHEN median_time_to_resolve < 60 THEN ROUND(CAST(CAST(median_time_to_resolve AS NUMERIC) / NULLIF(60, 0) AS DECIMAL), 1) || '(elite)' WHEN median_time_to_resolve < 24 * 60 THEN ROUND(CAST(CAST(median_time_to_resolve AS NUMERIC) / NULLIF(60, 0) AS DECIMAL), 1) || '(high)' WHEN median_time_to_resolve < 7 * 24 * 60 THEN ROUND(CAST(CAST(median_time_to_resolve AS NUMERIC) / NULLIF(60, 0) AS DECIMAL), 1) || '(medium)' WHEN median_time_to_resolve >= 7 * 24 * 60 THEN (ROUND(CAST(CAST(median_time_to_resolve AS NUMERIC) / NULLIF(60, 0) AS DECIMAL), 1) || '(low)')::TEXT ELSE 'N/A. Please check if you have collected incidents.' END END AS median_time_to_resolve FROM _median_mttr) SELECT median_recovery_time AS median_time_in_hour FROM _metric_recovery_time_2023_report WHERE ('$dora_report') = '2023' UNION SELECT median_time_to_resolve AS median_time_to_resolve FROM _metric_mttr_2021_report WHERE ('$dora_report') = '2021'"
    }
   ]
  },
  {
   "title": "Monthly deployments",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "/* Metric 1: Number of deployments per month */ WITH _deployments AS (/* When deploying multiple commits in one pipeline, GitLab and BitBucket may generate more than one deployment. However, DevLake consider these deployments as ONE production deployment and use the last one's finished_date as the finished date. */ SELECT TO_CHAR(CAST(deployment_finished_date AS TIMESTAMP), 'YY/MM') AS month, COUNT(cicd_deployment_id) AS deployment_count FROM (SELECT cdc.cicd_deployment_id, MAX(cdc.finished_date) AS deployment_finished_date FROM cicd_deployment_commits AS cdc JOIN commits AS c ON cdc.commit_sha = c.sha JOIN user_accounts AS ua ON c.author_id = ua.account_id JOIN users AS u ON ua.user_id = u.id JOIN team_users AS tu ON u.id = tu.user_id JOIN teams AS t ON tu.team_id = t.id JOIN project_mapping AS pm ON cdc.cicd_scope_id = pm.row_id AND pm.\"table\" = 'cicd_scopes' WHERE ('${team:csv}' = '' OR t.name::text = ANY(ARRAY[${team:singlequote}]::text[])) AND cdc.result = 'SUCCESS' AND cdc.environment = 'PRODUCTION' GROUP BY 1 HAVING MAX(cdc.finished_date) BETWEEN $__timeFrom() AND $__timeTo()) AS _production_deployments GROUP BY 1) SELECT cm.month, CASE WHEN d.deployment_count IS NULL THEN 0 ELSE d.deployment_count END AS \"Deployment Count\" FROM calendar_months AS cm LEFT JOIN _deployments AS d ON cm.month = d.month WHERE $__timeFilter(month_timestamp)"
    }
   ]
  },
  {
   "title": "Median Lead Time for Changes",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "rawSql": "/* Metric 2: median change lead time per month */ WITH _pr_stats AS (/* get the cycle time of PRs deployed by the deployments finished each month */ SELECT DISTINCT pr.id, TO_CHAR(CAST(cdc.finished_date AS TIMESTAMP), 'YY/MM') AS month, ppm.pr_cycle_time FROM pull_requests AS pr JOIN user_accounts AS ua ON pr.author_id = ua.account_id JOIN users AS u ON ua.user_id = u.id JOIN team_users AS tu ON u.id = tu.user_id JOIN teams AS t ON tu.team_id = t.id JOIN project_pr_metrics AS ppm ON ppm.id = pr.id JOIN project_mapping AS pm ON pr.base_repo_id = pm.row_id AND pm.\"table\" = 'repos' JOIN cicd_deployment_commits AS cdc ON ppm.deployment_commit_id = cdc.id WHERE ('${team:csv}' = '' OR t.name::text = ANY(ARRAY[${team:singlequote}]::text[])) AND NOT pr.merged_date IS NULL AND NOT ppm.pr_cycle_time IS NULL AND $__timeFilter(cdc.finished_date)), _find_median_clt_each_month_ranks AS (SELECT *, PERCENT_RANK() OVER (PARTITION BY month ORDER BY pr_cycle_time NULLS FIRST) AS ranks FROM _pr_stats), _clt AS (SELECT month, MAX(pr_cycle_time) AS median_change_lead_time FROM _find_median_clt_each_month_ranks WHERE ranks <= 0.5 GROUP BY month) SELECT cm.month, CASE WHEN _clt.median_change_lead_time IS NULL THEN 0 ELSE CAST(_clt.median_change_lead_time AS NUMERIC) / NULLIF(60, 0) END AS \"Median Change Lead Time In Hour\" FROM calendar_months AS cm LEFT JOIN _clt ON cm.month = _clt.month WHERE $__timeFilter(month_timestamp)"
    }
   ]
  },
  {
   "title": "Change Failure Rate",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "/* Metric 4: change failure rate per month */ WITH _deployments AS (/* When deploying multiple commits in one pipeline, GitLab and BitBucket may generate more than one deployment. However, DevLake consider these deployments as ONE production deployment and use the last one's finished_date as the finished date. */ SELECT cdc.cicd_deployment_id AS deployment_id, MAX(cdc.finished_date) AS deployment_finished_date FROM cicd_deployment_commits AS cdc JOIN commits AS c ON cdc.commit_sha = c.sha JOIN user_accounts AS ua ON c.author_id = ua.account_id JOIN users AS u ON ua.user_id = u.id JOIN team_users AS tu ON u.id = tu.user_id JOIN teams AS t ON tu.team_id = t.id JOIN project_mapping AS pm ON cdc.cicd_scope_id = pm.row_id AND pm.\"table\" = 'cicd_scopes' WHERE ('${team:csv}' = '' OR t.name::text = ANY(ARRAY[${team:singlequote}]::text[])) AND cdc.result = 'SUCCESS' AND cdc.environment = 'PRODUCTION' GROUP BY 1 HAVING MAX(cdc.finished_date) BETWEEN $__timeFrom() AND $__timeTo()), _failure_caused_by_deployments AS (/* calculate the number of incidents caused by each deployment */ SELECT d.deployment_id, d.deployment_finished_date, COUNT(DISTINCT CASE WHEN NOT i.id IS NULL THEN d.deployment_id ELSE NULL END) AS has_incident FROM _deployments AS d LEFT JOIN project_incident_deployment_relationships AS pim ON d.deployment_id = pim.deployment_id LEFT JOIN incidents AS i ON pim.id = i.id GROUP BY 1, 2), _change_failure_rate_for_each_month AS (SELECT TO_CHAR(CAST(deployment_finished_date AS TIMESTAMP), 'YY/MM') AS month, CASE WHEN COUNT(deployment_id) IS NULL THEN NULL ELSE CAST(SUM(has_incident) AS NUMERIC) / NULLIF(COUNT(deployment_id), 0) END AS change_failure_rate FROM _failure_caused_by_deployments GROUP BY 1) SELECT cm.month, cfr.change_failure_rate AS \"Change Failure Rate\" FROM calendar_months AS cm LEFT JOIN _change_failure_rate_for_each_month AS cfr ON cm.month = cfr.month WHERE $__timeFilter(month_timestamp)"
    }
   ]
  },
  {
   "title": "${title_value}",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "/*  ***** 2023 report ***** -- */ /*  Metric 4: Failed deployment recovery time */ WITH _deployments AS (SELECT cdc.cicd_deployment_id AS deployment_id, MAX(cdc.finished_date) AS deployment_finished_date FROM cicd_deployment_commits AS cdc JOIN commits AS c ON cdc.commit_sha = c.sha JOIN user_accounts AS ua ON c.author_id = ua.account_id JOIN users AS u ON ua.user_id = u.id JOIN team_users AS tu ON u.id = tu.user_id JOIN teams AS t ON tu.team_id = t.id JOIN project_mapping AS pm ON cdc.cicd_scope_id = pm.row_id AND pm.\"table\" = 'cicd_scopes' WHERE ('${team:csv}' = '' OR t.name::text = ANY(ARRAY[${team:singlequote}]::text[])) AND cdc.result = 'SUCCESS' AND cdc.environment = 'PRODUCTION' GROUP BY 1 HAVING MAX(cdc.finished_date) BETWEEN $__timeFrom() AND $__timeTo()), _incidents_for_deployments AS (SELECT i.id AS incident_id, i.created_date AS incident_create_date, i.resolution_date AS incident_resolution_date, fd.deployment_id AS caused_by_deployment, fd.deployment_finished_date, TO_CHAR(CAST(fd.deployment_finished_date AS TIMESTAMP), 'YY/MM') AS deployment_finished_month FROM incidents AS i LEFT JOIN project_incident_deployment_relationships AS pim ON i.id = pim.id JOIN _deployments AS fd ON pim.deployment_id = fd.deployment_id WHERE $__timeFilter(i.resolution_date)), _recovery_time_ranks AS (SELECT *, PERCENT_RANK() OVER (PARTITION BY deployment_finished_month ORDER BY (EXTRACT(EPOCH FROM (incident_resolution_date - deployment_finished_date))/60) NULLS FIRST) AS ranks FROM _incidents_for_deployments), _median_recovery_time AS (SELECT deployment_finished_month, MAX((EXTRACT(EPOCH FROM (incident_resolution_date - deployment_finished_date))/60)) AS median_recovery_time FROM _recovery_time_ranks WHERE ranks <= 0.5 GROUP BY deployment_finished_month), _metric_recovery_time_2023_report AS (SELECT cm.month, CASE WHEN m.median_recovery_time IS NULL THEN 0 ELSE CAST(m.median_recovery_time AS NUMERIC) / NULLIF(60, 0) END AS median_recovery_time_in_hour FROM calendar_months AS cm LEFT JOIN _median_recovery_time AS m ON cm.month = m.deployment_finished_month WHERE month_timestamp BETWEEN CAST(TO_CHAR(CAST($__timeFrom() AS TIMESTAMP), 'YYYY-MM-01') AS DATE) AND CAST(TO_CHAR(CAST($__timeTo() AS TIMESTAMP), 'YYYY-MM-01') AS DATE)), _incidents /*  ***** 2021 report ***** -- */ /* Metric 4: median time to restore service - MTTR */ AS (/* get the number of incidents created each month */ SELECT DISTINCT i.id, TO_CHAR(CAST(i.resolution_date AS TIMESTAMP), 'YY/MM') AS month, CAST(lead_time_minutes AS BIGINT) AS lead_time_minutes FROM incidents AS i JOIN project_mapping AS pm ON i.scope_id = pm.row_id AND pm.\"table\" = i.\"table\" JOIN user_accounts AS ua ON i.assignee_id = ua.account_id JOIN users AS u ON ua.user_id = u.id JOIN team_users AS tu ON u.id = tu.user_id JOIN teams AS t ON tu.team_id = t.id WHERE ('${team:csv}' = '' OR t.name::text = ANY(ARRAY[${team:singlequote}]::text[])) AND NOT i.lead_time_minutes IS NULL), _find_median_mttr_each_month_ranks AS (SELECT *, PERCENT_RANK() OVER (PARTITION BY month ORDER BY lead_time_minutes NULLS FIRST) AS ranks FROM _incidents), _mttr AS (SELECT month, MAX(lead_time_minutes) AS median_time_to_resolve FROM _find_median_mttr_each_month_ranks WHERE ranks <= 0.5 GROUP BY month), _metric_mttr_2021_report AS (SELECT cm.month, CASE WHEN m.median_time_to_resolve IS NULL THEN 0 ELSE CAST(m.median_time_to_resolve AS NUMERIC) / NULLIF(60, 0) END AS median_time_to_resolve_in_hour FROM calendar_months AS cm LEFT JOIN _mttr AS m ON cm.month = m.month WHERE month_timestamp BETWEEN CAST(TO_CHAR(CAST($__timeFrom() AS TIMESTAMP), 'YYYY-MM-01') AS DATE) AND CAST(TO_CHAR(CAST($__timeTo() AS TIMESTAMP), 'YYYY-MM-01') AS DATE)) SELECT cm.month, CASE WHEN '${dora_report}' = '2023' THEN mrt.median_recovery_time_in_hour WHEN '${dora_report}' = '2021' THEN mm.median_time_to_resolve_in_hour END AS \"${title_value} In Hours\" FROM calendar_months AS cm LEFT JOIN _metric_recovery_time_2023_report AS mrt ON cm.month = mrt.month LEFT JOIN _metric_mttr_2021_report AS mm ON cm.month = mm.month WHERE month_timestamp BETWEEN CAST(TO_CHAR(CAST($__timeFrom() AS TIMESTAMP), 'YYYY-MM-01') AS DATE) AND CAST(TO_CHAR(CAST($__timeTo() AS TIMESTAMP), 'YYYY-MM-01') AS DATE)"
    }
   ]
  }
 ]
}