{
 "title": "DORA Validation",
 "tags": [ "Engineering Leads Dashboard" ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "SELECT DISTINCT name FROM projects"
   },
   {
    "name": "pr_id",
    "label": "Pull Request Url",
    "query": "SELECT Url || '--' || id FROM pull_requests"
   },
   {
    "name": "dora_report",
    "label": "DORA Report",
    "query": "SELECT dora_report FROM dora_benchmarks"
   },
   {
    "name": "title_value",
    "label": "TitleValue",
    "query": "SELECT CASE WHEN dora_report = '2023' THEN 'Failed Deployment Recovery Time' WHEN dora_report = '2021' THEN 'Median Time to Restore Service' ELSE NULL END AS title_value FROM dora_benchmarks WHERE dora_report = '${dora_report:raw}'"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Introduction",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard is designed to validate the [DORA dashboard](/grafana/d/qNo8_0M4z/dora?orgId=1)."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Check \"Deployment Frequency\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "options": {
    "content": "- See the definition and calculation logic of [Deployment Frequency](https://devlake.apache.org/docs/Metrics/DeploymentFrequency)\n- Data Sources Required: \n  - `Deployments` from Jenkins, GitLab CI, GitHub Action, BitBucket Pipelines, or Webhook, etc. \n- Transformation Required: Define `deployments` in [data transformations](https://devlake.apache.org/docs/Configuration/Tutorial#step-3---add-transformations-optional) while configuring the blueprint of a project."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Step 1. All cicd_deployment_commits (the rows with 3 green columns will be used in the following steps)",
   "type": "table",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT pm.project_name, CASE WHEN ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) THEN 'This project is selected' ELSE 'Not Selected' END AS select_status, CASE WHEN cdc._raw_data_table <> '' THEN cdc._raw_data_table ELSE cdc.cicd_scope_id END AS _raw_data_table, result, environment, COUNT(DISTINCT cdc.id) AS deployment_commit_count, COUNT(DISTINCT cdc.cicd_deployment_id) AS deployment_count FROM cicd_deployment_commits AS cdc LEFT JOIN project_mapping AS pm ON cdc.cicd_scope_id = pm.row_id AND pm.\"table\" = 'cicd_scopes' WHERE $__timeFilter(cdc.finished_date) GROUP BY 1, 2, 3, 4, 5"
    }
   ]
  },
  {
   "title": "Figure 1 - Deployment Frequency",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "/* Metric 1: Deployment Frequency */ WITH last_few_calendar_months AS (/* construct the last few calendar months within the selected time period in the top-right corner */ SELECT CAST(($__timeTo()::timestamp - INTERVAL '1 day') AS DATE) AS day FROM (SELECT 0 AS \"H\" UNION ALL SELECT 100 UNION ALL SELECT 200 UNION ALL SELECT 300) AS \"H\" CROSS JOIN (SELECT 0 AS \"T\" UNION ALL SELECT 10 UNION ALL SELECT 20 UNION ALL SELECT 30 UNION ALL SELECT 40 UNION ALL SELECT 50 UNION ALL SELECT 60 UNION ALL SELECT 70 UNION ALL SELECT 80 UNION ALL SELECT 90) AS \"T\" CROSS JOIN (SELECT 0 AS \"U\" UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS \"U\" WHERE ($__timeTo()::timestamp - INTERVAL '1 day') > $__timeFrom()), _production_deployment_days AS (/* When deploying multiple commits in one pipeline, GitLab and BitBucket may generate more than one deployment. However, DevLake consider these deployments as ONE production deployment and use the last one's finished_date as the finished date. */ SELECT cdc.cicd_deployment_id AS deployment_id, MAX(CAST(cdc.finished_date AS DATE)) AS day FROM cicd_deployment_commits AS cdc JOIN project_mapping AS pm ON cdc.cicd_scope_id = pm.row_id AND pm.\"table\" = 'cicd_scopes' WHERE ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND cdc.result = 'SUCCESS' AND cdc.environment = 'PRODUCTION' GROUP BY 1), _days_weekly_deploy AS (/* calculate the number of deployment days every week */ SELECT CAST(last_few_calendar_months.day + -(EXTRACT(ISODOW FROM last_few_calendar_months.day) - 1) * INTERVAL '1 day' AS DATE) AS week, MAX(CASE WHEN NOT _production_deployment_days.day IS NULL THEN 1 ELSE NULL END) AS weeks_deployed, COUNT(DISTINCT _production_deployment_days.day) AS days_deployed FROM last_few_calendar_months LEFT JOIN _production_deployment_days ON _production_deployment_days.day = last_few_calendar_months.day GROUP BY week), _days_monthly_deploy AS (/* calculate the number of deployment days every month */ SELECT CAST(last_few_calendar_months.day + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST(last_few_calendar_months.day AS DATE)) + 1) AS DATE) AS month, MAX(CASE WHEN NOT _production_deployment_days.day IS NULL THEN 1 ELSE NULL END) AS months_deployed, COUNT(DISTINCT _production_deployment_days.day) AS days_deployed FROM last_few_calendar_months LEFT JOIN _production_deployment_days ON _production_deployment_days.day = last_few_calendar_months.day GROUP BY month), _days_six_months_deploy AS (SELECT month, SUM(days_deployed) OVER (ORDER BY month NULLS FIRST ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS days_deployed_per_six_months, COUNT(months_deployed) OVER (ORDER BY month NULLS FIRST ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS months_deployed_count, ROW_NUMBER() OVER (PARTITION BY ((EXTRACT(YEAR FROM CAST(month AS TIMESTAMP)) * 12 + EXTRACT(MONTH FROM CAST(month AS TIMESTAMP))) / 6) ORDER BY month DESC NULLS LAST) AS rn FROM _days_monthly_deploy), _median_number_of_deployment_days_per_week_ranks AS (SELECT *, PERCENT_RANK() OVER (ORDER BY days_deployed NULLS FIRST) AS ranks FROM _days_weekly_deploy), _median_number_of_deployment_days_per_week AS (SELECT MAX(days_deployed) AS median_number_of_deployment_days_per_week FROM _median_number_of_deployment_days_per_week_ranks WHERE ranks <= 0.5), _median_number_of_deployment_days_per_month_ranks AS (SELECT *, PERCENT_RANK() OVER (ORDER BY days_deployed NULLS FIRST) AS ranks FROM _days_monthly_deploy), _median_number_of_deployment_days_per_month AS (SELECT MAX(days_deployed) AS median_number_of_deployment_days_per_month FROM _median_number_of_deployment_days_per_month_ranks WHERE ranks <= 0.5), _days_per_six_months_deploy_by_filter AS (SELECT month, days_deployed_per_six_months, months_deployed_count FROM _days_six_months_deploy WHERE rn % 6 = 1), _median_number_of_deployment_days_per_six_months_ranks AS (SELECT *, PERCENT_RANK() OVER (ORDER BY days_deployed_per_six_months NULLS FIRST) AS ranks FROM _days_per_six_months_deploy_by_filter), _median_number_of_deployment_days_per_six_months AS (SELECT MIN(days_deployed_per_six_months) AS median_number_of_deployment_days_per_six_months, MIN(months_deployed_count) AS is_collected FROM _median_number_of_deployment_days_per_six_months_ranks WHERE ranks >= 0.5) SELECT CASE WHEN ('$dora_report') = '2023' THEN CASE WHEN median_number_of_deployment_days_per_week >= 5 THEN 'On-demand(elite)' WHEN median_number_of_deployment_days_per_week >= 1 THEN 'Between once per day and once per week(high)' WHEN median_number_of_deployment_days_per_month >= 1 THEN 'Between once per week and once per month(medium)' WHEN median_number_of_deployment_days_per_month < 1 AND NOT is_collected IS NULL THEN 'Fewer than once per month(low)' ELSE 'N/A. Please check if you have collected deployments.' END WHEN ('$dora_report') = '2021' THEN CASE WHEN median_number_of_deployment_days_per_week >= 5 THEN 'On-demand(elite)' WHEN median_number_of_deployment_days_per_month >= 1 THEN 'Between once per day and once per month(high)' WHEN median_number_of_deployment_days_per_six_months >= 1 THEN 'Between once per month and once every 6 months(medium)' WHEN median_number_of_deployment_days_per_six_months < 1 AND NOT is_collected IS NULL THEN 'Fewer than once per six months(low)' ELSE 'N/A. Please check if you have collected deployments.' END ELSE 'Invalid dora report' END AS \"Deployment Frequency\" FROM _median_number_of_deployment_days_per_week, _median_number_of_deployment_days_per_month, _median_number_of_deployment_days_per_six_months"
    }
   ]
  },
  {
   "title": "Step 2. Find the number of successful  production deployments in this project (Last column)",
   "type": "table",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT pm.project_name, CASE WHEN ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) THEN 'This project is selected' ELSE 'Not Selected' END AS select_status, CASE WHEN cdc._raw_data_table <> '' THEN cdc._raw_data_table ELSE cdc.cicd_scope_id END AS _raw_data_table, result, environment, COUNT(DISTINCT cdc.id) AS deployment_commit_count, COUNT(DISTINCT cdc.cicd_deployment_id) AS deployment_count FROM cicd_deployment_commits AS cdc JOIN project_mapping AS pm ON cdc.cicd_scope_id = pm.row_id AND pm.\"table\" = 'cicd_scopes' WHERE ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND result = 'SUCCESS' AND environment = 'PRODUCTION' AND $__timeFilter(cdc.finished_date) GROUP BY 1, 2, 3, 4, 5"
    }
   ]
  },
  {
   "title": "Figure 2 - Monthly deployments",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "rawSql": "/* Metric 1: Number of deployments per month */ WITH _deployments AS (/* When deploying multiple commits in one pipeline, GitLab and BitBucket may generate more than one deployment. However, DevLake consider these deployments as ONE production deployment and use the last one's finished_date as the finished date. */ SELECT TO_CHAR(CAST(deployment_finished_date AS TIMESTAMP), 'YY/MM') AS month, COUNT(cicd_deployment_id) AS deployment_count FROM (SELECT cdc.cicd_deployment_id, MAX(cdc.finished_date) AS deployment_finished_date FROM cicd_deployment_commits AS cdc JOIN project_mapping AS pm ON cdc.cicd_scope_id = pm.row_id AND pm.\"table\" = 'cicd_scopes' WHERE ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND cdc.result = 'SUCCESS' AND cdc.environment = 'PRODUCTION' GROUP BY 1 HAVING MAX(cdc.finished_date) BETWEEN $__timeFrom() AND $__timeTo()) AS _production_deployments GROUP BY 1) SELECT cm.month, CASE WHEN d.deployment_count IS NULL THEN 0 ELSE d.deployment_count END AS \"Deployment Count\" FROM calendar_months AS cm LEFT JOIN _deployments AS d ON cm.month = d.month WHERE month_timestamp BETWEEN CAST(TO_CHAR(CAST($__timeFrom() AS TIMESTAMP), 'YYYY-MM-01') AS DATE) AND CAST(TO_CHAR(CAST($__timeTo() AS TIMESTAMP), 'YYYY-MM-01') AS DATE)"
    }
   ]
  },
  {
   "title": "Step 3. Use the last finished_date of deployment commits as the finished date of deployments in this project",
   "type": "table",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "WITH _deployment_commit_rank AS (SELECT pm.project_name, CASE WHEN cdc._raw_data_table <> '' THEN cdc._raw_data_table ELSE cdc.cicd_scope_id END AS _raw_data_table, cdc.id, cdc.cicd_deployment_id, cdc.cicd_scope_id, result, environment, finished_date, ROW_NUMBER() OVER (PARTITION BY cdc.cicd_deployment_id ORDER BY finished_date DESC NULLS LAST) AS _deployment_commit_rank FROM cicd_deployment_commits AS cdc LEFT JOIN project_mapping AS pm ON cdc.cicd_scope_id = pm.row_id AND pm.\"table\" = 'cicd_scopes' WHERE ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND result = 'SUCCESS' AND environment = 'PRODUCTION') SELECT project_name, cicd_deployment_id AS deployment_id, id AS deployment_commit_id /* a deployment may have multiple deployment_commits */, result, environment, finished_date FROM _deployment_commit_rank WHERE _deployment_commit_rank = 1 AND $__timeFilter(finished_date)"
    }
   ]
  },
  {
   "title": "Step 4. Daily deployments in this project [To check Figure 1]",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "WITH _deployment_commit_rank AS (SELECT pm.project_name, CASE WHEN cdc._raw_data_table <> '' THEN cdc._raw_data_table ELSE cdc.cicd_scope_id END AS _raw_data_table, cdc.id, cdc.cicd_deployment_id, cdc.cicd_scope_id, result, environment, finished_date, ROW_NUMBER() OVER (PARTITION BY cdc.cicd_deployment_id ORDER BY finished_date DESC NULLS LAST) AS _deployment_commit_rank FROM cicd_deployment_commits AS cdc LEFT JOIN project_mapping AS pm ON cdc.cicd_scope_id = pm.row_id AND pm.\"table\" = 'cicd_scopes' WHERE ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND result = 'SUCCESS' AND environment = 'PRODUCTION'), _deployments AS (SELECT project_name, cicd_deployment_id AS deployment_id, id AS deployment_commit_id /* a deployment may have multiple deployment_commits */, result, environment, finished_date FROM _deployment_commit_rank WHERE _deployment_commit_rank = 1 AND $__timeFilter(finished_date)) SELECT DISTINCT CAST(finished_date AS DATE) AS day, COUNT(1) AS deployment_count FROM _deployments GROUP BY 1"
    }
   ]
  },
  {
   "title": "Step 5. Monthly deployments in this project [To check Figure 2]",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "rawSql": "WITH _deployment_commit_rank AS (SELECT pm.project_name, CASE WHEN cdc._raw_data_table <> '' THEN cdc._raw_data_table ELSE cdc.cicd_scope_id END AS _raw_data_table, cdc.id, cdc.cicd_deployment_id, cdc.cicd_scope_id, result, environment, finished_date, ROW_NUMBER() OVER (PARTITION BY cdc.cicd_deployment_id ORDER BY finished_date DESC NULLS LAST) AS _deployment_commit_rank FROM cicd_deployment_commits AS cdc LEFT JOIN project_mapping AS pm ON cdc.cicd_scope_id = pm.row_id AND pm.\"table\" = 'cicd_scopes' WHERE ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND result = 'SUCCESS' AND environment = 'PRODUCTION'), _deployments AS (SELECT project_name, cicd_deployment_id AS deployment_id, id AS deployment_commit_id /* a deployment may have multiple deployment_commits */, result, environment, finished_date FROM _deployment_commit_rank WHERE _deployment_commit_rank = 1 AND $__timeFilter(finished_date)), _deployment_days AS (SELECT DISTINCT CAST(finished_date AS DATE) AS day, COUNT(1) AS deployment_count FROM _deployments GROUP BY 1) SELECT TO_CHAR(CAST(day AS TIMESTAMP), 'YY/MM') AS month, SUM(deployment_count) AS monthly_deployment_counts FROM _deployment_days GROUP BY 1 ORDER BY 1 NULLS FIRST"
    }
   ]
  },
  {
   "title": "Check \"Median Lead Time for Changes\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "options": {
    "content": "- See the definition and calculation logic of [Median Lead Time for Changes](https://devlake.apache.org/docs/Metrics/LeadTimeForChanges)\n- Data Sources Required: \n  - `Deployments` from Jenkins, GitLab CI, GitHub Action, BitBucket Pipelines, or Webhook, etc. \n  - `Pull Requests` from GitHub PRs, GitLab MRs, BitBucket PRs, Azure DevOps PRs, etc.\n- Transformation Required: Define `deployments` in [data transformations](https://devlake.apache.org/docs/Configuration/Tutorial#step-3---add-transformations-optional) while configuring the blueprint of a project.\n- Validatation Steps below:\n  - Step 1 - check the data integrity of PRs in table `pull_requests`\n  - Step 2 - check the data integrity of deployment_commit in table `cicd_deployment_commits`\n  - Step 3 - check if a deployment_commit is associated with the correct PR in table `project_pr_metrics`\n  - Step 4 - check if metrics like PR Coding/Pickup/Review/Deploy/cycle time are correct in table `project_pr_metrics`\n  - Step 5 - check if the median lead time for changes in each month is correct"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Step 1-1. Check if the total PR number in the selected project(s) is correct",
   "type": "table",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT pm.project_name, pr._raw_data_table, COUNT(*) AS total_number_of_PRs FROM pull_requests AS pr /* \tjoin project_pr_metrics prm on prm.id = pr.id */ JOIN project_mapping AS pm ON pr.base_repo_id = pm.row_id AND pm.\"table\" = 'repos' WHERE ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND /* \tand pr.merged_date is not null */ /* \tand prm.pr_cycle_time is not null */ $__timeFilter(pr.created_date) GROUP BY 1, 2"
    }
   ]
  },
  {
   "title": "Figure 3 - Median Lead Time for Changes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "/* Metric 2: median lead time for changes */ WITH _pr_stats AS (/* get the cycle time of PRs deployed by the deployments finished in the selected period */ SELECT DISTINCT pr.id, ppm.pr_cycle_time FROM pull_requests AS pr JOIN project_pr_metrics AS ppm ON ppm.id = pr.id JOIN project_mapping AS pm ON pr.base_repo_id = pm.row_id AND pm.\"table\" = 'repos' JOIN cicd_deployment_commits AS cdc ON ppm.deployment_commit_id = cdc.id WHERE ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND NOT pr.merged_date IS NULL AND NOT ppm.pr_cycle_time IS NULL AND $__timeFilter(cdc.finished_date)), _median_change_lead_time_ranks AS (SELECT *, PERCENT_RANK() OVER (ORDER BY pr_cycle_time NULLS FIRST) AS ranks FROM _pr_stats), _median_change_lead_time AS (/* use median PR cycle time as the median change lead time */ SELECT MAX(pr_cycle_time) AS median_change_lead_time FROM _median_change_lead_time_ranks WHERE ranks <= 0.5) SELECT CASE WHEN ('$dora_report') = '2023' THEN CASE WHEN median_change_lead_time < 24 * 60 THEN 'Less than one day(elite)' WHEN median_change_lead_time < 7 * 24 * 60 THEN 'Between one day and one week(high)' WHEN median_change_lead_time < 30 * 24 * 60 THEN 'Between one week and one month(medium)' WHEN median_change_lead_time >= 30 * 24 * 60 THEN 'More than one month(low)' ELSE 'N/A. Please check if you have collected deployments/pull_requests.' END WHEN ('$dora_report') = '2021' THEN CASE WHEN median_change_lead_time < 60 THEN 'Less than one hour(elite)' WHEN median_change_lead_time < 7 * 24 * 60 THEN 'Less than one week(high)' WHEN median_change_lead_time < 180 * 24 * 60 THEN 'Between one week and six months(medium)' WHEN median_change_lead_time >= 180 * 24 * 60 THEN 'More than six months(low)' ELSE 'N/A. Please check if you have collected deployments/pull_requests.' END ELSE 'Invalid dora report' END AS median_change_lead_time FROM _median_change_lead_time"
    }
   ]
  },
  {
   "title": "Step 1-2. Check if the attributes of the selected pull request is correct (Use the Pull Request URL filter above)",
   "type": "table",
   "gridPos": { "h": 3, "w": 16, "x": 0, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT pm.project_name, pr.title /* pr.status, */, pr.author_name, pr.url, pr.merged_date, pr.created_date FROM pull_requests AS pr JOIN project_mapping AS pm ON pr.base_repo_id = pm.row_id AND pm.\"table\" = 'repos' WHERE pr.id /* ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) */ = '$pr_id' AND $__timeFilter(pr.created_date)"
    }
   ]
  },
  {
   "title": "Figure 4 - Median Lead Time for Changes",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
   "targets": [
    {
     "rawSql": "/* Metric 2: median change lead time per month */ WITH _pr_stats AS (/* get the cycle time of PRs deployed by the deployments finished each month */ SELECT DISTINCT pr.id, TO_CHAR(CAST(cdc.finished_date AS TIMESTAMP), 'YY/MM') AS month, ppm.pr_cycle_time FROM pull_requests AS pr JOIN project_pr_metrics AS ppm ON ppm.id = pr.id JOIN project_mapping AS pm ON pr.base_repo_id = pm.row_id AND pm.\"table\" = 'repos' JOIN cicd_deployment_commits AS cdc ON ppm.deployment_commit_id = cdc.id WHERE ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND NOT pr.merged_date IS NULL AND NOT ppm.pr_cycle_time IS NULL AND $__timeFilter(cdc.finished_date)), _find_median_clt_each_month_ranks AS (SELECT *, PERCENT_RANK() OVER (PARTITION BY month ORDER BY pr_cycle_time NULLS FIRST) AS ranks FROM _pr_stats), _clt AS (SELECT month, MAX(pr_cycle_time) AS median_change_lead_time FROM _find_median_clt_each_month_ranks WHERE ranks <= 0.5 GROUP BY month) SELECT cm.month, CASE WHEN _clt.median_change_lead_time IS NULL THEN 0 ELSE CAST(_clt.median_change_lead_time AS NUMERIC) / NULLIF(60, 0) END AS \"Median Change Lead Time In Hour\" FROM calendar_months AS cm LEFT JOIN _clt ON cm.month = _clt.month WHERE month_timestamp BETWEEN CAST(TO_CHAR(CAST($__timeFrom() AS TIMESTAMP), 'YYYY-MM-01') AS DATE) AND CAST(TO_CHAR(CAST($__timeTo() AS TIMESTAMP), 'YYYY-MM-01') AS DATE)"
    }
   ]
  },
  {
   "title": "Step 1-3. Check if the No. of records in project_pr_metrics is the same as the No. of MERGED PRs in the selected project(s)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT pr.id) AS \"No. of merged PRs in table.pull_requests\" FROM pull_requests AS pr JOIN project_mapping AS pm ON pr.base_repo_id = pm.row_id AND pm.\"table\" = 'repos' WHERE ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND NOT pr.merged_date IS NULL"
    },
    {
     "rawSql": "SELECT COUNT(DISTINCT id) AS \"No. of PRs in table.project_pr_metrics\" FROM project_pr_metrics WHERE ('${project:csv}' = '' OR project_name::text = ANY(ARRAY[${project:singlequote}]::text[]))"
    }
   ]
  },
  {
   "title": "Step 2. Check if the number of successful  production deployments in the selected project(s) is correct",
   "type": "table",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 46 },
   "targets": [
    {
     "rawSql": "SELECT pm.project_name, CASE WHEN ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) THEN 'This project is selected' ELSE 'Not Selected' END AS select_status, CASE WHEN cdc._raw_data_table <> '' THEN cdc._raw_data_table ELSE cdc.cicd_scope_id END AS _raw_data_table, result, environment, COUNT(DISTINCT cdc.id) AS deployment_commit_count, COUNT(DISTINCT cdc.cicd_deployment_id) AS deployment_count FROM cicd_deployment_commits AS cdc JOIN project_mapping AS pm ON cdc.cicd_scope_id = pm.row_id AND pm.\"table\" = 'cicd_scopes' WHERE ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND result = 'SUCCESS' AND environment = 'PRODUCTION' AND $__timeFilter(cdc.finished_date) GROUP BY 1, 2, 3, 4, 5"
    }
   ]
  },
  {
   "title": "Appendix 1 - All PRs in this project (Only the rows with 2 green columns should appear in project_pr_metrics)",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT pm.project_name, CASE WHEN ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) THEN 'This project is selected' ELSE 'Not Selected' END AS select_status, pr.title /* pr.status, */, pr.url /* \tpr.author_name, */, pr.merged_date, pr.created_date FROM pull_requests AS pr JOIN project_mapping AS pm ON pr.base_repo_id = pm.row_id AND pm.\"table\" = 'repos' WHERE $__timeFilter(pr.created_date) /* ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) */"
    }
   ]
  },
  {
   "title": "Step 3. Check if a `pull request` is associated with the correct `depoloyment commit` in table project_pr_metrics",
   "type": "table",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 50 },
   "targets": [
    {
     "rawSql": "/* This query can be used to test if the column \"deployment_commit_id\" is associated with the correct PR */ WITH pr_merge_commits AS (SELECT ppm.id AS pr_id, ppm.deployment_commit_id AS id_1, pr.merge_commit_sha, ppm.project_name FROM project_pr_metrics AS ppm LEFT JOIN pull_requests AS pr ON ppm.id = pr.id WHERE ('${project:csv}' = '' OR ppm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND ppm.id = '$pr_id'), _deployment_commits AS (SELECT DISTINCT cdc1.id AS id_2, cdc1.prev_success_deployment_commit_id, cdc1.commit_sha AS new_commit_sha, cdc2.commit_sha AS old_commit_sha, cdc1.finished_date, cd.commit_sha AS deployed_commits FROM cicd_deployment_commits AS cdc1 LEFT JOIN cicd_deployment_commits AS cdc2 ON cdc1.prev_success_deployment_commit_id = cdc2.id JOIN commits_diffs AS cd ON cdc1.commit_sha = cd.new_commit_sha AND COALESCE(cdc2.commit_sha, '') = cd.old_commit_sha JOIN project_mapping AS pm ON cdc1.cicd_scope_id = pm.row_id WHERE cdc1.result = 'SUCCESS' AND cdc1.environment = 'PRODUCTION' AND ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[]))), _find_deployment_commit_id_from_pr AS (SELECT pmc.pr_id, pmc.id_1, pmc.merge_commit_sha, pmc.project_name, dc.id_2, dc.prev_success_deployment_commit_id, dc.deployed_commits, RANK() OVER (PARTITION BY pr_id ORDER BY dc.finished_date NULLS FIRST) AS deployment_rank FROM pr_merge_commits AS pmc LEFT JOIN _deployment_commits AS dc ON pmc.merge_commit_sha = dc.deployed_commits) SELECT pr_id, id_1 AS deployment_commit_id /* If \"id_1\" equals \"id_2\", then pass */, CASE WHEN id_1 = COALESCE(id_2, '') THEN 'YES' ELSE 'NO' END AS if_the_mapping_logic_is_correct /* \tid_2, */ FROM _find_deployment_commit_id_from_pr WHERE deployment_rank = 1"
    }
   ]
  },
  {
   "title": "Step 4-1. Check if PR coding time in project_pr_metrics is correct (Adopt the Pull Request filter above)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH _pr_commit_ranks AS (SELECT pr.id, pr.created_date AS pr_created_date, prc.commit_sha, prc.commit_authored_date, ROW_NUMBER() OVER (PARTITION BY pr.id ORDER BY prc.commit_authored_date ASC NULLS FIRST) AS commit_rank FROM pull_requests AS pr LEFT JOIN pull_request_commits AS prc ON pr.id = prc.pull_request_id WHERE pr.id = '$pr_id') SELECT id, CEIL(CAST(EXTRACT(EPOCH FROM (pr_created_date - commit_authored_date)) AS NUMERIC) / NULLIF(60, 0)) AS \"PR coding time from PRs and commits\" /* commit_sha as first_commit_sha, */ /* commit_authored_date as first_commit_authored_date, */ FROM _pr_commit_ranks WHERE commit_rank = 1"
    },
    {
     "rawSql": "SELECT id, pr_coding_time AS \"PR coding time from project_pr_metrics\" /* first_commit_sha, */ FROM project_pr_metrics WHERE id = '$pr_id'"
    }
   ]
  },
  {
   "title": "Step 4-2. Check if PR pickup time in project_pr_metrics is correct (Adopt the Pull Request filter above)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH _pr_comment_ranks AS (SELECT pr.id AS pr_id, pr.created_date AS pr_created_date, prc.id AS review_id, prc.created_date AS review_created_date, ROW_NUMBER() OVER (PARTITION BY pr.id ORDER BY prc.created_date ASC NULLS FIRST) AS comment_rank FROM pull_requests AS pr LEFT JOIN pull_request_comments AS prc ON pr.id = prc.pull_request_id WHERE pr.id = '$pr_id' AND prc.account_id <> pr.author_id) SELECT pr_id, review_id AS first_review_id, pr_created_date, review_created_date AS first_review_time, CEIL(CAST(EXTRACT(EPOCH FROM (review_created_date - pr_created_date)) AS NUMERIC) / NULLIF(60, 0)) AS \"PR pickup time from pr_comments\" FROM _pr_comment_ranks WHERE comment_rank = 1"
    },
    {
     "rawSql": "SELECT id, pr_pickup_time AS \"PR pickup time from project_pr_metrics\" /* first_review_id, */ FROM project_pr_metrics WHERE id = '$pr_id' AND ('${project:csv}' = '' OR project_name::text = ANY(ARRAY[${project:singlequote}]::text[]))"
    }
   ]
  },
  {
   "title": "Step 4-3. Check if PR review time in project_pr_metrics is correct (Adopt the Pull Request filter above)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "WITH _pr_comment_ranks AS (SELECT pr.id AS pr_id, pr.merged_date AS pr_merged_date, prc.id AS review_id, prc.created_date AS review_created_date, ROW_NUMBER() OVER (PARTITION BY pr.id ORDER BY prc.created_date ASC NULLS FIRST) AS comment_rank_asc FROM pull_requests AS pr LEFT JOIN pull_request_comments AS prc ON pr.id = prc.pull_request_id WHERE pr.id = '$pr_id' AND prc.account_id <> pr.author_id) SELECT pr_id, review_id AS first_review_id, review_created_date AS first_review_time, CEIL(CAST(EXTRACT(EPOCH FROM (pr_merged_date - review_created_date)) AS NUMERIC) / NULLIF(60, 0)) AS \"PR review time from pr_comments\" FROM _pr_comment_ranks WHERE comment_rank_asc = 1"
    },
    {
     "rawSql": "SELECT id, pr_review_time AS \"PR review time from project_pr_metrics\" /* first_review_id, */ FROM project_pr_metrics WHERE id = '$pr_id' AND ('${project:csv}' = '' OR project_name::text = ANY(ARRAY[${project:singlequote}]::text[]))"
    }
   ]
  },
  {
   "title": "Step 4-4. Check if PR deploy time in project_pr_metrics is correct (Adopt the Pull Request filter above)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT ppm.id AS pr_id, ppm.deployment_commit_id, CEIL(CAST(EXTRACT(EPOCH FROM (cdc.finished_date - pr.merged_date)) AS NUMERIC) / NULLIF(60, 0)) AS \"PR deploy time from cicd_deployment_commits\" FROM project_pr_metrics AS ppm LEFT JOIN cicd_deployment_commits AS cdc ON ppm.deployment_commit_id = cdc.id LEFT JOIN pull_requests AS pr ON ppm.id = pr.id WHERE ('${project:csv}' = '' OR project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND cdc.result = 'SUCCESS' AND cdc.\"environment\" = 'PRODUCTION' AND ppm.id = '$pr_id'"
    },
    {
     "rawSql": "SELECT id, pr_deploy_time AS \"PR deploy time from project_pr_metrics\" FROM project_pr_metrics WHERE id = '$pr_id' AND ('${project:csv}' = '' OR project_name::text = ANY(ARRAY[${project:singlequote}]::text[]))"
    }
   ]
  },
  {
   "title": "Step 4-5. Check if PR cycle time in project_pr_metrics is correct (Adopt the Pull Request filter above)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT ppm.id, (pr_coding_time + CEIL(CAST(EXTRACT(EPOCH FROM (pr.merged_date - pr.created_date)) AS NUMERIC) / NULLIF(60, 0)) + pr_deploy_time) AS \"PR cycle time from lower-level metrics\", ppm.\"pr_cycle_time\" AS \"PR cycle time from project_pr_metrics\" FROM project_pr_metrics AS ppm LEFT JOIN pull_requests AS pr ON ppm.id = pr.id WHERE ('${project:csv}' = '' OR project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND pr.id = '$pr_id'"
    }
   ]
  },
  {
   "title": "Step 5 - check the median change lead time for each month in Figure 4 (Compare the change_lead_time with the max ranks in GREEN before the first occurrence of ORANGE in each month)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {
     "rawSql": "WITH _pr_stats AS (/* get the cycle time of PRs deployed by the deployments finished each month */ SELECT DISTINCT TO_CHAR(CAST(cdc.finished_date AS TIMESTAMP), 'YY/MM') AS month, pr.id, ppm.pr_cycle_time FROM pull_requests AS pr JOIN project_pr_metrics AS ppm ON ppm.id = pr.id JOIN project_mapping AS pm ON pr.base_repo_id = pm.row_id AND pm.\"table\" = 'repos' JOIN cicd_deployment_commits AS cdc ON ppm.deployment_commit_id = cdc.id WHERE ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND NOT pr.merged_date IS NULL AND NOT ppm.pr_cycle_time IS NULL AND $__timeFilter(cdc.finished_date)), _find_median_clt_each_month_ranks AS (SELECT *, PERCENT_RANK() OVER (PARTITION BY month ORDER BY pr_cycle_time NULLS FIRST) AS ranks FROM _pr_stats) SELECT month, id, pr_cycle_time AS change_lead_time_in_minutes, CAST(pr_cycle_time AS NUMERIC) / NULLIF(60, 0) AS change_lead_time_in_hours, ranks FROM _find_median_clt_each_month_ranks"
    }
   ]
  },
  {
   "title": "Check \"Change Failure Rate\" & \"${title_value}\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 75 },
   "options": {
    "content": "- See the definition and calculation logic of [${title_value}](https://devlake.apache.org/docs/Metrics/MTTR)\n- Data Sources Required: \n  - `Deployments` from Jenkins, GitLab CI, GitHub Action, BitBucket Pipelines, or Webhook, etc. \n  - `Incidents` from Jira issues, GitHub issues, TAPD issues, PagerDuty Incidents, etc. \n- Transformation Required: Define `deployments` and `incidents` in [data transformations](https://devlake.apache.org/docs/Configuration/Tutorial#step-3---add-transformations-optional) while configuring the blueprint of a project."
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 79 },
   "options": {
    "content": "- See the definition and calculation logic of [Change Failure Rate](https://devlake.apache.org/docs/Metrics/CFR)\n- Data Sources Required: \n  - `Deployments` from Jenkins, GitLab CI, GitHub Action, BitBucket Pipelines, or Webhook, etc. \n  - `Incidents` from Jira issues, GitHub issues, TAPD issues, PagerDuty Incidents, etc. \n- Transformation Required: Define `deployments` and `incidents` in [data transformations](https://devlake.apache.org/docs/Configuration/Tutorial#step-3---add-transformations-optional) while configuring the blueprint of a project."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Step 1. All types of issues in table.issues (rows with 2 green columns will be used to construct project_incident_deployment_relationships)",
   "type": "table",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 83 },
   "targets": [
    {
     "rawSql": "/* get the incident created within the selected time period in the top-right corner */ SELECT pm.project_name, CASE WHEN ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) THEN 'This project is selected' ELSE 'Not Selected' END AS select_status, i._raw_data_table, i.type, COUNT(1) AS issue_count FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id JOIN project_mapping AS pm ON b.id = pm.row_id AND pm.\"table\" = 'boards' WHERE ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND /* \tand i.type = 'INCIDENT' */ $__timeFilter(i.created_date) GROUP BY pm.project_name, \"select_status\", i._raw_data_table, i.type"
    }
   ]
  },
  {
   "title": "Figure 5 - ${title_value}",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "/*  ***** 2023 report ***** -- */ /*  Metric 4: Failed deployment recovery time */ WITH _deployments AS (SELECT cdc.cicd_deployment_id AS deployment_id, MAX(cdc.finished_date) AS deployment_finished_date FROM cicd_deployment_commits AS cdc JOIN project_mapping AS pm ON cdc.cicd_scope_id = pm.row_id AND pm.\"table\" = 'cicd_scopes' WHERE ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND cdc.result = 'SUCCESS' AND cdc.environment = 'PRODUCTION' GROUP BY 1 HAVING MAX(cdc.finished_date) BETWEEN $__timeFrom() AND $__timeTo()), _incidents_for_deployments AS (SELECT i.id AS incident_id, i.created_date AS incident_create_date, i.resolution_date AS incident_resolution_date, fd.deployment_id AS caused_by_deployment, fd.deployment_finished_date, TO_CHAR(CAST(fd.deployment_finished_date AS TIMESTAMP), 'YY/MM') AS deployment_finished_month FROM incidents AS i LEFT JOIN project_incident_deployment_relationships AS pim ON i.id = pim.id JOIN _deployments AS fd ON pim.deployment_id = fd.deployment_id WHERE $__timeFilter(i.resolution_date)), _recovery_time_ranks AS (SELECT *, PERCENT_RANK() OVER (ORDER BY (EXTRACT(EPOCH FROM (incident_resolution_date - deployment_finished_date))/60) NULLS FIRST) AS ranks FROM _incidents_for_deployments), _median_recovery_time AS (SELECT MAX((EXTRACT(EPOCH FROM (incident_resolution_date - deployment_finished_date))/60)) AS median_recovery_time FROM _recovery_time_ranks WHERE ranks <= 0.5), _is_collected_data AS (SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM _deployments) AND NOT EXISTS(SELECT 1 FROM incidents) THEN 'No deployments and incidents' WHEN NOT EXISTS(SELECT 1 FROM _deployments) THEN 'No Deployments' WHEN NOT EXISTS(SELECT 1 FROM incidents) THEN 'No Incidents' ELSE 'No incidents are mapped to deployments' END AS is_collected FROM _deployments AS d, _incidents_for_deployments AS i), _metric_recovery_time_2023_report AS (SELECT CASE WHEN ('$dora_report') = '2023' THEN CASE WHEN is_collected = 'No deployments and incidents' THEN 'N/A. Please check if you have collected deployments and incidents.' WHEN is_collected = 'No Deployments' THEN 'N/A. Please check if you have collected deployments.' WHEN is_collected = 'No Incidents' THEN 'N/A. Please check if you have collected incidents.' WHEN median_recovery_time < 60 THEN ROUND(CAST(CAST(median_recovery_time AS NUMERIC) / NULLIF(60, 0) AS DECIMAL), 1) || '(elite)' WHEN median_recovery_time < 24 * 60 THEN ROUND(CAST(CAST(median_recovery_time AS NUMERIC) / NULLIF(60, 0) AS DECIMAL), 1) || '(high)' WHEN median_recovery_time < 7 * 24 * 60 THEN ROUND(CAST(CAST(median_recovery_time AS NUMERIC) / NULLIF(60, 0) AS DECIMAL), 1) || '(medium)' WHEN median_recovery_time >= 7 * 24 * 60 THEN ROUND(CAST(CAST(median_recovery_time AS NUMERIC) / NULLIF(60, 0) AS DECIMAL), 1) || '(low)' ELSE 'No data' END END AS median_recovery_time FROM _median_recovery_time, _is_collected_data), _incidents /*  ***** 2021 report ***** -- */ /* Metric 4: Median time to restore service */ AS (/* get the incidents created within the selected time period in the top-right corner */ SELECT DISTINCT i.id, CAST(lead_time_minutes AS BIGINT) AS lead_time_minutes FROM incidents AS i JOIN project_mapping AS pm ON i.scope_id = pm.row_id AND pm.\"table\" = i.\"table\" WHERE ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND $__timeFilter(i.created_date)), _median_mttr_ranks AS (SELECT *, PERCENT_RANK() OVER (ORDER BY lead_time_minutes NULLS FIRST) AS ranks FROM _incidents), _median_mttr AS (SELECT MAX(lead_time_minutes) AS median_time_to_resolve FROM _median_mttr_ranks WHERE ranks <= 0.5), _metric_mttr_2021_report AS (SELECT CASE WHEN ('$dora_report') = '2021' THEN CASE WHEN median_time_to_resolve < 60 THEN 'Less than one hour(elite)' WHEN median_time_to_resolve < 24 * 60 THEN 'Less than one day(high)' WHEN median_time_to_resolve < 7 * 24 * 60 THEN 'Between one day and one week(medium)' WHEN median_time_to_resolve >= 7 * 24 * 60 THEN 'More than one week(low)' ELSE 'N/A. Please check if you have collected incidents.' END END AS median_time_to_resolve FROM _median_mttr) SELECT median_recovery_time AS median_time_in_hour FROM _metric_recovery_time_2023_report WHERE ('$dora_report') = '2023' UNION SELECT median_time_to_resolve AS median_time_to_resolve FROM _metric_mttr_2021_report WHERE ('$dora_report') = '2021'"
    }
   ]
  },
  {
   "title": "Step 2. Number of Incidents in the selected project(s)",
   "type": "table",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 89 },
   "targets": [
    {
     "rawSql": "/* get the incident created within the selected time period in the top-right corner */ SELECT pm.project_name, CASE WHEN ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) THEN 'This project is selected' ELSE 'Not Selected' END AS select_status, i._raw_data_table, COUNT(1) AS issue_count FROM incidents AS i JOIN project_mapping AS pm ON i.scope_id = pm.row_id AND pm.\"table\" = i.\"table\" WHERE ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND $__timeFilter(i.created_date) GROUP BY pm.project_name, \"select_status\", i._raw_data_table"
    }
   ]
  },
  {
   "title": "Deployment - Incident Mapping and CFR calculation logic",
   "type": "text",
   "gridPos": { "h": 15, "w": 16, "x": 0, "y": 93 },
   "options": {
    "content": "<img src = 'https://devlake.apache.org/assets/images/cfr-definition-94d92cc75f857f183443ad5390d31d65.png' />\n\nIn this case:\n\n- Deployment-1 maps to Incident-1\n- Deployment-3 maps to Incident-2 and Incident-3\n- Deployment-2,4,5 doesn't map to any Incident"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Figure 6 - ${title_value}",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "/*  ***** 2023 report ***** -- */ /*  Metric 4: Failed deployment recovery time */ WITH _deployments AS (SELECT cdc.cicd_deployment_id AS deployment_id, MAX(cdc.finished_date) AS deployment_finished_date FROM cicd_deployment_commits AS cdc JOIN project_mapping AS pm ON cdc.cicd_scope_id = pm.row_id AND pm.\"table\" = 'cicd_scopes' WHERE ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND cdc.result = 'SUCCESS' AND cdc.environment = 'PRODUCTION' GROUP BY 1 HAVING MAX(cdc.finished_date) BETWEEN $__timeFrom() AND $__timeTo()), _incidents_for_deployments AS (SELECT i.id AS incident_id, i.created_date AS incident_create_date, i.resolution_date AS incident_resolution_date, fd.deployment_id AS caused_by_deployment, fd.deployment_finished_date, TO_CHAR(CAST(fd.deployment_finished_date AS TIMESTAMP), 'YY/MM') AS deployment_finished_month FROM incidents AS i LEFT JOIN project_incident_deployment_relationships AS pim ON i.id = pim.id JOIN _deployments AS fd ON pim.deployment_id = fd.deployment_id WHERE $__timeFilter(i.resolution_date)), _recovery_time_ranks AS (SELECT *, PERCENT_RANK() OVER (PARTITION BY deployment_finished_month ORDER BY (EXTRACT(EPOCH FROM (incident_resolution_date - deployment_finished_date))/60) NULLS FIRST) AS ranks FROM _incidents_for_deployments), _median_recovery_time AS (SELECT deployment_finished_month, MAX((EXTRACT(EPOCH FROM (incident_resolution_date - deployment_finished_date))/60)) AS median_recovery_time FROM _recovery_time_ranks WHERE ranks <= 0.5 GROUP BY deployment_finished_month), _metric_recovery_time_2023_report AS (SELECT cm.month, CASE WHEN m.median_recovery_time IS NULL THEN 0 ELSE CAST(m.median_recovery_time AS NUMERIC) / NULLIF(60, 0) END AS median_recovery_time_in_hour FROM calendar_months AS cm LEFT JOIN _median_recovery_time AS m ON cm.month = m.deployment_finished_month WHERE month_timestamp BETWEEN CAST(TO_CHAR(CAST($__timeFrom() AS TIMESTAMP), 'YYYY-MM-01') AS DATE) AND CAST(TO_CHAR(CAST($__timeTo() AS TIMESTAMP), 'YYYY-MM-01') AS DATE)), _incidents /*  ***** 2021 report ***** -- */ /* Metric 4: median time to restore service - MTTR */ AS (/* get the number of incidents created each month */ SELECT DISTINCT i.id, TO_CHAR(CAST(i.created_date AS TIMESTAMP), 'YY/MM') AS month, CAST(lead_time_minutes AS BIGINT) AS lead_time_minutes FROM incidents AS i JOIN project_mapping AS pm ON i.scope_id = pm.row_id AND pm.\"table\" = i.\"table\" WHERE ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND NOT i.lead_time_minutes IS NULL), _find_median_mttr_each_month_ranks AS (SELECT *, PERCENT_RANK() OVER (PARTITION BY month ORDER BY lead_time_minutes NULLS FIRST) AS ranks FROM _incidents), _mttr AS (SELECT month, MAX(lead_time_minutes) AS median_time_to_resolve FROM _find_median_mttr_each_month_ranks WHERE ranks <= 0.5 GROUP BY month), _metric_mttr_2021_report AS (SELECT cm.month, CASE WHEN m.median_time_to_resolve IS NULL THEN 0 ELSE CAST(m.median_time_to_resolve AS NUMERIC) / NULLIF(60, 0) END AS median_time_to_resolve_in_hour FROM calendar_months AS cm LEFT JOIN _mttr AS m ON cm.month = m.month WHERE month_timestamp BETWEEN CAST(TO_CHAR(CAST($__timeFrom() AS TIMESTAMP), 'YYYY-MM-01') AS DATE) AND CAST(TO_CHAR(CAST($__timeTo() AS TIMESTAMP), 'YYYY-MM-01') AS DATE)) SELECT cm.month, CASE WHEN '${dora_report}' = '2023' THEN mrt.median_recovery_time_in_hour WHEN '${dora_report}' = '2021' THEN mm.median_time_to_resolve_in_hour END AS \"${title_value} In Hours\" FROM calendar_months AS cm LEFT JOIN _metric_recovery_time_2023_report AS mrt ON cm.month = mrt.month LEFT JOIN _metric_mttr_2021_report AS mm ON cm.month = mm.month WHERE month_timestamp BETWEEN CAST(TO_CHAR(CAST($__timeFrom() AS TIMESTAMP), 'YYYY-MM-01') AS DATE) AND CAST(TO_CHAR(CAST($__timeTo() AS TIMESTAMP), 'YYYY-MM-01') AS DATE)"
    }
   ]
  },
  {
   "title": "Figure 7 - Change Failure Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 103 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "/* Metric 3: change failure rate */ WITH _deployments AS (/* When deploying multiple commits in one pipeline, GitLab and BitBucket may generate more than one deployment. However, DevLake consider these deployments as ONE production deployment and use the last one's finished_date as the finished date. */ SELECT cdc.cicd_deployment_id AS deployment_id, MAX(cdc.finished_date) AS deployment_finished_date FROM cicd_deployment_commits AS cdc JOIN project_mapping AS pm ON cdc.cicd_scope_id = pm.row_id AND pm.\"table\" = 'cicd_scopes' WHERE ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND cdc.result = 'SUCCESS' AND cdc.environment = 'PRODUCTION' GROUP BY 1 HAVING MAX(cdc.finished_date) BETWEEN $__timeFrom() AND $__timeTo()), _failure_caused_by_deployments AS (/* calculate the number of incidents caused by each deployment */ SELECT d.deployment_id, d.deployment_finished_date, COUNT(DISTINCT CASE WHEN i.id = NULL THEN d.deployment_id ELSE NULL END) AS has_incident FROM _deployments AS d LEFT JOIN project_incident_deployment_relationships AS pim ON d.deployment_id = pim.deployment_id LEFT JOIN incidents AS i ON pim.id = i.id GROUP BY 1, 2), _change_failure_rate AS (SELECT CASE WHEN COUNT(deployment_id) IS NULL THEN NULL ELSE CAST(SUM(has_incident) AS NUMERIC) / NULLIF(COUNT(deployment_id), 0) END AS change_failure_rate FROM _failure_caused_by_deployments), _is_collected_data AS (SELECT CASE WHEN COUNT(i.id) = 0 AND COUNT(cdc.id) = 0 THEN 'No All' WHEN COUNT(i.id) = 0 THEN 'No Incidents' WHEN COUNT(cdc.id) = 0 THEN 'No Deployments' END AS is_collected FROM (SELECT 1) AS dummy LEFT JOIN incidents AS i ON 1 = 1 LEFT JOIN cicd_deployment_commits AS cdc ON 1 = 1) SELECT CASE WHEN ('$dora_report') = '2023' THEN CASE WHEN is_collected = 'No All' THEN 'N/A. Please check if you have collected deployments/incidents.' WHEN is_collected = 'No Incidents' THEN 'N/A. Please check if you have collected incidents.' WHEN is_collected = 'No Deployments' THEN 'N/A. Please check if you have collected deployments.' WHEN change_failure_rate <= 0.05 THEN '0-5%(elite)' WHEN change_failure_rate <= 0.10 THEN '5%-10%(high)' WHEN change_failure_rate <= 0.15 THEN '10%-15%(medium)' WHEN change_failure_rate > 0.15 THEN '> 15%(low)' ELSE 'N/A. Please check if you have collected deployments/incidents.' END WHEN ('$dora_report') = '2021' THEN CASE WHEN is_collected = 'No All' THEN 'N/A. Please check if you have collected deployments/incidents.' WHEN is_collected = 'No Incidents' THEN 'N/A. Please check if you have collected incidents.' WHEN is_collected = 'No Deployments' THEN 'N/A. Please check if you have collected deployments.' WHEN change_failure_rate <= 0.15 THEN '0-15%(elite)' WHEN change_failure_rate <= 0.20 THEN '16%-20%(high)' WHEN change_failure_rate <= 0.30 THEN '21%-30%(medium)' WHEN change_failure_rate > 0.30 THEN '> 30%(low)' ELSE 'N/A. Please check if you have collected deployments/incidents.' END ELSE 'Invalid dora report' END AS change_failure_rate FROM _change_failure_rate, \"_is_collected_data\""
    }
   ]
  },
  {
   "title": "Step 3. The sequence of DEPLOYMENTS and INCIDENTS",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 108 },
   "targets": [
    {
     "rawSql": "WITH _deployments AS (SELECT DISTINCT d.cicd_deployment_id AS deployment_id, d.result, d.environment, d.finished_date, d.cicd_scope_id, pm.project_name FROM cicd_deployment_commits AS d JOIN project_mapping AS pm ON d.cicd_scope_id = pm.row_id AND pm.\"table\" = 'cicd_scopes' WHERE d.result /* only result needs to specified, not environment */ = 'SUCCESS' /* choose your project_name */ AND ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[]))), _incidents AS (SELECT DISTINCT i.id AS issue_id, i.created_date, pm.project_name FROM incidents AS i JOIN project_mapping AS pm ON i.scope_id = pm.row_id AND i.\"table\" = pm.\"table\" WHERE pm.project_name /* choose your project_name */ IN ($project)) SELECT deployment_id AS id, 'DEPLOYMENT' AS type, finished_date AS time FROM _deployments UNION SELECT issue_id AS id, 'INCIDENT' AS type, created_date AS time FROM _incidents ORDER BY time NULLS FIRST"
    }
   ]
  },
  {
   "title": "Step 4. Check if the DEPLOYMENT and INCIDENT mapping results are consistent with them in step 3 and figure 7&8",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 108 },
   "targets": [
    {
     "rawSql": "SELECT cdc.cicd_deployment_id AS deployment_id /* in CFR we use deployment_commit_id as the deployment_id in a specific repo */, cdc.finished_date, pim.id AS incident_id, CASE WHEN NOT pim.id IS NULL THEN 'TRUE' ELSE 'FALSE' END AS has_failure FROM cicd_deployment_commits AS cdc LEFT JOIN project_incident_deployment_relationships AS pim ON cdc.cicd_deployment_id = pim.deployment_id LEFT JOIN project_mapping AS pm ON cdc.cicd_scope_id = pm.row_id AND pm.\"table\" = 'cicd_scopes' WHERE ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND $__timeFilter(cdc.finished_date) ORDER BY 2 DESC NULLS LAST"
    }
   ]
  },
  {
   "title": "Figure 8 - Change Failure Rate",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "/* Metric 3: change failure rate per month */ WITH _deployments AS (/* When deploying multiple commits in one pipeline, GitLab and BitBucket may generate more than one deployment. However, DevLake consider these deployments as ONE production deployment and use the last one's finished_date as the finished date. */ SELECT cdc.cicd_deployment_id AS deployment_id, MAX(cdc.finished_date) AS deployment_finished_date FROM cicd_deployment_commits AS cdc JOIN project_mapping AS pm ON cdc.cicd_scope_id = pm.row_id AND pm.\"table\" = 'cicd_scopes' WHERE ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND cdc.result = 'SUCCESS' AND cdc.environment = 'PRODUCTION' GROUP BY 1 HAVING MAX(cdc.finished_date) BETWEEN $__timeFrom() AND $__timeTo()), _failure_caused_by_deployments AS (/* calculate the number of incidents caused by each deployment */ SELECT d.deployment_id, d.deployment_finished_date, COUNT(DISTINCT CASE WHEN NOT i.id IS NULL THEN d.deployment_id ELSE NULL END) AS has_incident FROM _deployments AS d LEFT JOIN project_incident_deployment_relationships AS pim ON d.deployment_id = pim.deployment_id LEFT JOIN incidents AS i ON pim.id = i.id GROUP BY 1, 2), _change_failure_rate_for_each_month AS (SELECT TO_CHAR(CAST(deployment_finished_date AS TIMESTAMP), 'YY/MM') AS month, CASE WHEN COUNT(deployment_id) IS NULL THEN NULL ELSE CAST(SUM(has_incident) AS NUMERIC) / NULLIF(COUNT(deployment_id), 0) END AS change_failure_rate FROM _failure_caused_by_deployments GROUP BY 1) SELECT cm.month, cfr.change_failure_rate AS \"Change Failure Rate\" FROM calendar_months AS cm LEFT JOIN _change_failure_rate_for_each_month AS cfr ON cm.month = cfr.month WHERE month_timestamp BETWEEN CAST(TO_CHAR(CAST($__timeFrom() AS TIMESTAMP), 'YYYY-MM-01') AS DATE) AND CAST(TO_CHAR(CAST($__timeTo() AS TIMESTAMP), 'YYYY-MM-01') AS DATE)"
    }
   ]
  }
 ]
}