{
 "title": "Engineering Throughput and Cycle Time - Team View",
 "tags": [ "Engineering Leads Dashboard" ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "SELECT DISTINCT name FROM projects"
   },
   {
    "name": "team1",
    "label": "Team1",
    "query": "SELECT name || '--' || id AS text FROM teams"
   },
   {
    "name": "team2",
    "label": "Team2",
    "query": "SELECT name || '--' || id AS text FROM teams"
   },
   {
    "name": "priority",
    "label": "P0+P1 Priority",
    "query": "SELECT DISTINCT priority FROM issues WHERE priority <> ''"
   },
   {
    "name": "interval",
    "label": "Time Interval",
    "query": "Month : DAYOFMONTH, Week : WEEKDAY"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Introduction",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "- Use Cases: This dashboard shows the engineering throughput and and cycle time, which helps to identify productivity and bottlenecks of the development process.\n- Data Sources Required:\n   - One of the Git tools, e.g. [GitHub](https://devlake.apache.org/docs/Configuration/GitHub), [GitLab](https://devlake.apache.org/docs/Configuration/GitLab), [Bitbucket](https://devlake.apache.org/docs/Configuration/BitBucket) or [Azure DevOps](https://devlake.apache.org/docs/Configuration/AzureDevOps)\n   - One of the issue tracking tools, e.g. [Jira](https://devlake.apache.org/docs/Configuration/Jira) ([Scope Config](https://devlake.apache.org/docs/UserManuals/ConfigUI/Jira#step-3---adding-transformation-rules-optional) required to tell DevLake what the story_points field is)\n- You also need to do [team configuration](https://devlake.apache.org/docs/Configuration/TeamConfiguration) to use this dashboard."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "1. Total and Avg PRs Opened/Merged",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total PRs Opened",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "WITH _prs AS (SELECT pr.id, pr.url, pr.created_date, pr.merged_date, pr.author_id, u.id AS user_id, u.name AS user_name, t.id AS team_id, t.name AS team FROM pull_requests AS pr JOIN user_accounts AS ua ON pr.author_id = ua.account_id JOIN users AS u ON ua.user_id = u.id JOIN team_users AS tu ON u.id = tu.user_id JOIN teams AS t ON tu.team_id = t.id JOIN project_mapping AS pm ON pr.base_repo_id = pm.row_id AND pm.table = 'repos' WHERE $__timeFilter(pr.created_date) AND ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[]))) SELECT CAST(created_date AS DATE) + INTERVAL '1 DAY' * (-CASE WHEN '$interval' = 'DAYOFMONTH' THEN EXTRACT(DAY FROM CAST(created_date AS DATE)) ELSE (EXTRACT(ISODOW FROM CAST(created_date AS DATE)) - 1) END + 1) AS time, COUNT(DISTINCT CASE WHEN ('${team1:csv}' = '' OR team_id::text = ANY(ARRAY[${team1:singlequote}]::text[])) THEN id ELSE NULL END) AS \"Team1: Total PR Opened\", COUNT(DISTINCT CASE WHEN ('${team2:csv}' = '' OR team_id::text = ANY(ARRAY[${team2:singlequote}]::text[])) THEN id ELSE NULL END) AS \"Team2: Total PR Opened\" FROM _prs GROUP BY 1"
    }
   ]
  },
  {
   "title": "PRs Opened per Member",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "rawSql": "WITH _prs AS (SELECT pr.id, pr.url, pr.created_date, pr.merged_date, pr.author_id, u.id AS user_id, u.name AS user_name, t.id AS team_id, t.name AS team FROM pull_requests AS pr JOIN project_mapping AS pm ON pr.base_repo_id = pm.row_id AND pm.table = 'repos' JOIN user_accounts AS ua ON pr.author_id = ua.account_id JOIN users AS u ON ua.user_id = u.id JOIN team_users AS tu ON u.id = tu.user_id JOIN teams AS t ON tu.team_id = t.id WHERE $__timeFilter(pr.created_date) AND ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[]))) SELECT CAST(created_date AS DATE) + INTERVAL '1 DAY' * (-CASE WHEN '$interval' = 'DAYOFMONTH' THEN EXTRACT(DAY FROM CAST(created_date AS DATE)) ELSE (EXTRACT(ISODOW FROM CAST(created_date AS DATE)) - 1) END + 1) AS time, CAST(COUNT(DISTINCT CASE WHEN ('${team1:csv}' = '' OR team_id::text = ANY(ARRAY[${team1:singlequote}]::text[])) THEN id ELSE NULL END) AS NUMERIC) / NULLIF((SELECT COUNT(DISTINCT user_id) FROM team_users WHERE ('${team1:csv}' = '' OR team_id::text = ANY(ARRAY[${team1:singlequote}]::text[]))), 0) AS \"Team1: PR Opened per Member\", CAST(COUNT(DISTINCT CASE WHEN ('${team2:csv}' = '' OR team_id::text = ANY(ARRAY[${team2:singlequote}]::text[])) THEN id ELSE NULL END) AS NUMERIC) / NULLIF((SELECT COUNT(DISTINCT user_id) FROM team_users WHERE ('${team2:csv}' = '' OR team_id::text = ANY(ARRAY[${team2:singlequote}]::text[]))), 0) AS \"Team2: PR Opened per Member\", CAST(COUNT(DISTINCT id) AS NUMERIC) / NULLIF((SELECT COUNT(*) FROM users), 0) AS \"Org: PR Opened per Member\" FROM _prs GROUP BY 1"
    }
   ]
  },
  {
   "title": "Total PRs Merged",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "WITH _prs AS (SELECT pr.id, pr.url, pr.created_date, pr.merged_date, pr.author_id, u.id AS user_id, u.name AS user_name, t.id AS team_id, t.name AS team FROM pull_requests AS pr JOIN project_mapping AS pm ON pr.base_repo_id = pm.row_id AND pm.table = 'repos' JOIN user_accounts AS ua ON pr.author_id = ua.account_id JOIN users AS u ON ua.user_id = u.id JOIN team_users AS tu ON u.id = tu.user_id JOIN teams AS t ON tu.team_id = t.id WHERE $__timeFilter(pr.created_date) AND ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[]))) SELECT CAST(created_date AS DATE) + INTERVAL '1 DAY' * (-CASE WHEN '$interval' = 'DAYOFMONTH' THEN EXTRACT(DAY FROM CAST(created_date AS DATE)) ELSE (EXTRACT(ISODOW FROM CAST(created_date AS DATE)) - 1) END + 1) AS time, COUNT(DISTINCT CASE WHEN ('${team1:csv}' = '' OR team_id::text = ANY(ARRAY[${team1:singlequote}]::text[])) AND NOT merged_date IS NULL THEN id WHEN ('${team1:csv}' = '' OR team_id::text = ANY(ARRAY[${team1:singlequote}]::text[])) AND merged_date IS NULL THEN NULL END) AS \"Team1: Total PR Merged\", COUNT(DISTINCT CASE WHEN ('${team2:csv}' = '' OR team_id::text = ANY(ARRAY[${team2:singlequote}]::text[])) AND NOT merged_date IS NULL THEN id WHEN ('${team2:csv}' = '' OR team_id::text = ANY(ARRAY[${team2:singlequote}]::text[])) AND merged_date IS NULL THEN NULL END) AS \"Team2: Total PR Merged\" FROM _prs GROUP BY 1"
    }
   ]
  },
  {
   "title": "PRs Merged per Member",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "WITH _prs AS (SELECT pr.id, pr.url, pr.created_date, pr.merged_date, pr.author_id, u.id AS user_id, u.name AS user_name, t.id AS team_id, t.name AS team FROM pull_requests AS pr JOIN project_mapping AS pm ON pr.base_repo_id = pm.row_id AND pm.table = 'repos' JOIN user_accounts AS ua ON pr.author_id = ua.account_id JOIN users AS u ON ua.user_id = u.id JOIN team_users AS tu ON u.id = tu.user_id JOIN teams AS t ON tu.team_id = t.id WHERE $__timeFilter(pr.created_date) AND ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[]))) SELECT CAST(created_date AS DATE) + INTERVAL '1 DAY' * (-CASE WHEN '$interval' = 'DAYOFMONTH' THEN EXTRACT(DAY FROM CAST(created_date AS DATE)) ELSE (EXTRACT(ISODOW FROM CAST(created_date AS DATE)) - 1) END + 1) AS time, CAST(COUNT(DISTINCT CASE WHEN ('${team1:csv}' = '' OR team_id::text = ANY(ARRAY[${team1:singlequote}]::text[])) AND NOT merged_date IS NULL THEN id WHEN ('${team1:csv}' = '' OR team_id::text = ANY(ARRAY[${team1:singlequote}]::text[])) AND merged_date IS NULL THEN NULL END) AS NUMERIC) / NULLIF((SELECT COUNT(DISTINCT user_id) FROM team_users WHERE ('${team1:csv}' = '' OR team_id::text = ANY(ARRAY[${team1:singlequote}]::text[]))), 0) AS \"Team1: PR Merged per Member\", CAST(COUNT(DISTINCT CASE WHEN ('${team2:csv}' = '' OR team_id::text = ANY(ARRAY[${team2:singlequote}]::text[])) AND NOT merged_date IS NULL THEN id WHEN ('${team2:csv}' = '' OR team_id::text = ANY(ARRAY[${team2:singlequote}]::text[])) AND merged_date IS NULL THEN NULL END) AS NUMERIC) / NULLIF((SELECT COUNT(DISTINCT user_id) FROM team_users WHERE ('${team2:csv}' = '' OR team_id::text = ANY(ARRAY[${team2:singlequote}]::text[]))), 0) AS \"Team2: PR Merged per Member\", CAST(COUNT(DISTINCT CASE WHEN NOT merged_date IS NULL THEN id END) AS NUMERIC) / NULLIF((SELECT COUNT(*) FROM users), 0) AS \"Org: PR Merged per Member\" FROM _prs GROUP BY 1"
    }
   ]
  },
  {
   "title": "2. Issue Completed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Issue Completed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "WITH _issues AS (SELECT i.id, i.url, i.created_date, i.status, i.assignee_id, i.story_point, i.priority, u.id AS user_id, u.name AS user_name, t.id AS team_id, t.name AS team FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id JOIN project_mapping AS pm ON b.id = pm.row_id JOIN user_accounts AS ua ON i.assignee_id = ua.account_id JOIN users AS u ON ua.user_id = u.id JOIN team_users AS tu ON u.id = tu.user_id JOIN teams AS t ON tu.team_id = t.id WHERE $__timeFilter(i.created_date) AND ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[]))) SELECT CAST(created_date AS DATE) + INTERVAL '1 DAY' * (-CASE WHEN '$interval' = 'DAYOFMONTH' THEN EXTRACT(DAY FROM CAST(created_date AS DATE)) ELSE (EXTRACT(ISODOW FROM CAST(created_date AS DATE)) - 1) END + 1) AS time, COUNT(DISTINCT CASE WHEN status = 'DONE' AND ('${team1:csv}' = '' OR team_id::text = ANY(ARRAY[${team1:singlequote}]::text[])) THEN id ELSE NULL END) AS \"Team1: Issues Completed\" /* count(i.id) AS \"Issues Opened\", */, COUNT(DISTINCT CASE WHEN status = 'DONE' AND ('${team2:csv}' = '' OR team_id::text = ANY(ARRAY[${team2:singlequote}]::text[])) THEN id ELSE NULL END) AS \"Team2: Issues Completed\" FROM _issues GROUP BY 1"
    }
   ]
  },
  {
   "title": "Issue Completed per Member",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "rawSql": "WITH _issues AS (SELECT DISTINCT i.id, i.url, i.created_date, i.status, i.assignee_id, i.story_point, i.priority, u.id AS user_id, u.name AS user_name, t.id AS team_id, t.name AS team FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id JOIN project_mapping AS pm ON b.id = pm.row_id JOIN user_accounts AS ua ON i.assignee_id = ua.account_id JOIN users AS u ON ua.user_id = u.id JOIN team_users AS tu ON u.id = tu.user_id JOIN teams AS t ON tu.team_id = t.id WHERE $__timeFilter(i.created_date) AND ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) ORDER BY 1 NULLS FIRST) SELECT CAST(created_date AS DATE) + INTERVAL '1 DAY' * (-CASE WHEN '$interval' = 'DAYOFMONTH' THEN EXTRACT(DAY FROM CAST(created_date AS DATE)) ELSE (EXTRACT(ISODOW FROM CAST(created_date AS DATE)) - 1) END + 1) AS time, CAST(COUNT(DISTINCT CASE WHEN status = 'DONE' AND ('${team1:csv}' = '' OR team_id::text = ANY(ARRAY[${team1:singlequote}]::text[])) THEN id ELSE NULL END) AS NUMERIC) / NULLIF((SELECT COUNT(DISTINCT user_id) FROM team_users WHERE ('${team1:csv}' = '' OR team_id::text = ANY(ARRAY[${team1:singlequote}]::text[]))), 0) AS \"Team1: Issues Completed per Member\", CAST(COUNT(DISTINCT CASE WHEN status = 'DONE' AND ('${team2:csv}' = '' OR team_id::text = ANY(ARRAY[${team2:singlequote}]::text[])) THEN id ELSE NULL END) AS NUMERIC) / NULLIF((SELECT COUNT(DISTINCT user_id) FROM team_users WHERE ('${team2:csv}' = '' OR team_id::text = ANY(ARRAY[${team2:singlequote}]::text[]))), 0) AS \"Team2: Issues Completed per Member\", CAST(COUNT(DISTINCT id) AS NUMERIC) / NULLIF((SELECT COUNT(*) FROM users), 0) AS \"Org: Issues Completed per Member\" FROM _issues GROUP BY 1"
    }
   ]
  },
  {
   "title": "3. Story Points Completed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Story Points Completed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "WITH _issues AS (SELECT DISTINCT i.id, i.url, i.created_date, i.status, i.assignee_id, i.story_point, i.priority, u.id AS user_id, u.name AS user_name, t.id AS team_id, t.name AS team FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id JOIN project_mapping AS pm ON b.id = pm.row_id JOIN user_accounts AS ua ON i.assignee_id = ua.account_id JOIN users AS u ON ua.user_id = u.id JOIN team_users AS tu ON u.id = tu.user_id JOIN teams AS t ON tu.team_id = t.id WHERE $__timeFilter(i.created_date) AND ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) ORDER BY 1 NULLS FIRST) SELECT CAST(created_date AS DATE) + INTERVAL '1 DAY' * (-CASE WHEN '$interval' = 'DAYOFMONTH' THEN EXTRACT(DAY FROM CAST(created_date AS DATE)) ELSE (EXTRACT(ISODOW FROM CAST(created_date AS DATE)) - 1) END + 1) AS time, SUM(CASE WHEN status = 'DONE' AND ('${team1:csv}' = '' OR team_id::text = ANY(ARRAY[${team1:singlequote}]::text[])) THEN story_point ELSE 0 END) AS \"Team1: Story Points Completed\" /* count(i.id) AS \"Issues Opened\", */, SUM(CASE WHEN status = 'DONE' AND ('${team2:csv}' = '' OR team_id::text = ANY(ARRAY[${team2:singlequote}]::text[])) THEN story_point ELSE 0 END) AS \"Team2: Story Points Completed\" FROM _issues GROUP BY 1"
    }
   ]
  },
  {
   "title": "Story Points Completed per Member",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "rawSql": "WITH _issues AS (SELECT DISTINCT i.id, i.url, i.created_date, i.status, i.assignee_id, i.story_point, i.priority, u.id AS user_id, u.name AS user_name, t.id AS team_id, t.name AS team FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id JOIN project_mapping AS pm ON b.id = pm.row_id JOIN user_accounts AS ua ON i.assignee_id = ua.account_id JOIN users AS u ON ua.user_id = u.id JOIN team_users AS tu ON u.id = tu.user_id JOIN teams AS t ON tu.team_id = t.id WHERE $__timeFilter(i.created_date) AND ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) ORDER BY 1 NULLS FIRST) SELECT CAST(created_date AS DATE) + INTERVAL '1 DAY' * (-CASE WHEN '$interval' = 'DAYOFMONTH' THEN EXTRACT(DAY FROM CAST(created_date AS DATE)) ELSE (EXTRACT(ISODOW FROM CAST(created_date AS DATE)) - 1) END + 1) AS time, CAST(SUM(CASE WHEN status = 'DONE' AND ('${team1:csv}' = '' OR team_id::text = ANY(ARRAY[${team1:singlequote}]::text[])) THEN story_point ELSE 0 END) AS NUMERIC) / NULLIF((SELECT COUNT(DISTINCT user_id) FROM team_users WHERE ('${team1:csv}' = '' OR team_id::text = ANY(ARRAY[${team1:singlequote}]::text[]))), 0) AS \"Team1: Story Points Completed per Member\", CAST(SUM(CASE WHEN status = 'DONE' AND ('${team2:csv}' = '' OR team_id::text = ANY(ARRAY[${team2:singlequote}]::text[])) THEN story_point ELSE 0 END) AS NUMERIC) / NULLIF((SELECT COUNT(DISTINCT user_id) FROM team_users WHERE ('${team2:csv}' = '' OR team_id::text = ANY(ARRAY[${team2:singlequote}]::text[]))), 0) AS \"Team2: Story Points Completed per Member\", CAST(COUNT(DISTINCT id) AS NUMERIC) / NULLIF((SELECT COUNT(*) FROM users), 0) AS \"Org: Story Points Completed per Member\" FROM _issues GROUP BY 1"
    }
   ]
  },
  {
   "title": "4. PR Review Depth and PR Merged Size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {}
   ]
  },
  {
   "title": " Average PR Review Depth per Team",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "WITH _merged_prs AS (SELECT DISTINCT pr.id, pr.url, pr.created_date, pr.merged_date, pr.author_id, prc.id AS comment_id, u.id AS user_id, u.name AS user_name, t.id AS team_id, t.name AS team FROM pull_requests AS pr JOIN project_mapping AS pm ON pr.base_repo_id = pm.row_id AND pm.table = 'repos' LEFT JOIN pull_request_comments AS prc ON pr.id = prc.pull_request_id JOIN user_accounts AS ua ON pr.author_id = ua.account_id JOIN users AS u ON ua.user_id = u.id JOIN team_users AS tu ON u.id = tu.user_id JOIN teams AS t ON tu.team_id = t.id WHERE $__timeFilter(pr.created_date) AND ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND NOT pr.merged_date IS NULL ORDER BY 1 NULLS FIRST) SELECT CAST(created_date AS DATE) + INTERVAL '1 DAY' * (-CASE WHEN '$interval' = 'DAYOFMONTH' THEN EXTRACT(DAY FROM CAST(created_date AS DATE)) ELSE (EXTRACT(ISODOW FROM CAST(created_date AS DATE)) - 1) END + 1) AS time, CAST(COUNT(DISTINCT CASE WHEN ('${team1:csv}' = '' OR team_id::text = ANY(ARRAY[${team1:singlequote}]::text[])) THEN comment_id ELSE NULL END) AS NUMERIC) / NULLIF((SELECT COUNT(DISTINCT user_id) FROM team_users WHERE ('${team1:csv}' = '' OR team_id::text = ANY(ARRAY[${team1:singlequote}]::text[]))), 0) AS \"Team1: PR Review Depth\", CAST(COUNT(DISTINCT CASE WHEN ('${team2:csv}' = '' OR team_id::text = ANY(ARRAY[${team2:singlequote}]::text[])) THEN comment_id ELSE NULL END) AS NUMERIC) / NULLIF((SELECT COUNT(DISTINCT user_id) FROM team_users WHERE ('${team2:csv}' = '' OR team_id::text = ANY(ARRAY[${team2:singlequote}]::text[]))), 0) AS \"Team2: PR Review Depth\", CAST(COUNT(DISTINCT comment_id) AS NUMERIC) / NULLIF((SELECT COUNT(*) FROM users), 0) AS \"Org: PR Review Depth\" FROM _merged_prs GROUP BY 1"
    }
   ]
  },
  {
   "title": " Average PR Merged Size by Team",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "rawSql": "WITH _prs AS (SELECT DISTINCT pr.id, pr.url, pr.created_date, pr.merged_date, pr.author_id, pr.merge_commit_sha, c.additions + c.deletions AS loc, u.id AS user_id, u.name AS user_name, t.id AS team_id, t.name AS team FROM pull_requests AS pr JOIN project_mapping AS pm ON pr.base_repo_id = pm.row_id AND pm.table = 'repos' LEFT JOIN commits AS c ON pr.merge_commit_sha = c.sha JOIN user_accounts AS ua ON pr.author_id = ua.account_id JOIN users AS u ON ua.user_id = u.id JOIN team_users AS tu ON u.id = tu.user_id JOIN teams AS t ON tu.team_id = t.id WHERE $__timeFilter(pr.created_date) AND ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND pr.status = 'MERGED' ORDER BY 1 NULLS FIRST) SELECT CAST(created_date AS DATE) + INTERVAL '1 DAY' * (-CASE WHEN '$interval' = 'DAYOFMONTH' THEN EXTRACT(DAY FROM CAST(created_date AS DATE)) ELSE (EXTRACT(ISODOW FROM CAST(created_date AS DATE)) - 1) END + 1) AS time, CAST(SUM(CASE WHEN ('${team1:csv}' = '' OR team_id::text = ANY(ARRAY[${team1:singlequote}]::text[])) THEN loc ELSE NULL END) AS NUMERIC) / NULLIF((SELECT COUNT(DISTINCT user_id) FROM team_users WHERE ('${team1:csv}' = '' OR team_id::text = ANY(ARRAY[${team1:singlequote}]::text[]))), 0) AS \"Team1: PR Size\", CAST(SUM(CASE WHEN ('${team2:csv}' = '' OR team_id::text = ANY(ARRAY[${team2:singlequote}]::text[])) THEN loc ELSE NULL END) AS NUMERIC) / NULLIF((SELECT COUNT(DISTINCT user_id) FROM team_users WHERE ('${team2:csv}' = '' OR team_id::text = ANY(ARRAY[${team2:singlequote}]::text[]))), 0) AS \"Team2: PR Size\", CAST(SUM(loc) AS NUMERIC) / NULLIF((SELECT COUNT(*) FROM users), 0) AS \"Org: PR Merged Size\" FROM _prs GROUP BY 1 ORDER BY 1 NULLS FIRST"
    }
   ]
  },
  {
   "title": "5. P0/P1 Bugs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total P0/P1 Bugs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "rawSql": "WITH _bugs AS (SELECT DISTINCT i.id, i.url, i.created_date, i.status, i.assignee_id, i.story_point, i.priority, u.id AS user_id, u.name AS user_name, t.id AS team_id, t.name AS team FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id JOIN project_mapping AS pm ON b.id = pm.row_id JOIN user_accounts AS ua ON i.assignee_id = ua.account_id JOIN users AS u ON ua.user_id = u.id JOIN team_users AS tu ON u.id = tu.user_id JOIN teams AS t ON tu.team_id = t.id WHERE $__timeFilter(i.created_date) AND ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND i.type = 'BUG' ORDER BY 1 NULLS FIRST) SELECT CAST(created_date AS DATE) + INTERVAL '1 DAY' * (-CASE WHEN '$interval' = 'DAYOFMONTH' THEN EXTRACT(DAY FROM CAST(created_date AS DATE)) ELSE (EXTRACT(ISODOW FROM CAST(created_date AS DATE)) - 1) END + 1) AS time, COUNT(CASE WHEN ('${team1:csv}' = '' OR team_id::text = ANY(ARRAY[${team1:singlequote}]::text[])) THEN id ELSE NULL END) AS \"Team1: P0/P1 Bugs\", COUNT(CASE WHEN ('${team2:csv}' = '' OR team_id::text = ANY(ARRAY[${team2:singlequote}]::text[])) THEN id ELSE NULL END) AS \"Team2: P0/P1 Bugs\" FROM _bugs WHERE priority /* please choose the priorities in the filter above */ IN (${priority}) GROUP BY 1 ORDER BY 1 NULLS FIRST"
    }
   ]
  },
  {
   "title": "P0/P1 Bugs per Member",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "rawSql": "WITH _bugs AS (SELECT DISTINCT i.id, i.url, i.created_date, i.status, i.assignee_id, i.story_point, i.priority, u.id AS user_id, u.name AS user_name, t.id AS team_id, t.name AS team FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id JOIN project_mapping AS pm ON b.id = pm.row_id JOIN user_accounts AS ua ON i.assignee_id = ua.account_id JOIN users AS u ON ua.user_id = u.id JOIN team_users AS tu ON u.id = tu.user_id JOIN teams AS t ON tu.team_id = t.id WHERE $__timeFilter(i.created_date) AND ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND i.type = 'BUG' ORDER BY 1 NULLS FIRST) SELECT CAST(created_date AS DATE) + INTERVAL '1 DAY' * (-CASE WHEN '$interval' = 'DAYOFMONTH' THEN EXTRACT(DAY FROM CAST(created_date AS DATE)) ELSE (EXTRACT(ISODOW FROM CAST(created_date AS DATE)) - 1) END + 1) AS time, CAST(COUNT(CASE WHEN ('${team1:csv}' = '' OR team_id::text = ANY(ARRAY[${team1:singlequote}]::text[])) THEN id ELSE NULL END) AS NUMERIC) / NULLIF((SELECT COUNT(DISTINCT user_id) FROM team_users WHERE ('${team1:csv}' = '' OR team_id::text = ANY(ARRAY[${team1:singlequote}]::text[]))), 0) AS \"Team1: P0/P1 Bugs per Member\", CAST(COUNT(CASE WHEN ('${team2:csv}' = '' OR team_id::text = ANY(ARRAY[${team2:singlequote}]::text[])) THEN id ELSE NULL END) AS NUMERIC) / NULLIF((SELECT COUNT(DISTINCT user_id) FROM team_users WHERE ('${team2:csv}' = '' OR team_id::text = ANY(ARRAY[${team2:singlequote}]::text[]))), 0) AS \"Team2: P0/P1 Bugs per Member\", CAST(COUNT(DISTINCT id) AS NUMERIC) / NULLIF((SELECT COUNT(*) FROM users), 0) AS \"Org: P0/P1 Bugs per Member\" FROM _bugs WHERE priority /* please choose the priorities in the filter above */ IN (${priority}) GROUP BY 1 ORDER BY 1 NULLS FIRST"
    }
   ]
  },
  {
   "title": "6. Cycle Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Cycle Time(h)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "rawSql": "WITH _prs AS (SELECT pr.id, pr.merged_date AS pr_merged_date, COALESCE(CAST(prm.pr_cycle_time AS NUMERIC) / NULLIF(60, 0), 0) AS cycle_time /* convert null to 0 if a PR has no cycle_time to make sure cycle_time equals the sum of the four metrics below */, pr.author_id, u.id AS user_id, u.name AS user_name, t.id AS team_id, t.name AS team FROM pull_requests AS pr JOIN project_mapping AS pm ON pr.base_repo_id = pm.row_id AND pm.table = 'repos' LEFT JOIN project_pr_metrics AS prm ON pr.id = prm.id LEFT JOIN user_accounts AS ua ON pr.author_id = ua.account_id LEFT JOIN users AS u ON ua.user_id = u.id LEFT JOIN team_users AS tu ON u.id = tu.user_id LEFT JOIN teams AS t ON tu.team_id = t.id WHERE $__timeFilter(pr.merged_date) AND ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) GROUP BY 1, 2, 3, 4, 5, 6, 7, 8) SELECT CAST(pr_merged_date AS DATE) + INTERVAL '1 DAY' * (-CASE WHEN '$interval' = 'DAYOFMONTH' THEN EXTRACT(DAY FROM CAST(pr_merged_date AS DATE)) ELSE (EXTRACT(ISODOW FROM CAST(pr_merged_date AS DATE)) - 1) END + 1) AS time, AVG(CASE WHEN ('${team1:csv}' = '' OR team_id::text = ANY(ARRAY[${team1:singlequote}]::text[])) THEN cycle_time END) AS \"Team1: Avg Cycle Time(h)\", AVG(CASE WHEN ('${team2:csv}' = '' OR team_id::text = ANY(ARRAY[${team2:singlequote}]::text[])) THEN cycle_time END) AS \"Team2: Avg Cycle Time(h)\" FROM _prs GROUP BY 1 ORDER BY 1 NULLS FIRST"
    }
   ]
  },
  {
   "title": "PR Coding Time(h)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 58 },
   "targets": [
    {
     "rawSql": "WITH _prs AS (SELECT pr.id, pr.merged_date AS pr_merged_date, COALESCE(CAST(prm.pr_coding_time AS NUMERIC) / NULLIF(60, 0), 0) AS coding_time /* convert null to 0 if a PR has no coding_time to make sure cycle_time equals the sum of the four sub-metrics */, pr.author_id, u.id AS user_id, u.name AS user_name, t.id AS team_id, t.name AS team FROM pull_requests AS pr JOIN project_mapping AS pm ON pr.base_repo_id = pm.row_id AND pm.table = 'repos' LEFT JOIN project_pr_metrics AS prm ON pr.id = prm.id LEFT JOIN user_accounts AS ua ON pr.author_id = ua.account_id LEFT JOIN users AS u ON ua.user_id = u.id LEFT JOIN team_users AS tu ON u.id = tu.user_id LEFT JOIN teams AS t ON tu.team_id = t.id WHERE $__timeFilter(pr.merged_date) AND ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) GROUP BY 1, 2, 3, 4, 5, 6, 7, 8) SELECT CAST(pr_merged_date AS DATE) + INTERVAL '1 DAY' * (-CASE WHEN '$interval' = 'DAYOFMONTH' THEN EXTRACT(DAY FROM CAST(pr_merged_date AS DATE)) ELSE (EXTRACT(ISODOW FROM CAST(pr_merged_date AS DATE)) - 1) END + 1) AS time, AVG(CASE WHEN ('${team1:csv}' = '' OR team_id::text = ANY(ARRAY[${team1:singlequote}]::text[])) THEN coding_time END) AS \"Team1: Avg Coding Time(h)\", AVG(CASE WHEN ('${team2:csv}' = '' OR team_id::text = ANY(ARRAY[${team2:singlequote}]::text[])) THEN coding_time END) AS \"Team2: Avg Coding Time(h)\" FROM _prs GROUP BY 1 ORDER BY 1 NULLS FIRST"
    }
   ]
  },
  {
   "title": "PR Pickup Time(h)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 58 },
   "targets": [
    {
     "rawSql": "WITH _prs AS (SELECT pr.id, pr.merged_date AS pr_merged_date, COALESCE(CAST(prm.pr_pickup_time AS NUMERIC) / NULLIF(60, 0), 0) AS pickup_time /* convert null to 0 if a PR has no pickup_time to make sure cycle_time equals the sum of the four sub-metrics */, pr.author_id, u.id AS user_id, u.name AS user_name, t.id AS team_id, t.name AS team FROM pull_requests AS pr JOIN project_mapping AS pm ON pr.base_repo_id = pm.row_id AND pm.table = 'repos' LEFT JOIN project_pr_metrics AS prm ON pr.id = prm.id LEFT JOIN user_accounts AS ua ON pr.author_id = ua.account_id LEFT JOIN users AS u ON ua.user_id = u.id LEFT JOIN team_users AS tu ON u.id = tu.user_id LEFT JOIN teams AS t ON tu.team_id = t.id WHERE $__timeFilter(pr.merged_date) AND ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) GROUP BY 1, 2, 3, 4, 5, 6, 7, 8) SELECT CAST(pr_merged_date AS DATE) + INTERVAL '1 DAY' * (-CASE WHEN '$interval' = 'DAYOFMONTH' THEN EXTRACT(DAY FROM CAST(pr_merged_date AS DATE)) ELSE (EXTRACT(ISODOW FROM CAST(pr_merged_date AS DATE)) - 1) END + 1) AS time, AVG(CASE WHEN ('${team1:csv}' = '' OR team_id::text = ANY(ARRAY[${team1:singlequote}]::text[])) THEN pickup_time END) AS \"Team1: Avg Pickup Time(h)\", AVG(CASE WHEN ('${team2:csv}' = '' OR team_id::text = ANY(ARRAY[${team2:singlequote}]::text[])) THEN pickup_time END) AS \"Team2: Avg Pickup Time(h)\" FROM _prs GROUP BY 1 ORDER BY 1 NULLS FIRST"
    }
   ]
  },
  {
   "title": "PR Review Time(h)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 58 },
   "targets": [
    {
     "rawSql": "WITH _prs AS (SELECT pr.id, pr.merged_date AS pr_merged_date, COALESCE(CAST(prm.pr_review_time AS NUMERIC) / NULLIF(60, 0), 0) AS review_time /* convert null to 0 if a PR has no review_time to make sure cycle_time equals the sum of the four sub-metrics */, pr.author_id, u.id AS user_id, u.name AS user_name, t.id AS team_id, t.name AS team FROM pull_requests AS pr JOIN project_mapping AS pm ON pr.base_repo_id = pm.row_id AND pm.table = 'repos' LEFT JOIN project_pr_metrics AS prm ON pr.id = prm.id LEFT JOIN user_accounts AS ua ON pr.author_id = ua.account_id LEFT JOIN users AS u ON ua.user_id = u.id LEFT JOIN team_users AS tu ON u.id = tu.user_id LEFT JOIN teams AS t ON tu.team_id = t.id WHERE $__timeFilter(pr.merged_date) AND ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) GROUP BY 1, 2, 3, 4, 5, 6, 7, 8) SELECT CAST(pr_merged_date AS DATE) + INTERVAL '1 DAY' * (-CASE WHEN '$interval' = 'DAYOFMONTH' THEN EXTRACT(DAY FROM CAST(pr_merged_date AS DATE)) ELSE (EXTRACT(ISODOW FROM CAST(pr_merged_date AS DATE)) - 1) END + 1) AS time, AVG(CASE WHEN ('${team1:csv}' = '' OR team_id::text = ANY(ARRAY[${team1:singlequote}]::text[])) THEN review_time END) AS \"Team1: Avg Review Time(h)\", AVG(CASE WHEN ('${team2:csv}' = '' OR team_id::text = ANY(ARRAY[${team2:singlequote}]::text[])) THEN review_time END) AS \"Team2: Avg Review Time(h)\" FROM _prs GROUP BY 1 ORDER BY 1 NULLS FIRST"
    }
   ]
  },
  {
   "title": "PR Deploy Time(h)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 58 },
   "targets": [
    {
     "rawSql": "WITH _prs AS (SELECT pr.id, pr.merged_date AS pr_merged_date, COALESCE(CAST(prm.pr_deploy_time AS NUMERIC) / NULLIF(60, 0), 0) AS deploy_time /* convert null to 0 if a PR has no deploy_time to make sure cycle_time equals the sum of the four sub-metrics */, pr.author_id, u.id AS user_id, u.name AS user_name, t.id AS team_id, t.name AS team FROM pull_requests AS pr JOIN project_mapping AS pm ON pr.base_repo_id = pm.row_id AND pm.table = 'repos' LEFT JOIN project_pr_metrics AS prm ON pr.id = prm.id LEFT JOIN user_accounts AS ua ON pr.author_id = ua.account_id LEFT JOIN users AS u ON ua.user_id = u.id LEFT JOIN team_users AS tu ON u.id = tu.user_id LEFT JOIN teams AS t ON tu.team_id = t.id WHERE $__timeFilter(pr.merged_date) AND ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) GROUP BY 1, 2, 3, 4, 5, 6, 7, 8) SELECT CAST(pr_merged_date AS DATE) + INTERVAL '1 DAY' * (-CASE WHEN '$interval' = 'DAYOFMONTH' THEN EXTRACT(DAY FROM CAST(pr_merged_date AS DATE)) ELSE (EXTRACT(ISODOW FROM CAST(pr_merged_date AS DATE)) - 1) END + 1) AS time, AVG(CASE WHEN ('${team1:csv}' = '' OR team_id::text = ANY(ARRAY[${team1:singlequote}]::text[])) THEN deploy_time END) AS \"Team1: Avg Deploy Time(h)\", AVG(CASE WHEN ('${team2:csv}' = '' OR team_id::text = ANY(ARRAY[${team2:singlequote}]::text[])) THEN deploy_time END) AS \"Team2: Avg Deploy Time(h)\" FROM _prs GROUP BY 1 ORDER BY 1 NULLS FIRST"
    }
   ]
  },
  {
   "title": "7. PRs Merged w/o Review",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {}
   ]
  },
  {
   "title": "PRs Merged w/o Review",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "rawSql": "WITH _merged_prs AS (SELECT DISTINCT pr.id, pr.url, pr.created_date, pr.merged_date, pr.author_id, u.id AS user_id, u.name AS user_name, t.id AS team_id, t.name AS team FROM pull_requests AS pr JOIN project_mapping AS pm ON pr.base_repo_id = pm.row_id AND pm.table = 'repos' JOIN user_accounts AS ua ON pr.author_id = ua.account_id JOIN users AS u ON ua.user_id = u.id JOIN team_users AS tu ON u.id = tu.user_id JOIN teams AS t ON tu.team_id = t.id WHERE $__timeFilter(pr.created_date) AND ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND NOT pr.merged_date IS NULL ORDER BY 1 NULLS FIRST) SELECT CAST(created_date AS DATE) + INTERVAL '1 DAY' * (-CASE WHEN '$interval' = 'DAYOFMONTH' THEN EXTRACT(DAY FROM CAST(created_date AS DATE)) ELSE (EXTRACT(ISODOW FROM CAST(created_date AS DATE)) - 1) END + 1) AS time, COUNT(DISTINCT CASE WHEN ('${team1:csv}' = '' OR team_id::text = ANY(ARRAY[${team1:singlequote}]::text[])) AND NOT id IN (SELECT pull_request_id FROM pull_request_comments) THEN id ELSE NULL END) AS \"Team1: PRs Merged w/o Review\", COUNT(DISTINCT CASE WHEN ('${team2:csv}' = '' OR team_id::text = ANY(ARRAY[${team2:singlequote}]::text[])) AND NOT id IN (SELECT pull_request_id FROM pull_request_comments) THEN id ELSE NULL END) AS \"Team2: PRs Merged w/o Review\" FROM _merged_prs GROUP BY 1"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 73 },
   "options": {
    "content": "<br/>\n\nThis dashboard is created based on this [data schema](https://devlake.apache.org/docs/DataModels/DevLakeDomainLayerSchema). Want to add more metrics? Please follow the [guide](https://devlake.apache.org/docs/Configuration/Dashboards/GrafanaUserGuide)."
   },
   "targets": [
    {}
   ]
  }
 ]
}