{
 "title": "Engineering Overview",
 "tags": [
  "Engineering Leads Dashboard",
  "Highlights"
 ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "SELECT DISTINCT name FROM projects"
   },
   {
    "name": "month",
    "label": "Selected Month",
    "query": "SELECT DISTINCT (TO_CHAR(CAST(month_timestamp AS TIMESTAMP), 'YYYY-MM') || ':' || TO_CHAR(CAST(month_timestamp AS TIMESTAMP), 'YYYY-MM-DD')) AS month FROM calendar_months WHERE month_timestamp <= CURRENT_DATE ORDER BY month DESC NULLS LAST LIMIT 12"
   },
   {
    "name": "priority",
    "label": "Prioriti(es) of Critical Issues",
    "query": "SELECT DISTINCT priority FROM issues"
   },
   {
    "name": "type",
    "label": "Issue Type",
    "query": "SELECT DISTINCT type FROM issues"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Introduction",
   "type": "text",
   "gridPos": { "h": 3, "w": 13, "x": 0, "y": 0 },
   "options": {
    "content": "- Use Cases: This dashboard is to overview the Git and project management metrics.\n- Data Sources Required:\n   - One of the Git tools, e.g. [GitHub](https://devlake.apache.org/docs/Configuration/GitHub), [GitLab](https://devlake.apache.org/docs/Configuration/GitLab), [Bitbucket](https://devlake.apache.org/docs/Configuration/BitBucket) or [Azure DevOps](https://devlake.apache.org/docs/Configuration/AzureDevOps)\n   - One of the issue tracking tools, e.g. [Jira](https://devlake.apache.org/docs/Configuration/Jira)"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Critical Defects Identified [in $month]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT i.id) FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id JOIN project_mapping AS pm ON b.id = pm.row_id WHERE ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND ('${priority:csv}' = '' OR i.priority::text = ANY(ARRAY[${priority:singlequote}]::text[])) AND i.type = 'BUG' AND CAST(i.created_date AS DATE) BETWEEN TO_DATE('$month', 'YYYY-MM-DD') AND TO_DATE('$month', 'YYYY-MM-DD') + INTERVAL '1 MONTH'"
    }
   ]
  },
  {
   "title": "Critical Defects Identified over Month",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 3 },
   "targets": [
    {
     "rawSql": "WITH _issues AS (SELECT CAST(i.created_date AS DATE) + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST(i.created_date AS DATE)) + 1) AS time, COUNT(DISTINCT i.id) AS defect_count FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id JOIN project_mapping AS pm ON b.id = pm.row_id WHERE ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND ('${priority:csv}' = '' OR i.priority::text = ANY(ARRAY[${priority:singlequote}]::text[])) AND i.type = 'BUG' AND $__timeFilter(i.created_date) AND i.created_date >= $__timeFrom()::timestamp + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST($__timeFrom() AS DATE)) + 1) + INTERVAL '1 MONTH' GROUP BY time) SELECT TO_CHAR(CAST(time AS TIMESTAMP), 'FMMonth YYYY') AS month, defect_count FROM _issues ORDER BY time ASC NULLS FIRST"
    }
   ]
  },
  {
   "title": "Mean Issue Lead Time in Days [Issues Resolved in $month]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(CAST(lead_time_minutes AS NUMERIC) / NULLIF(1440, 0)) AS value FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id JOIN project_mapping AS pm ON b.id = pm.row_id WHERE ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND ('${type:csv}' = '' OR i.type::text = ANY(ARRAY[${type:singlequote}]::text[])) AND i.status = 'DONE' AND i.resolution_date BETWEEN TO_DATE('$month', 'YYYY-MM-DD') AND TO_DATE('$month', 'YYYY-MM-DD') + INTERVAL '1 MONTH'"
    }
   ]
  },
  {
   "title": "Mean Requirement Lead Time in Days [Of Issues Resolved per Month]",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "WITH _issues AS (SELECT CAST(i.resolution_date AS DATE) + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST(i.resolution_date AS DATE)) + 1) AS time, AVG(CAST(i.lead_time_minutes AS NUMERIC) / NULLIF(1440, 0)) AS issue_lead_time FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id JOIN project_mapping AS pm ON b.id = pm.row_id WHERE ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND i.status = 'DONE' AND $__timeFilter(i.resolution_date) AND i.resolution_date >= $__timeFrom()::timestamp + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST($__timeFrom() AS DATE)) + 1) + INTERVAL '1 MONTH' GROUP BY 1) SELECT TO_CHAR(CAST(time AS TIMESTAMP), 'FMMonth YYYY') AS month, issue_lead_time AS \"Mean Requirement Lead Time in Days\" FROM _issues ORDER BY time NULLS FIRST"
    }
   ]
  },
  {
   "title": "Number of Developers [in $month]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT author_name) FROM commits AS c JOIN repo_commits AS rc ON c.sha = rc.commit_sha JOIN project_mapping AS pm ON rc.repo_id = pm.row_id AND pm.table = 'repos' WHERE CAST(authored_date AS DATE) BETWEEN TO_DATE('$month', 'YYYY-MM-DD') AND TO_DATE('$month', 'YYYY-MM-DD') + INTERVAL '1 MONTH' AND ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[]))"
    }
   ]
  },
  {
   "title": "Number of Developers",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 19 },
   "targets": [
    {
     "rawSql": "WITH _developers AS (SELECT CAST(c.authored_date AS DATE) + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST(c.authored_date AS DATE)) + 1) AS time, COUNT(DISTINCT author_name) AS developer_count FROM commits AS c JOIN repo_commits AS rc ON c.sha = rc.commit_sha JOIN project_mapping AS pm ON rc.repo_id = pm.row_id AND pm.table = 'repos' WHERE $__timeFilter(c.authored_date) AND c.authored_date >= $__timeFrom()::timestamp + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST($__timeFrom() AS DATE)) + 1) + INTERVAL '1 MONTH' AND ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) GROUP BY time) SELECT TO_CHAR(CAST(time AS TIMESTAMP), 'FMMonth YYYY') AS month, developer_count FROM _developers ORDER BY time ASC NULLS FIRST"
    }
   ]
  },
  {
   "title": "On-time Delivery [in $month]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH _num_issues_with_sprint_updated AS (SELECT NULLIF(COUNT(DISTINCT i.id), 0) AS num_issues_with_sprint_updated FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id JOIN project_mapping AS pm ON b.id = pm.row_id JOIN issue_changelogs AS c ON i.id = c.issue_id WHERE ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND c.field_name = 'Sprint' AND c.original_from_value <> '' AND c.original_to_value <> '' AND CAST(i.created_date AS DATE) BETWEEN TO_DATE('$month', 'YYYY-MM-DD') AND TO_DATE('$month', 'YYYY-MM-DD') + INTERVAL '1 MONTH'), _total_num_issues AS (SELECT NULLIF(COUNT(DISTINCT i.id), 0) AS total_num_issues FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id JOIN project_mapping AS pm ON b.id = pm.row_id WHERE ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND CAST(i.created_date AS DATE) BETWEEN TO_DATE('$month', 'YYYY-MM-DD') AND TO_DATE('$month', 'YYYY-MM-DD') + INTERVAL '1 MONTH') SELECT NOW() AS time, 100 - CAST(100 * (SELECT 1.0 * num_issues_with_sprint_updated FROM _num_issues_with_sprint_updated) AS NUMERIC) / NULLIF((SELECT total_num_issues FROM _total_num_issues), 0) AS ratio"
    }
   ]
  },
  {
   "title": "On-time Delivery over Month",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH _num_issues_with_sprint_updated AS (SELECT CAST(i.created_date AS DATE) + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST(i.created_date AS DATE)) + 1) AS time, NULLIF(COUNT(DISTINCT i.id), 0) AS num_issues_with_sprint_updated FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id JOIN project_mapping AS pm ON b.id = pm.row_id JOIN issue_changelogs AS c ON i.id = c.issue_id WHERE ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND c.field_name = 'Sprint' AND c.original_from_value <> '' AND c.original_to_value <> '' AND $__timeFilter(i.created_date) AND i.created_date >= $__timeFrom()::timestamp + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST($__timeFrom() AS DATE)) + 1) + INTERVAL '1 MONTH' GROUP BY time), _total_num_issues AS (SELECT CAST(i.created_date AS DATE) + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST(i.created_date AS DATE)) + 1) AS time, NULLIF(COUNT(DISTINCT i.id), 0) AS total_num_issues FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id JOIN project_mapping AS pm ON b.id = pm.row_id WHERE ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND $__timeFilter(i.created_date) AND i.created_date >= $__timeFrom()::timestamp + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST($__timeFrom() AS DATE)) + 1) + INTERVAL '1 MONTH' GROUP BY time) SELECT x.time, 100 - 100 * (CAST(1.0 * x.num_issues_with_sprint_updated AS NUMERIC) / NULLIF(y.total_num_issues, 0)) AS delivery_rate FROM _num_issues_with_sprint_updated AS x JOIN _total_num_issues AS y ON x.time = y.time"
    }
   ]
  },
  {
   "title": "PRs merged [in $month]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT pr.id) FROM pull_requests AS pr JOIN project_mapping AS pm ON pr.base_repo_id = pm.row_id AND pm.table = 'repos' WHERE NOT pr.merged_date IS NULL AND CAST(pr.merged_date AS DATE) BETWEEN TO_DATE('$month', 'YYYY-MM-DD') AND TO_DATE('$month', 'YYYY-MM-DD') + INTERVAL '1 MONTH' AND ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[]))"
    }
   ]
  },
  {
   "title": "PRs Merged over Month",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 35 },
   "targets": [
    {
     "rawSql": "WITH _merged_prs AS (SELECT CAST(pr.merged_date AS DATE) + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST(pr.merged_date AS DATE)) + 1) AS time, COUNT(DISTINCT pr.id) AS pr_merged_count FROM pull_requests AS pr JOIN project_mapping AS pm ON pr.base_repo_id = pm.row_id AND pm.table = 'repos' WHERE ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND NOT pr.merged_date IS NULL AND $__timeFilter(pr.merged_date) AND pr.merged_date >= $__timeFrom()::timestamp + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST($__timeFrom() AS DATE)) + 1) + INTERVAL '1 MONTH' GROUP BY time) SELECT TO_CHAR(CAST(time AS TIMESTAMP), 'FMMonth YYYY') AS month, pr_merged_count FROM _merged_prs ORDER BY time ASC NULLS FIRST"
    }
   ]
  },
  {
   "title": "Unlinked PRs % [in $month]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CAST(100 * COUNT(DISTINCT CASE WHEN pr.id IN (SELECT pull_request_id FROM pull_request_issues) THEN pr.id ELSE NULL END) AS NUMERIC) / NULLIF(COUNT(DISTINCT pr.id), 0) AS unlinked_pr_rate FROM pull_requests AS pr JOIN project_mapping AS pm ON pr.base_repo_id = pm.row_id AND pm.table = 'repos' WHERE ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND CAST(pr.created_date AS DATE) BETWEEN TO_DATE('$month', 'YYYY-MM-DD') AND TO_DATE('$month', 'YYYY-MM-DD') + INTERVAL '1 MONTH'"
    }
   ]
  },
  {
   "title": "Unlinked PRs Ratio over Month",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT CAST(created_date AS DATE) + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST(created_date AS DATE)) + 1) AS time, COALESCE(pr.sub_project, 'All') AS sub_project, CAST(100 * COUNT(DISTINCT CASE WHEN pr.id IN (SELECT pull_request_id FROM pull_request_issues) THEN pr.id ELSE NULL END) AS NUMERIC) / NULLIF(COUNT(DISTINCT pr.id), 0) AS unlinked_pr_rate FROM pull_requests AS pr JOIN project_mapping AS pm ON pr.base_repo_id = pm.row_id AND pm.table = 'repos' WHERE ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND $__timeFilter(created_date) AND created_date >= $__timeFrom()::timestamp + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST($__timeFrom() AS DATE)) + 1) + INTERVAL '1 MONTH' GROUP BY \"time\", pr.sub_project"
    }
   ]
  },
  {
   "title": "Coding Days % [in $month]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH _commits_groupby_name_and_date AS (SELECT author_name, CAST(authored_date AS DATE) AS _day, COUNT(DISTINCT c.sha) FROM commits AS c JOIN repo_commits AS rc ON c.sha = rc.commit_sha JOIN project_mapping AS pm ON rc.repo_id = pm.row_id WHERE ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND (EXTRACT(ISODOW FROM authored_date) - 1) BETWEEN 0 AND 4 AND CAST(authored_date AS DATE) BETWEEN TO_DATE('$month', 'YYYY-MM-DD') AND TO_DATE('$month', 'YYYY-MM-DD') + INTERVAL '1 MONTH' GROUP BY \"author_name\", CAST(authored_date AS DATE)) SELECT CAST(100 * COUNT(*) AS NUMERIC) / NULLIF((COUNT(DISTINCT author_name) * COUNT(DISTINCT _day)), 0) FROM _commits_groupby_name_and_date"
    }
   ]
  },
  {
   "title": "Percentage of Coding Days Each Month",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH _commits_groupby_name_and_date AS (SELECT author_name, CAST(authored_date AS DATE) AS _day, COUNT(DISTINCT c.sha) FROM commits AS c JOIN repo_commits AS rc ON c.sha = rc.commit_sha JOIN project_mapping AS pm ON rc.repo_id = pm.row_id WHERE ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND ((EXTRACT(ISODOW FROM authored_date) - 1) BETWEEN 0 AND 4) AND $__timeFilter(authored_date) AND authored_date >= $__timeFrom()::timestamp + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST($__timeFrom() AS DATE)) + 1) + INTERVAL '1 MONTH' GROUP BY 1, 2) SELECT _day + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST(_day AS DATE)) + 1) AS time, CAST(100 * COUNT(*) AS NUMERIC) / NULLIF((COUNT(DISTINCT author_name) * COUNT(DISTINCT _day)), 0) AS working_days_percentatages_per_month FROM _commits_groupby_name_and_date GROUP BY time"
    }
   ]
  },
  {
   "title": "Mean Time to Merge [in $month]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(CAST((EXTRACT(EPOCH FROM (pr.merged_date - pr.created_date))/60) AS NUMERIC) / NULLIF(1440, 0)) FROM pull_requests AS pr JOIN project_mapping AS pm ON pr.base_repo_id = pm.row_id AND pm.table = 'repos' WHERE ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND NOT pr.merged_date IS NULL AND CAST(pr.created_date AS DATE) BETWEEN TO_DATE('$month', 'YYYY-MM-DD') AND TO_DATE('$month', 'YYYY-MM-DD') + INTERVAL '1 MONTH'"
    }
   ]
  },
  {
   "title": "Mean Time to Merge over Month",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "rawSql": "SELECT CAST(pr.created_date AS DATE) + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST(pr.created_date AS DATE)) + 1) AS time, COALESCE(pr.sub_project, 'All') AS sub_project, AVG(CAST((EXTRACT(EPOCH FROM (pr.merged_date - pr.created_date))/60) AS NUMERIC) / NULLIF(1440, 0)) AS pr_time_to_merge_in_days FROM pull_requests AS pr JOIN project_mapping AS pm ON pr.base_repo_id = pm.row_id AND pm.table = 'repos' WHERE ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND NOT pr.merged_date IS NULL AND $__timeFilter(pr.created_date) AND pr.created_date >= $__timeFrom()::timestamp + INTERVAL '1 DAY' * (-EXTRACT(DAY FROM CAST($__timeFrom() AS DATE)) + 1) + INTERVAL '1 MONTH' GROUP BY \"time\", pr.sub_project ORDER BY time NULLS FIRST"
    }
   ]
  },
  {
   "title": "Work Done % [in $month]",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT CASE WHEN i.type = 'BUG' THEN i.id ELSE NULL END) AS \"Bug\", COUNT(DISTINCT CASE WHEN i.type <> 'BUG' AND epic_key <> '' THEN i.id ELSE NULL END) AS \"Strategic\", COUNT(DISTINCT CASE WHEN i.type <> 'BUG' AND epic_key = '' THEN i.id ELSE NULL END) AS \"Non-Strategic\" FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id JOIN project_mapping AS pm ON b.id = pm.row_id WHERE ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND NOT i.resolution_date IS NULL AND CAST(resolution_date AS DATE) BETWEEN TO_DATE('$month', 'YYYY-MM-DD') AND TO_DATE('$month', 'YYYY-MM-DD') + INTERVAL '1 MONTH'"
    }
   ]
  },
  {
   "title": "Average Age of Critical Outstanding Defects by Priority",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "rawSql": "SELECT i.priority AS \"Priority\", AVG(CAST((EXTRACT(EPOCH FROM (NOW() - i.created_date))/60) AS NUMERIC) / NULLIF(1440, 0)) AS \"Average Age\" FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id JOIN project_mapping AS pm ON b.id = pm.row_id WHERE ('${project:csv}' = '' OR pm.project_name::text = ANY(ARRAY[${project:singlequote}]::text[])) AND i.status = 'TODO' AND i.type = 'BUG' AND ('${priority:csv}' = '' OR i.priority::text = ANY(ARRAY[${priority:singlequote}]::text[])) GROUP BY i.priority"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 75 },
   "options": {
    "content": "<br/>\n\nThis dashboard is created based on this [data schema](https://devlake.apache.org/docs/DataModels/DevLakeDomainLayerSchema). Want to add more metrics? Please follow the [guide](https://devlake.apache.org/docs/Configuration/Dashboards/GrafanaUserGuide)."
   },
   "targets": [
    {}
   ]
  }
 ]
}