{
 "title": "Weekly Community Retro",
 "tags": [ "OSS Maintainer Dashboard" ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "repo_id",
    "label": "Repo",
    "query": "SELECT name || '-' || id AS text FROM repos"
   },
   {
    "name": "issue_type",
    "label": "Issue Type",
    "query": "SELECT DISTINCT type FROM issues"
   },
   {
    "name": "org",
    "label": "Community Definition - Issues and PRs NOT from Organization(s)",
    "query": "SELECT DISTINCT organization FROM accounts WHERE organization <> ''"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Introduction",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "- Use Cases: This dashboard can be used to track community growth by OSS maintainers.\n- Data Source Required: GitHub users' organizations are used to filter issues/PRs created by certain users. [Publicize users' org](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/publicizing-or-hiding-organization-membership) so that Apache DevLake can collect users' org.\n- This dashboard **DOES NOT** honor the time filter on the top-right corner."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Community Issues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "New Issue Count [Previous Week]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT i.id) FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id WHERE ('${issue_type:csv}' = '' OR i.type::text = ANY(ARRAY[${issue_type:singlequote}]::text[])) AND CAST(i.created_date AS DATE) BETWEEN CURRENT_DATE - INTERVAL '1 day' AND CURRENT_DATE - (EXTRACT(ISODOW FROM CURRENT_DATE) - 1) * INTERVAL '1 day' AND ('${repo_id:csv}' = '' OR b.id::text = ANY(ARRAY[${repo_id:singlequote}]::text[]))"
    }
   ]
  },
  {
   "title": "New Issue Created by Community [Previous Week]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT i.id) FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id WHERE ('${issue_type:csv}' = '' OR i.type::text = ANY(ARRAY[${issue_type:singlequote}]::text[])) AND CAST(i.created_date AS DATE) BETWEEN CURRENT_DATE - INTERVAL '1 day' AND CURRENT_DATE - (EXTRACT(ISODOW FROM CURRENT_DATE) - 1) * INTERVAL '1 day' AND ('${repo_id:csv}' = '' OR b.id::text = ANY(ARRAY[${repo_id:singlequote}]::text[])) AND NOT i.creator_id IN (SELECT DISTINCT id FROM accounts WHERE ('${org:csv}' = '' OR organization::text = ANY(ARRAY[${org:singlequote}]::text[])))"
    }
   ]
  },
  {
   "title": "Ratio of New Issue Created by the Community [Previous Week]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CAST(SUM(CASE WHEN NOT i.creator_id IN (SELECT DISTINCT id FROM accounts WHERE ('${org:csv}' = '' OR organization::text = ANY(ARRAY[${org:singlequote}]::text[]))) THEN 1 ELSE 0 END) AS NUMERIC) / NULLIF(COUNT(DISTINCT i.id), 0) AS community_issue_ratio FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id WHERE ('${issue_type:csv}' = '' OR i.type::text = ANY(ARRAY[${issue_type:singlequote}]::text[])) AND CAST(i.created_date AS DATE) BETWEEN CURRENT_DATE - INTERVAL '1 day' AND CURRENT_DATE - (EXTRACT(ISODOW FROM CURRENT_DATE) - 1) * INTERVAL '1 day' AND ('${repo_id:csv}' = '' OR b.id::text = ANY(ARRAY[${repo_id:singlequote}]::text[]))"
    }
   ]
  },
  {
   "title": "1st Time Issue Reporter [Previous Week]",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT i.creator_name FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id WHERE ('${issue_type:csv}' = '' OR i.type::text = ANY(ARRAY[${issue_type:singlequote}]::text[])) AND CAST(i.created_date AS DATE) BETWEEN CURRENT_DATE - INTERVAL '1 day' AND CURRENT_DATE - (EXTRACT(ISODOW FROM CURRENT_DATE) - 1) * INTERVAL '1 day' AND ('${repo_id:csv}' = '' OR b.id::text = ANY(ARRAY[${repo_id:singlequote}]::text[])) AND NOT i.creator_name IN (SELECT DISTINCT creator_name FROM issues WHERE created_date < CURRENT_DATE - INTERVAL '1 day' AND NOT creator_name IS NULL)"
    }
   ]
  },
  {
   "title": "Community Issues' Response Rate [Previous Week]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH issue_comment_list AS (SELECT i.id AS issue_id, i.url, i.title, ic.id AS comment_id, ic.created_date AS comment_date, ic.body, CASE WHEN NOT ic.id IS NULL THEN RANK() OVER (PARTITION BY i.id ORDER BY ic.created_date ASC NULLS FIRST) ELSE NULL END AS comment_rank FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id LEFT JOIN issue_comments AS ic ON i.id = ic.issue_id WHERE ('${issue_type:csv}' = '' OR i.type::text = ANY(ARRAY[${issue_type:singlequote}]::text[])) AND CAST(i.created_date AS DATE) BETWEEN CURRENT_DATE - INTERVAL '1 day' AND CURRENT_DATE - (EXTRACT(ISODOW FROM CURRENT_DATE) - 1) * INTERVAL '1 day' AND ('${repo_id:csv}' = '' OR b.id::text = ANY(ARRAY[${repo_id:singlequote}]::text[])) AND NOT i.creator_id IN (SELECT DISTINCT id FROM accounts WHERE ('${org:csv}' = '' OR organization::text = ANY(ARRAY[${org:singlequote}]::text[])))) SELECT 1 - CAST(COUNT(DISTINCT CASE WHEN comment_id IS NULL THEN issue_id ELSE NULL END) AS NUMERIC) / NULLIF(COUNT(DISTINCT issue_id), 0) AS response_rate FROM issue_comment_list"
    }
   ]
  },
  {
   "title": "List of New Community Issues with no Comments [Previous Week]",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 13 },
   "targets": [
    {
     "rawSql": "WITH issue_comment_list AS (SELECT i.id AS issue_id, i.url, i.issue_key, i.title, i.creator_name, i.created_date AS issue_created_date, i.status, ic.id AS comment_id, ic.created_date AS comment_date, ic.body, CASE WHEN NOT ic.id IS NULL THEN RANK() OVER (PARTITION BY i.id ORDER BY ic.created_date ASC NULLS FIRST) ELSE NULL END AS comment_rank FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id LEFT JOIN issue_comments AS ic ON i.id = ic.issue_id WHERE ('${issue_type:csv}' = '' OR i.type::text = ANY(ARRAY[${issue_type:singlequote}]::text[])) AND CAST(i.created_date AS DATE) BETWEEN CURRENT_DATE - INTERVAL '1 day' AND CURRENT_DATE - (EXTRACT(ISODOW FROM CURRENT_DATE) - 1) * INTERVAL '1 day' AND ('${repo_id:csv}' = '' OR b.id::text = ANY(ARRAY[${repo_id:singlequote}]::text[])) AND NOT i.creator_id IN (SELECT DISTINCT id FROM accounts WHERE ('${org:csv}' = '' OR organization::text = ANY(ARRAY[${org:singlequote}]::text[])))) SELECT issue_key, title, creator_name, issue_created_date, status, CAST(((EXTRACT(EPOCH FROM (NOW() - issue_created_date))/60)) AS NUMERIC) / NULLIF(1440, 0) AS \"queue_time_in_days\", url FROM issue_comment_list WHERE comment_id IS NULL"
    }
   ]
  },
  {
   "title": "New Community Issues' Average Response Time in Days [Previous Week]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH issue_comment_list AS (SELECT i.id AS issue_id, i.url, i.title, i.created_date AS issue_created_date, ic.id AS comment_id, ic.created_date AS comment_date, ic.body, CASE WHEN NOT ic.id IS NULL THEN RANK() OVER (PARTITION BY i.id ORDER BY ic.created_date ASC NULLS FIRST) ELSE NULL END AS comment_rank FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id LEFT JOIN issue_comments AS ic ON i.id = ic.issue_id WHERE ('${issue_type:csv}' = '' OR i.type::text = ANY(ARRAY[${issue_type:singlequote}]::text[])) AND CAST(i.created_date AS DATE) BETWEEN CURRENT_DATE - INTERVAL '1 day' AND CURRENT_DATE - (EXTRACT(ISODOW FROM CURRENT_DATE) - 1) * INTERVAL '1 day' AND ('${repo_id:csv}' = '' OR b.id::text = ANY(ARRAY[${repo_id:singlequote}]::text[])) AND NOT i.creator_id IN (SELECT DISTINCT id FROM accounts WHERE ('${org:csv}' = '' OR organization::text = ANY(ARRAY[${org:singlequote}]::text[])))) SELECT AVG(CAST(((EXTRACT(EPOCH FROM (comment_date - issue_created_date))/60)) AS NUMERIC) / NULLIF(1440, 0)) FROM issue_comment_list WHERE comment_rank = 1"
    }
   ]
  },
  {
   "title": "List of New Community Issues' 1st Comment [Previous Week]",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "WITH issue_comment_list AS (SELECT REVERSE(SPLIT_PART(REVERSE(i.url), '/', 1)) AS issue_number, i.url, i.issue_key, i.title, i.creator_name, i.created_date AS issue_created_date, ic.id AS comment_id, ic.created_date AS comment_date, ic.body, CASE WHEN NOT ic.id IS NULL THEN RANK() OVER (PARTITION BY i.id ORDER BY ic.created_date ASC NULLS FIRST) ELSE NULL END AS comment_rank FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id LEFT JOIN issue_comments AS ic ON i.id = ic.issue_id WHERE ('${issue_type:csv}' = '' OR i.type::text = ANY(ARRAY[${issue_type:singlequote}]::text[])) AND CAST(i.created_date AS DATE) BETWEEN CURRENT_DATE - INTERVAL '1 day' AND CURRENT_DATE - (EXTRACT(ISODOW FROM CURRENT_DATE) - 1) * INTERVAL '1 day' AND ('${repo_id:csv}' = '' OR b.id::text = ANY(ARRAY[${repo_id:singlequote}]::text[])) AND NOT i.creator_id IN (SELECT DISTINCT id FROM accounts WHERE ('${org:csv}' = '' OR organization::text = ANY(ARRAY[${org:singlequote}]::text[])))) SELECT issue_key, title, creator_name /* body, */, issue_created_date, comment_date, CAST(((EXTRACT(EPOCH FROM (comment_date - issue_created_date))/60)) AS NUMERIC) / NULLIF(1440, 0) AS response_time_in_days, url FROM issue_comment_list WHERE comment_rank = 1"
    }
   ]
  },
  {
   "title": "Community PRs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of New Pull Requests [Previous Week]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT pr.id) AS pull_request_count FROM pull_requests AS pr WHERE CAST(created_date AS DATE) BETWEEN CURRENT_DATE - INTERVAL '1 day' AND CURRENT_DATE - (EXTRACT(ISODOW FROM CURRENT_DATE) - 1) * INTERVAL '1 day' AND ('${repo_id:csv}' = '' OR base_repo_id::text = ANY(ARRAY[${repo_id:singlequote}]::text[]))"
    }
   ]
  },
  {
   "title": "Number of New Pull Requests Created by the Community [Previous Week]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT pr.id) AS pull_request_count FROM pull_requests AS pr WHERE CAST(created_date AS DATE) BETWEEN CURRENT_DATE - INTERVAL '1 day' AND CURRENT_DATE - (EXTRACT(ISODOW FROM CURRENT_DATE) - 1) * INTERVAL '1 day' AND ('${repo_id:csv}' = '' OR base_repo_id::text = ANY(ARRAY[${repo_id:singlequote}]::text[])) AND NOT author_id IN (SELECT DISTINCT id FROM accounts WHERE ('${org:csv}' = '' OR organization::text = ANY(ARRAY[${org:singlequote}]::text[])))"
    }
   ]
  },
  {
   "title": "Ratio of New PR Created by the Community [Previous Week]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CAST(SUM(CASE WHEN NOT author_id IN (SELECT DISTINCT id FROM accounts WHERE ('${org:csv}' = '' OR organization::text = ANY(ARRAY[${org:singlequote}]::text[]))) THEN 1 ELSE 0 END) AS NUMERIC) / NULLIF(COUNT(DISTINCT pr.id), 0) AS community_pr_ratio FROM pull_requests AS pr WHERE CAST(created_date AS DATE) BETWEEN CURRENT_DATE - INTERVAL '1 day' AND CURRENT_DATE - (EXTRACT(ISODOW FROM CURRENT_DATE) - 1) * INTERVAL '1 day' AND ('${repo_id:csv}' = '' OR base_repo_id::text = ANY(ARRAY[${repo_id:singlequote}]::text[]))"
    }
   ]
  },
  {
   "title": "Number of Merged Pull Requests Created by the Community [Previous Week]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT pr.id) AS merged_pull_request_count FROM pull_requests AS pr WHERE CAST(created_date AS DATE) BETWEEN CURRENT_DATE - INTERVAL '1 day' AND CURRENT_DATE - (EXTRACT(ISODOW FROM CURRENT_DATE) - 1) * INTERVAL '1 day' AND ('${repo_id:csv}' = '' OR base_repo_id::text = ANY(ARRAY[${repo_id:singlequote}]::text[])) AND NOT merged_date IS NULL AND NOT author_id IN (SELECT DISTINCT id FROM accounts WHERE ('${org:csv}' = '' OR organization::text = ANY(ARRAY[${org:singlequote}]::text[])))"
    }
   ]
  },
  {
   "title": "Average Time to Merge of Community Pull Requests in Days [Previous Week]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(CAST((EXTRACT(EPOCH FROM (merged_date - created_date))/60) AS NUMERIC) / NULLIF(1440, 0)) FROM pull_requests WHERE CAST(created_date AS DATE) BETWEEN CURRENT_DATE - INTERVAL '1 day' AND CURRENT_DATE - (EXTRACT(ISODOW FROM CURRENT_DATE) - 1) * INTERVAL '1 day' AND ('${repo_id:csv}' = '' OR base_repo_id::text = ANY(ARRAY[${repo_id:singlequote}]::text[])) AND NOT merged_date IS NULL AND NOT author_id IN (SELECT DISTINCT id FROM accounts WHERE ('${org:csv}' = '' OR organization::text = ANY(ARRAY[${org:singlequote}]::text[])))"
    }
   ]
  },
  {
   "title": "First time Contributor [Previous Week]",
   "type": "table",
   "description": "Contributors: the PR authors who have merged PR(s)",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT author_name FROM pull_requests AS pr WHERE CAST(created_date AS DATE) BETWEEN CURRENT_DATE - INTERVAL '1 day' AND CURRENT_DATE - (EXTRACT(ISODOW FROM CURRENT_DATE) - 1) * INTERVAL '1 day' AND NOT merged_date IS NULL AND ('${repo_id:csv}' = '' OR base_repo_id::text = ANY(ARRAY[${repo_id:singlequote}]::text[])) AND NOT author_name IN (SELECT DISTINCT author_name FROM pull_requests WHERE created_date < CURRENT_DATE - INTERVAL '1 day' AND NOT author_name IS NULL)"
    }
   ]
  },
  {
   "title": "Ratio of Merged Pull Requests Created by the Community [Previous Week]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CAST(COUNT(DISTINCT CASE WHEN NOT merged_date IS NULL THEN pr.id ELSE NULL END) AS NUMERIC) / NULLIF(COUNT(DISTINCT pr.id), 0) AS merged_pull_request_ratio FROM pull_requests AS pr WHERE CAST(created_date AS DATE) BETWEEN CURRENT_DATE - INTERVAL '1 day' AND CURRENT_DATE - (EXTRACT(ISODOW FROM CURRENT_DATE) - 1) * INTERVAL '1 day' AND ('${repo_id:csv}' = '' OR base_repo_id::text = ANY(ARRAY[${repo_id:singlequote}]::text[])) AND NOT author_id IN (SELECT DISTINCT id FROM accounts WHERE ('${org:csv}' = '' OR organization::text = ANY(ARRAY[${org:singlequote}]::text[])))"
    }
   ]
  },
  {
   "title": "List of New Community Issues' 1st Comment [Previous Week]",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT pull_request_key, title, status, author_name, created_date, CAST(((EXTRACT(EPOCH FROM (CURRENT_DATE - created_date))/60)) AS NUMERIC) / NULLIF(1440, 0) AS queue_time_in_days, url FROM pull_requests AS pr WHERE CAST(created_date AS DATE) BETWEEN CURRENT_DATE - INTERVAL '1 day' AND CURRENT_DATE - (EXTRACT(ISODOW FROM CURRENT_DATE) - 1) * INTERVAL '1 day' AND ('${repo_id:csv}' = '' OR base_repo_id::text = ANY(ARRAY[${repo_id:singlequote}]::text[])) AND merged_date IS NULL AND NOT author_id IN (SELECT DISTINCT id FROM accounts WHERE ('${org:csv}' = '' OR organization::text = ANY(ARRAY[${org:singlequote}]::text[])))"
    }
   ]
  },
  {
   "title": "Top 20 Community Contributors By Number of PRs Merged [Previous Week]",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT author_name, COUNT(DISTINCT pr.id) AS pull_request_count FROM pull_requests AS pr WHERE CAST(created_date AS DATE) BETWEEN CURRENT_DATE - INTERVAL '1 day' AND CURRENT_DATE - (EXTRACT(ISODOW FROM CURRENT_DATE) - 1) * INTERVAL '1 day' AND ('${repo_id:csv}' = '' OR base_repo_id::text = ANY(ARRAY[${repo_id:singlequote}]::text[])) AND NOT merged_date IS NULL AND NOT author_id IN (SELECT DISTINCT id FROM accounts WHERE ('${org:csv}' = '' OR organization::text = ANY(ARRAY[${org:singlequote}]::text[]))) GROUP BY 1 ORDER BY 2 DESC NULLS LAST LIMIT 20"
    }
   ]
  },
  {
   "title": "Top Community Contributors By PRs Created [All History]",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 10, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT author_id) AS all_contributor_count FROM pull_requests AS pr WHERE ('${repo_id:csv}' = '' OR base_repo_id::text = ANY(ARRAY[${repo_id:singlequote}]::text[])) AND NOT merged_date IS NULL /* and author_id not in (select distinct id from accounts where ('${org:csv}' = '' OR organization::text = ANY(ARRAY[${org:singlequote}]::text[]))) */"
    }
   ]
  },
  {
   "title": "Top 20 Community Contributors By Merged PR Numbers [All History]",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT author_name, COUNT(DISTINCT pr.id) AS merged_pull_request_count FROM pull_requests AS pr WHERE ('${repo_id:csv}' = '' OR base_repo_id::text = ANY(ARRAY[${repo_id:singlequote}]::text[])) AND NOT merged_date IS NULL /* and author_id not in (select distinct id from accounts where ('${org:csv}' = '' OR organization::text = ANY(ARRAY[${org:singlequote}]::text[]))) */ GROUP BY 1 ORDER BY 2 DESC NULLS LAST LIMIT 20"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 63 },
   "options": {
    "content": "<br/>\n\nThis dashboard is created based on this [data schema](https://devlake.apache.org/docs/DataModels/DevLakeDomainLayerSchema). Want to add more metrics? Please follow the [guide](https://devlake.apache.org/docs/Configuration/Dashboards/GrafanaUserGuide)."
   },
   "targets": [
    {}
   ]
  }
 ]
}